version: "2"
linters:
  enable:
    # These are default linters in v2 but listed explicitly for clarity:
    - errcheck
    - govet
    - ineffassign
    - staticcheck # includes gosimple checks in v2
    - unused
    # Additional linters from original config:
    - goconst
    - gosec
    - lll
    - misspell
    - nakedret
    - revive
    - unconvert
  settings:
    lll:
      line-length: 220
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - schema.go
      - pulumiManifest.go
      - pkg/vendored
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
  settings:
    gci:
      sections:
        - standard
        - blank
        - default
        - prefix(github.com/pulumi/)
        - prefix(github.com/JDetmar/pulumi-sendgrid)
      custom-order: true
  exclusions:
    generated: lax
    paths:
      - schema.go
      - pulumiManifest.go
      - pkg/vendored
      - third_party$
      - builtin$
      - examples$
