project_name: pulumi-sendgrid

builds:
  - id: build-provider
    dir: provider
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    ignore: []
    main: ./cmd/pulumi-resource-sendgrid/
    ldflags:
      - -s
      - -w
      - -X github.com/JDetmar/pulumi-sendgrid/provider/pkg/version.Version={{.Tag}}
    binary: pulumi-resource-sendgrid

archives:
  - name_template: "{{ .Binary }}-{{ .Tag }}-{{ .Os }}-{{ .Arch }}"
    id: archive

snapshot:
  name_template: "{{ .Tag }}-SNAPSHOT"

# Generate checksums for all artifacts
checksum:
  name_template: "checksums.txt"
  algorithm: sha256

# Generate Software Bill of Materials (SBOM) for supply chain security
# Users can scan these for vulnerabilities using tools like grype
sboms:
  - artifacts: archive
    documents:
      - "{{ .ArtifactName }}.sbom.json"

# Auto-generate changelog from git commits
# Groups commits by type based on conventional commit prefixes
changelog:
  disable: false
  use: github
  sort: asc
  groups:
    - title: "Features"
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: "Bug Fixes"
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: "Documentation"
      regexp: '^.*?docs(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: "Maintenance"
      regexp: '^.*?(chore|refactor|test|ci)(\([[:word:]]+\))??!?:.+$'
      order: 3
    - title: "Other Changes"
      order: 999
  filters:
    exclude:
      - "^Merge"

release:
  disable: false
  prerelease: auto
  # Include SBOM info in release notes
  footer: |
    ## Security

    Each release artifact includes an SBOM (Software Bill of Materials) file
    (`.sbom.json`) that lists all dependencies. You can scan these for
    vulnerabilities using tools like [grype](https://github.com/anchore/grype):

    ```bash
    grype sbom:./pulumi-resource-sendgrid-{{ .Tag }}-linux-amd64.tar.gz.sbom.json
    ```

    ### SLSA Provenance Attestations

    Binary releases include SLSA provenance attestations generated by GitHub Actions. Verify
    the build provenance of downloaded artifacts using the GitHub CLI:

    ```bash
    gh attestation verify pulumi-resource-sendgrid-{{ .Tag }}-linux-amd64.tar.gz \
      --owner JDetmar
    ```
