project_name: pulumi-sendgrid
builds:
- id: build-provider
  dir: provider
  env:
  - CGO_ENABLED=0
  - GO111MODULE=on
  goos:
  - darwin
  - linux
  goarch:
  - amd64
  - arm64
  ignore: []
  main: ./cmd/pulumi-resource-sendgrid/
  ldflags:
    - -s
    - -w
    - -X
      github.com/JDetmar/pulumi-sendgrid/provider/pkg/version.Version={{.Tag}}
  binary: pulumi-resource-sendgrid
archives:
- name_template: "{{ .Binary }}-{{ .Tag }}-{{ .Os }}-{{ .Arch }}"
  id: archive
snapshot:
  name_template: "{{ .Tag }}-SNAPSHOT"
changelog:
  skip: false
release:
  disable: false
