// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.sendgrid;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class APIKeyArgs extends com.pulumi.resources.ResourceArgs {

    public static final APIKeyArgs Empty = new APIKeyArgs();

    @Import(name="name", required=true)
    private Output<String> name;

    public Output<String> name() {
        return this.name;
    }

    @Import(name="scopes")
    private @Nullable Output<List<String>> scopes;

    public Optional<Output<List<String>>> scopes() {
        return Optional.ofNullable(this.scopes);
    }

    private APIKeyArgs() {}

    private APIKeyArgs(APIKeyArgs $) {
        this.name = $.name;
        this.scopes = $.scopes;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(APIKeyArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private APIKeyArgs $;

        public Builder() {
            $ = new APIKeyArgs();
        }

        public Builder(APIKeyArgs defaults) {
            $ = new APIKeyArgs(Objects.requireNonNull(defaults));
        }

        public Builder name(Output<String> name) {
            $.name = name;
            return this;
        }

        public Builder name(String name) {
            return name(Output.of(name));
        }

        public Builder scopes(@Nullable Output<List<String>> scopes) {
            $.scopes = scopes;
            return this;
        }

        public Builder scopes(List<String> scopes) {
            return scopes(Output.of(scopes));
        }

        public Builder scopes(String... scopes) {
            return scopes(List.of(scopes));
        }

        public APIKeyArgs build() {
            if ($.name == null) {
                throw new MissingRequiredPropertyException("APIKeyArgs", "name");
            }
            return $;
        }
    }

}
