// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.sendgrid;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;


public final class IpPoolArgs extends com.pulumi.resources.ResourceArgs {

    public static final IpPoolArgs Empty = new IpPoolArgs();

    @Import(name="name", required=true)
    private Output<String> name;

    public Output<String> name() {
        return this.name;
    }

    private IpPoolArgs() {}

    private IpPoolArgs(IpPoolArgs $) {
        this.name = $.name;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(IpPoolArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private IpPoolArgs $;

        public Builder() {
            $ = new IpPoolArgs();
        }

        public Builder(IpPoolArgs defaults) {
            $ = new IpPoolArgs(Objects.requireNonNull(defaults));
        }

        public Builder name(Output<String> name) {
            $.name = name;
            return this;
        }

        public Builder name(String name) {
            return name(Output.of(name));
        }

        public IpPoolArgs build() {
            if ($.name == null) {
                throw new MissingRequiredPropertyException("IpPoolArgs", "name");
            }
            return $;
        }
    }

}
