// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.sendgrid;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.core.internal.Codegen;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class ProviderArgs extends com.pulumi.resources.ResourceArgs {

    public static final ProviderArgs Empty = new ProviderArgs();

    /**
     * The SendGrid API key for authentication. Can also be set via the SENDGRID_API_KEY environment variable.
     * 
     */
    @Import(name="apiKey")
    private @Nullable Output<String> apiKey;

    /**
     * @return The SendGrid API key for authentication. Can also be set via the SENDGRID_API_KEY environment variable.
     * 
     */
    public Optional<Output<String>> apiKey() {
        return Optional.ofNullable(this.apiKey);
    }

    /**
     * The SendGrid API base URL. Defaults to https://api.sendgrid.com. Use https://api.eu.sendgrid.com for EU regional subusers.
     * 
     */
    @Import(name="baseUrl")
    private @Nullable Output<String> baseUrl;

    /**
     * @return The SendGrid API base URL. Defaults to https://api.sendgrid.com. Use https://api.eu.sendgrid.com for EU regional subusers.
     * 
     */
    public Optional<Output<String>> baseUrl() {
        return Optional.ofNullable(this.baseUrl);
    }

    private ProviderArgs() {}

    private ProviderArgs(ProviderArgs $) {
        this.apiKey = $.apiKey;
        this.baseUrl = $.baseUrl;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(ProviderArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private ProviderArgs $;

        public Builder() {
            $ = new ProviderArgs();
        }

        public Builder(ProviderArgs defaults) {
            $ = new ProviderArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param apiKey The SendGrid API key for authentication. Can also be set via the SENDGRID_API_KEY environment variable.
         * 
         * @return builder
         * 
         */
        public Builder apiKey(@Nullable Output<String> apiKey) {
            $.apiKey = apiKey;
            return this;
        }

        /**
         * @param apiKey The SendGrid API key for authentication. Can also be set via the SENDGRID_API_KEY environment variable.
         * 
         * @return builder
         * 
         */
        public Builder apiKey(String apiKey) {
            return apiKey(Output.of(apiKey));
        }

        /**
         * @param baseUrl The SendGrid API base URL. Defaults to https://api.sendgrid.com. Use https://api.eu.sendgrid.com for EU regional subusers.
         * 
         * @return builder
         * 
         */
        public Builder baseUrl(@Nullable Output<String> baseUrl) {
            $.baseUrl = baseUrl;
            return this;
        }

        /**
         * @param baseUrl The SendGrid API base URL. Defaults to https://api.sendgrid.com. Use https://api.eu.sendgrid.com for EU regional subusers.
         * 
         * @return builder
         * 
         */
        public Builder baseUrl(String baseUrl) {
            return baseUrl(Output.of(baseUrl));
        }

        public ProviderArgs build() {
            $.baseUrl = Codegen.stringProp("baseUrl").output().arg($.baseUrl).def("https://api.sendgrid.com").getNullable();
            return $;
        }
    }

}
