// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.sendgrid;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Boolean;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class TeammateArgs extends com.pulumi.resources.ResourceArgs {

    public static final TeammateArgs Empty = new TeammateArgs();

    @Import(name="email", required=true)
    private Output<String> email;

    public Output<String> email() {
        return this.email;
    }

    @Import(name="isAdmin")
    private @Nullable Output<Boolean> isAdmin;

    public Optional<Output<Boolean>> isAdmin() {
        return Optional.ofNullable(this.isAdmin);
    }

    @Import(name="scopes")
    private @Nullable Output<List<String>> scopes;

    public Optional<Output<List<String>>> scopes() {
        return Optional.ofNullable(this.scopes);
    }

    private TeammateArgs() {}

    private TeammateArgs(TeammateArgs $) {
        this.email = $.email;
        this.isAdmin = $.isAdmin;
        this.scopes = $.scopes;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(TeammateArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private TeammateArgs $;

        public Builder() {
            $ = new TeammateArgs();
        }

        public Builder(TeammateArgs defaults) {
            $ = new TeammateArgs(Objects.requireNonNull(defaults));
        }

        public Builder email(Output<String> email) {
            $.email = email;
            return this;
        }

        public Builder email(String email) {
            return email(Output.of(email));
        }

        public Builder isAdmin(@Nullable Output<Boolean> isAdmin) {
            $.isAdmin = isAdmin;
            return this;
        }

        public Builder isAdmin(Boolean isAdmin) {
            return isAdmin(Output.of(isAdmin));
        }

        public Builder scopes(@Nullable Output<List<String>> scopes) {
            $.scopes = scopes;
            return this;
        }

        public Builder scopes(List<String> scopes) {
            return scopes(Output.of(scopes));
        }

        public Builder scopes(String... scopes) {
            return scopes(List.of(scopes));
        }

        public TeammateArgs build() {
            if ($.email == null) {
                throw new MissingRequiredPropertyException("TeammateArgs", "email");
            }
            return $;
        }
    }

}
