// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.sendgrid;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import com.pulumi.sendgrid.TeammateArgs;
import com.pulumi.sendgrid.Utilities;
import java.lang.Boolean;
import java.lang.String;
import java.util.List;
import java.util.Optional;
import javax.annotation.Nullable;

/**
 * Manages a SendGrid Teammate.
 * 
 * Teammates are users who have access to your SendGrid account with configurable permissions. You can invite teammates via email and set their initial permissions using scopes.
 * 
 * Note: Teammate invitations expire after 7 days. The invitation can be resent to reset the expiration. Free and Essentials plans allow only one teammate per account.
 * 
 */
@ResourceType(type="sendgrid:index:Teammate")
public class Teammate extends com.pulumi.resources.CustomResource {
    @Export(name="email", refs={String.class}, tree="[0]")
    private Output<String> email;

    public Output<String> email() {
        return this.email;
    }
    @Export(name="firstName", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> firstName;

    public Output<Optional<String>> firstName() {
        return Codegen.optional(this.firstName);
    }
    @Export(name="isAdmin", refs={Boolean.class}, tree="[0]")
    private Output<Boolean> isAdmin;

    public Output<Boolean> isAdmin() {
        return this.isAdmin;
    }
    @Export(name="lastName", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> lastName;

    public Output<Optional<String>> lastName() {
        return Codegen.optional(this.lastName);
    }
    @Export(name="scopes", refs={List.class,String.class}, tree="[0,1]")
    private Output</* @Nullable */ List<String>> scopes;

    public Output<Optional<List<String>>> scopes() {
        return Codegen.optional(this.scopes);
    }
    @Export(name="token", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> token;

    public Output<Optional<String>> token() {
        return Codegen.optional(this.token);
    }
    @Export(name="userType", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> userType;

    public Output<Optional<String>> userType() {
        return Codegen.optional(this.userType);
    }
    @Export(name="username", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> username;

    public Output<Optional<String>> username() {
        return Codegen.optional(this.username);
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public Teammate(java.lang.String name) {
        this(name, TeammateArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public Teammate(java.lang.String name, TeammateArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public Teammate(java.lang.String name, TeammateArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("sendgrid:index:Teammate", name, makeArgs(args, options), makeResourceOptions(options, Codegen.empty()), false);
    }

    private Teammate(java.lang.String name, Output<java.lang.String> id, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("sendgrid:index:Teammate", name, null, makeResourceOptions(options, id), false);
    }

    private static TeammateArgs makeArgs(TeammateArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        if (options != null && options.getUrn().isPresent()) {
            return null;
        }
        return args == null ? TeammateArgs.Empty : args;
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<java.lang.String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static Teammate get(java.lang.String name, Output<java.lang.String> id, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new Teammate(name, id, options);
    }
}
