// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.sendgrid;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import com.pulumi.sendgrid.TemplateArgs;
import com.pulumi.sendgrid.Utilities;
import com.pulumi.sendgrid.outputs.TemplateVersionSummary;
import java.lang.String;
import java.util.List;
import java.util.Optional;
import javax.annotation.Nullable;

/**
 * Manages a SendGrid Transactional Template.
 * 
 * Transactional templates are used to create reusable email templates for transactional emails like receipts, password resets, etc.
 * 
 * Templates can be either &#39;legacy&#39; (plain text/HTML) or &#39;dynamic&#39; (supporting handlebars syntax for personalization).
 * 
 * **Note:** Template versions are managed separately via the TemplateVersion resource.
 * 
 */
@ResourceType(type="sendgrid:index:Template")
public class Template extends com.pulumi.resources.CustomResource {
    @Export(name="generation", refs={String.class}, tree="[0]")
    private Output<String> generation;

    public Output<String> generation() {
        return this.generation;
    }
    @Export(name="name", refs={String.class}, tree="[0]")
    private Output<String> name;

    public Output<String> name() {
        return this.name;
    }
    @Export(name="templateId", refs={String.class}, tree="[0]")
    private Output<String> templateId;

    public Output<String> templateId() {
        return this.templateId;
    }
    @Export(name="updatedAt", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> updatedAt;

    public Output<Optional<String>> updatedAt() {
        return Codegen.optional(this.updatedAt);
    }
    @Export(name="versions", refs={List.class,TemplateVersionSummary.class}, tree="[0,1]")
    private Output</* @Nullable */ List<TemplateVersionSummary>> versions;

    public Output<Optional<List<TemplateVersionSummary>>> versions() {
        return Codegen.optional(this.versions);
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public Template(java.lang.String name) {
        this(name, TemplateArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public Template(java.lang.String name, TemplateArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public Template(java.lang.String name, TemplateArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("sendgrid:index:Template", name, makeArgs(args, options), makeResourceOptions(options, Codegen.empty()), false);
    }

    private Template(java.lang.String name, Output<java.lang.String> id, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("sendgrid:index:Template", name, null, makeResourceOptions(options, id), false);
    }

    private static TemplateArgs makeArgs(TemplateArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        if (options != null && options.getUrn().isPresent()) {
            return null;
        }
        return args == null ? TemplateArgs.Empty : args;
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<java.lang.String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static Template get(java.lang.String name, Output<java.lang.String> id, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new Template(name, id, options);
    }
}
