// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.sendgrid;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Boolean;
import java.lang.Integer;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class TemplateVersionArgs extends com.pulumi.resources.ResourceArgs {

    public static final TemplateVersionArgs Empty = new TemplateVersionArgs();

    @Import(name="active")
    private @Nullable Output<Integer> active;

    public Optional<Output<Integer>> active() {
        return Optional.ofNullable(this.active);
    }

    @Import(name="editor")
    private @Nullable Output<String> editor;

    public Optional<Output<String>> editor() {
        return Optional.ofNullable(this.editor);
    }

    @Import(name="generatePlainContent")
    private @Nullable Output<Boolean> generatePlainContent;

    public Optional<Output<Boolean>> generatePlainContent() {
        return Optional.ofNullable(this.generatePlainContent);
    }

    @Import(name="htmlContent")
    private @Nullable Output<String> htmlContent;

    public Optional<Output<String>> htmlContent() {
        return Optional.ofNullable(this.htmlContent);
    }

    @Import(name="name", required=true)
    private Output<String> name;

    public Output<String> name() {
        return this.name;
    }

    @Import(name="plainContent")
    private @Nullable Output<String> plainContent;

    public Optional<Output<String>> plainContent() {
        return Optional.ofNullable(this.plainContent);
    }

    @Import(name="subject")
    private @Nullable Output<String> subject;

    public Optional<Output<String>> subject() {
        return Optional.ofNullable(this.subject);
    }

    @Import(name="templateId", required=true)
    private Output<String> templateId;

    public Output<String> templateId() {
        return this.templateId;
    }

    @Import(name="testData")
    private @Nullable Output<String> testData;

    public Optional<Output<String>> testData() {
        return Optional.ofNullable(this.testData);
    }

    private TemplateVersionArgs() {}

    private TemplateVersionArgs(TemplateVersionArgs $) {
        this.active = $.active;
        this.editor = $.editor;
        this.generatePlainContent = $.generatePlainContent;
        this.htmlContent = $.htmlContent;
        this.name = $.name;
        this.plainContent = $.plainContent;
        this.subject = $.subject;
        this.templateId = $.templateId;
        this.testData = $.testData;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(TemplateVersionArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private TemplateVersionArgs $;

        public Builder() {
            $ = new TemplateVersionArgs();
        }

        public Builder(TemplateVersionArgs defaults) {
            $ = new TemplateVersionArgs(Objects.requireNonNull(defaults));
        }

        public Builder active(@Nullable Output<Integer> active) {
            $.active = active;
            return this;
        }

        public Builder active(Integer active) {
            return active(Output.of(active));
        }

        public Builder editor(@Nullable Output<String> editor) {
            $.editor = editor;
            return this;
        }

        public Builder editor(String editor) {
            return editor(Output.of(editor));
        }

        public Builder generatePlainContent(@Nullable Output<Boolean> generatePlainContent) {
            $.generatePlainContent = generatePlainContent;
            return this;
        }

        public Builder generatePlainContent(Boolean generatePlainContent) {
            return generatePlainContent(Output.of(generatePlainContent));
        }

        public Builder htmlContent(@Nullable Output<String> htmlContent) {
            $.htmlContent = htmlContent;
            return this;
        }

        public Builder htmlContent(String htmlContent) {
            return htmlContent(Output.of(htmlContent));
        }

        public Builder name(Output<String> name) {
            $.name = name;
            return this;
        }

        public Builder name(String name) {
            return name(Output.of(name));
        }

        public Builder plainContent(@Nullable Output<String> plainContent) {
            $.plainContent = plainContent;
            return this;
        }

        public Builder plainContent(String plainContent) {
            return plainContent(Output.of(plainContent));
        }

        public Builder subject(@Nullable Output<String> subject) {
            $.subject = subject;
            return this;
        }

        public Builder subject(String subject) {
            return subject(Output.of(subject));
        }

        public Builder templateId(Output<String> templateId) {
            $.templateId = templateId;
            return this;
        }

        public Builder templateId(String templateId) {
            return templateId(Output.of(templateId));
        }

        public Builder testData(@Nullable Output<String> testData) {
            $.testData = testData;
            return this;
        }

        public Builder testData(String testData) {
            return testData(Output.of(testData));
        }

        public TemplateVersionArgs build() {
            if ($.name == null) {
                throw new MissingRequiredPropertyException("TemplateVersionArgs", "name");
            }
            if ($.templateId == null) {
                throw new MissingRequiredPropertyException("TemplateVersionArgs", "templateId");
            }
            return $;
        }
    }

}
