// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.sendgrid;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import com.pulumi.sendgrid.UnsubscribeGroupArgs;
import com.pulumi.sendgrid.Utilities;
import java.lang.Boolean;
import java.lang.Integer;
import java.lang.String;
import java.util.Optional;
import javax.annotation.Nullable;

/**
 * Manages a SendGrid Unsubscribe Group (Advanced Suppression Management).
 * 
 * Unsubscribe groups allow recipients to opt out of specific types of emails while still receiving others. For example, you might have separate groups for marketing, newsletters, and product updates, allowing users to choose which types of emails they want to receive.
 * 
 * When a recipient unsubscribes from a group, they will no longer receive emails that are associated with that group.
 * 
 */
@ResourceType(type="sendgrid:index:UnsubscribeGroup")
public class UnsubscribeGroup extends com.pulumi.resources.CustomResource {
    @Export(name="description", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> description;

    public Output<Optional<String>> description() {
        return Codegen.optional(this.description);
    }
    @Export(name="groupId", refs={Integer.class}, tree="[0]")
    private Output<Integer> groupId;

    public Output<Integer> groupId() {
        return this.groupId;
    }
    @Export(name="isDefault", refs={Boolean.class}, tree="[0]")
    private Output</* @Nullable */ Boolean> isDefault;

    public Output<Optional<Boolean>> isDefault() {
        return Codegen.optional(this.isDefault);
    }
    @Export(name="name", refs={String.class}, tree="[0]")
    private Output<String> name;

    public Output<String> name() {
        return this.name;
    }
    @Export(name="unsubscribes", refs={Integer.class}, tree="[0]")
    private Output<Integer> unsubscribes;

    public Output<Integer> unsubscribes() {
        return this.unsubscribes;
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public UnsubscribeGroup(java.lang.String name) {
        this(name, UnsubscribeGroupArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public UnsubscribeGroup(java.lang.String name, UnsubscribeGroupArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public UnsubscribeGroup(java.lang.String name, UnsubscribeGroupArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("sendgrid:index:UnsubscribeGroup", name, makeArgs(args, options), makeResourceOptions(options, Codegen.empty()), false);
    }

    private UnsubscribeGroup(java.lang.String name, Output<java.lang.String> id, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("sendgrid:index:UnsubscribeGroup", name, null, makeResourceOptions(options, id), false);
    }

    private static UnsubscribeGroupArgs makeArgs(UnsubscribeGroupArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        if (options != null && options.getUrn().isPresent()) {
            return null;
        }
        return args == null ? UnsubscribeGroupArgs.Empty : args;
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<java.lang.String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static UnsubscribeGroup get(java.lang.String name, Output<java.lang.String> id, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new UnsubscribeGroup(name, id, options);
    }
}
