// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.sendgrid;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import com.pulumi.sendgrid.Utilities;
import com.pulumi.sendgrid.VerifiedSenderArgs;
import java.lang.Boolean;
import java.lang.Integer;
import java.lang.String;
import java.util.Optional;
import javax.annotation.Nullable;

/**
 * Manages a SendGrid Verified Sender.
 * 
 * Verified Senders are sender identities that have been verified for sending email. After creation, SendGrid will send a verification email to the from_email address. The sender must click the verification link to complete the verification process.
 * 
 * **Note:** The `verified` status will be `false` until the verification email is confirmed.
 * 
 */
@ResourceType(type="sendgrid:index:VerifiedSender")
public class VerifiedSender extends com.pulumi.resources.CustomResource {
    @Export(name="address", refs={String.class}, tree="[0]")
    private Output<String> address;

    public Output<String> address() {
        return this.address;
    }
    @Export(name="address2", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> address2;

    public Output<Optional<String>> address2() {
        return Codegen.optional(this.address2);
    }
    @Export(name="city", refs={String.class}, tree="[0]")
    private Output<String> city;

    public Output<String> city() {
        return this.city;
    }
    @Export(name="country", refs={String.class}, tree="[0]")
    private Output<String> country;

    public Output<String> country() {
        return this.country;
    }
    @Export(name="fromEmail", refs={String.class}, tree="[0]")
    private Output<String> fromEmail;

    public Output<String> fromEmail() {
        return this.fromEmail;
    }
    @Export(name="fromName", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> fromName;

    public Output<Optional<String>> fromName() {
        return Codegen.optional(this.fromName);
    }
    @Export(name="locked", refs={Boolean.class}, tree="[0]")
    private Output<Boolean> locked;

    public Output<Boolean> locked() {
        return this.locked;
    }
    @Export(name="nickname", refs={String.class}, tree="[0]")
    private Output<String> nickname;

    public Output<String> nickname() {
        return this.nickname;
    }
    @Export(name="replyTo", refs={String.class}, tree="[0]")
    private Output<String> replyTo;

    public Output<String> replyTo() {
        return this.replyTo;
    }
    @Export(name="replyToName", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> replyToName;

    public Output<Optional<String>> replyToName() {
        return Codegen.optional(this.replyToName);
    }
    @Export(name="senderId", refs={Integer.class}, tree="[0]")
    private Output<Integer> senderId;

    public Output<Integer> senderId() {
        return this.senderId;
    }
    @Export(name="state", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> state;

    public Output<Optional<String>> state() {
        return Codegen.optional(this.state);
    }
    @Export(name="verified", refs={Boolean.class}, tree="[0]")
    private Output<Boolean> verified;

    public Output<Boolean> verified() {
        return this.verified;
    }
    @Export(name="zip", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> zip;

    public Output<Optional<String>> zip() {
        return Codegen.optional(this.zip);
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public VerifiedSender(java.lang.String name) {
        this(name, VerifiedSenderArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public VerifiedSender(java.lang.String name, VerifiedSenderArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public VerifiedSender(java.lang.String name, VerifiedSenderArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("sendgrid:index:VerifiedSender", name, makeArgs(args, options), makeResourceOptions(options, Codegen.empty()), false);
    }

    private VerifiedSender(java.lang.String name, Output<java.lang.String> id, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("sendgrid:index:VerifiedSender", name, null, makeResourceOptions(options, id), false);
    }

    private static VerifiedSenderArgs makeArgs(VerifiedSenderArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        if (options != null && options.getUrn().isPresent()) {
            return null;
        }
        return args == null ? VerifiedSenderArgs.Empty : args;
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<java.lang.String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static VerifiedSender get(java.lang.String name, Output<java.lang.String> id, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new VerifiedSender(name, id, options);
    }
}
