// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Community.Pulumi.Sendgrid.Outputs
{

    [OutputType]
    public sealed class DNSRecord
    {
        public readonly string Data;
        public readonly string Host;
        public readonly string Type;
        public readonly bool Valid;

        [OutputConstructor]
        private DNSRecord(
            string data,

            string host,

            string type,

            bool valid)
        {
            Data = data;
            Host = host;
            Type = type;
            Valid = valid;
        }
    }
}
