// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Community.Pulumi.Sendgrid.Outputs
{

    [OutputType]
    public sealed class TemplateVersionSummary
    {
        public readonly bool Active;
        public readonly string Id;
        public readonly string Name;
        public readonly string TemplateId;
        public readonly string? UpdatedAt;

        [OutputConstructor]
        private TemplateVersionSummary(
            bool active,

            string id,

            string name,

            string templateId,

            string? updatedAt)
        {
            Active = active;
            Id = id;
            Name = name;
            TemplateId = templateId;
            UpdatedAt = updatedAt;
        }
    }
}
