// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package config

import (
	"github.com/JDetmar/pulumi-sendgrid/sdk/go/sendgrid/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi/config"
)

var _ = internal.GetEnvOrDefault

// The SendGrid API key for authentication. Can also be set via the SENDGRID_API_KEY environment variable.
func GetApiKey(ctx *pulumi.Context) string {
	return config.Get(ctx, "sendgrid:apiKey")
}

// The SendGrid API base URL. Defaults to https://api.sendgrid.com. Use https://api.eu.sendgrid.com for EU regional subusers.
func GetBaseUrl(ctx *pulumi.Context) string {
	v, err := config.Try(ctx, "sendgrid:baseUrl")
	if err == nil {
		return v
	}
	var value string
	value = "https://api.sendgrid.com"
	return value
}
