# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
from . import _utilities
import typing
# Export this package's modules as members:
from .alert import *
from .api_key import *
from .domain_authentication import *
from .event_webhook import *
from .global_suppression import *
from .ip_pool import *
from .link_branding import *
from .provider import *
from .subuser import *
from .teammate import *
from .template import *
from .template_version import *
from .unsubscribe_group import *
from .verified_sender import *
from . import outputs

# Make subpackages available:
if typing.TYPE_CHECKING:
    import pulumi_sendgrid.config as __config
    config = __config
else:
    config = _utilities.lazy_import('pulumi_sendgrid.config')

_utilities.register(
    resource_modules="""
[
 {
  "pkg": "sendgrid",
  "mod": "index",
  "fqn": "pulumi_sendgrid",
  "classes": {
   "sendgrid:index:Alert": "Alert",
   "sendgrid:index:ApiKey": "ApiKey",
   "sendgrid:index:DomainAuthentication": "DomainAuthentication",
   "sendgrid:index:EventWebhook": "EventWebhook",
   "sendgrid:index:GlobalSuppression": "GlobalSuppression",
   "sendgrid:index:IpPool": "IpPool",
   "sendgrid:index:LinkBranding": "LinkBranding",
   "sendgrid:index:Subuser": "Subuser",
   "sendgrid:index:Teammate": "Teammate",
   "sendgrid:index:Template": "Template",
   "sendgrid:index:TemplateVersion": "TemplateVersion",
   "sendgrid:index:UnsubscribeGroup": "UnsubscribeGroup",
   "sendgrid:index:VerifiedSender": "VerifiedSender"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "sendgrid",
  "token": "pulumi:providers:sendgrid",
  "fqn": "pulumi_sendgrid",
  "class": "Provider"
 }
]
"""
)
