# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
from . import _utilities
import typing
# Export this package's modules as members:
from .api_key import *
from .provider import *
from .template import *
from . import outputs

# Make subpackages available:
if typing.TYPE_CHECKING:
    import pulumi_sendgrid.config as __config
    config = __config
else:
    config = _utilities.lazy_import('pulumi_sendgrid.config')

_utilities.register(
    resource_modules="""
[
 {
  "pkg": "sendgrid",
  "mod": "index",
  "fqn": "pulumi_sendgrid",
  "classes": {
   "sendgrid:index:ApiKey": "ApiKey",
   "sendgrid:index:Template": "Template"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "sendgrid",
  "token": "pulumi:providers:sendgrid",
  "fqn": "pulumi_sendgrid",
  "class": "Provider"
 }
]
"""
)
