# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = ['AlertArgs', 'Alert']

@pulumi.input_type
class AlertArgs:
    def __init__(__self__, *,
                 email_to: pulumi.Input[_builtins.str],
                 type: pulumi.Input[_builtins.str],
                 frequency: Optional[pulumi.Input[_builtins.str]] = None,
                 percentage: Optional[pulumi.Input[_builtins.int]] = None):
        """
        The set of arguments for constructing a Alert resource.
        """
        pulumi.set(__self__, "email_to", email_to)
        pulumi.set(__self__, "type", type)
        if frequency is not None:
            pulumi.set(__self__, "frequency", frequency)
        if percentage is not None:
            pulumi.set(__self__, "percentage", percentage)

    @_builtins.property
    @pulumi.getter(name="emailTo")
    def email_to(self) -> pulumi.Input[_builtins.str]:
        return pulumi.get(self, "email_to")

    @email_to.setter
    def email_to(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "email_to", value)

    @_builtins.property
    @pulumi.getter
    def type(self) -> pulumi.Input[_builtins.str]:
        return pulumi.get(self, "type")

    @type.setter
    def type(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "type", value)

    @_builtins.property
    @pulumi.getter
    def frequency(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "frequency")

    @frequency.setter
    def frequency(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "frequency", value)

    @_builtins.property
    @pulumi.getter
    def percentage(self) -> Optional[pulumi.Input[_builtins.int]]:
        return pulumi.get(self, "percentage")

    @percentage.setter
    def percentage(self, value: Optional[pulumi.Input[_builtins.int]]):
        pulumi.set(self, "percentage", value)


@pulumi.type_token("sendgrid:index:Alert")
class Alert(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 email_to: Optional[pulumi.Input[_builtins.str]] = None,
                 frequency: Optional[pulumi.Input[_builtins.str]] = None,
                 percentage: Optional[pulumi.Input[_builtins.int]] = None,
                 type: Optional[pulumi.Input[_builtins.str]] = None,
                 __props__=None):
        """
        Manages a SendGrid Alert.

        Alerts notify you via email about important account events. Two types are available:

        1. **usage_limit**: Notifies when your email usage reaches a specified percentage of your plan limit.
        2. **stats_notification**: Sends periodic email statistics (daily, weekly, or monthly).

        You can create multiple alerts of the same type with different email recipients.

        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: AlertArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Manages a SendGrid Alert.

        Alerts notify you via email about important account events. Two types are available:

        1. **usage_limit**: Notifies when your email usage reaches a specified percentage of your plan limit.
        2. **stats_notification**: Sends periodic email statistics (daily, weekly, or monthly).

        You can create multiple alerts of the same type with different email recipients.

        :param str resource_name: The name of the resource.
        :param AlertArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(AlertArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 email_to: Optional[pulumi.Input[_builtins.str]] = None,
                 frequency: Optional[pulumi.Input[_builtins.str]] = None,
                 percentage: Optional[pulumi.Input[_builtins.int]] = None,
                 type: Optional[pulumi.Input[_builtins.str]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = AlertArgs.__new__(AlertArgs)

            if email_to is None and not opts.urn:
                raise TypeError("Missing required property 'email_to'")
            __props__.__dict__["email_to"] = email_to
            __props__.__dict__["frequency"] = frequency
            __props__.__dict__["percentage"] = percentage
            if type is None and not opts.urn:
                raise TypeError("Missing required property 'type'")
            __props__.__dict__["type"] = type
            __props__.__dict__["alert_id"] = None
            __props__.__dict__["created_at"] = None
            __props__.__dict__["updated_at"] = None
        super(Alert, __self__).__init__(
            'sendgrid:index:Alert',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None) -> 'Alert':
        """
        Get an existing Alert resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = AlertArgs.__new__(AlertArgs)

        __props__.__dict__["alert_id"] = None
        __props__.__dict__["created_at"] = None
        __props__.__dict__["email_to"] = None
        __props__.__dict__["frequency"] = None
        __props__.__dict__["percentage"] = None
        __props__.__dict__["type"] = None
        __props__.__dict__["updated_at"] = None
        return Alert(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter(name="alertId")
    def alert_id(self) -> pulumi.Output[_builtins.int]:
        return pulumi.get(self, "alert_id")

    @_builtins.property
    @pulumi.getter(name="createdAt")
    def created_at(self) -> pulumi.Output[_builtins.int]:
        return pulumi.get(self, "created_at")

    @_builtins.property
    @pulumi.getter(name="emailTo")
    def email_to(self) -> pulumi.Output[_builtins.str]:
        return pulumi.get(self, "email_to")

    @_builtins.property
    @pulumi.getter
    def frequency(self) -> pulumi.Output[Optional[_builtins.str]]:
        return pulumi.get(self, "frequency")

    @_builtins.property
    @pulumi.getter
    def percentage(self) -> pulumi.Output[Optional[_builtins.int]]:
        return pulumi.get(self, "percentage")

    @_builtins.property
    @pulumi.getter
    def type(self) -> pulumi.Output[_builtins.str]:
        return pulumi.get(self, "type")

    @_builtins.property
    @pulumi.getter(name="updatedAt")
    def updated_at(self) -> pulumi.Output[_builtins.int]:
        return pulumi.get(self, "updated_at")

