# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from . import outputs

__all__ = ['DomainAuthenticationArgs', 'DomainAuthentication']

@pulumi.input_type
class DomainAuthenticationArgs:
    def __init__(__self__, *,
                 domain: pulumi.Input[_builtins.str],
                 automatic_security: Optional[pulumi.Input[_builtins.bool]] = None,
                 custom_dkim_selector: Optional[pulumi.Input[_builtins.str]] = None,
                 custom_spf: Optional[pulumi.Input[_builtins.bool]] = None,
                 default: Optional[pulumi.Input[_builtins.bool]] = None,
                 ips: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 region: Optional[pulumi.Input[_builtins.str]] = None,
                 subdomain: Optional[pulumi.Input[_builtins.str]] = None):
        """
        The set of arguments for constructing a DomainAuthentication resource.
        """
        pulumi.set(__self__, "domain", domain)
        if automatic_security is not None:
            pulumi.set(__self__, "automatic_security", automatic_security)
        if custom_dkim_selector is not None:
            pulumi.set(__self__, "custom_dkim_selector", custom_dkim_selector)
        if custom_spf is not None:
            pulumi.set(__self__, "custom_spf", custom_spf)
        if default is not None:
            pulumi.set(__self__, "default", default)
        if ips is not None:
            pulumi.set(__self__, "ips", ips)
        if region is not None:
            pulumi.set(__self__, "region", region)
        if subdomain is not None:
            pulumi.set(__self__, "subdomain", subdomain)

    @_builtins.property
    @pulumi.getter
    def domain(self) -> pulumi.Input[_builtins.str]:
        return pulumi.get(self, "domain")

    @domain.setter
    def domain(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "domain", value)

    @_builtins.property
    @pulumi.getter(name="automaticSecurity")
    def automatic_security(self) -> Optional[pulumi.Input[_builtins.bool]]:
        return pulumi.get(self, "automatic_security")

    @automatic_security.setter
    def automatic_security(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "automatic_security", value)

    @_builtins.property
    @pulumi.getter(name="customDkimSelector")
    def custom_dkim_selector(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "custom_dkim_selector")

    @custom_dkim_selector.setter
    def custom_dkim_selector(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "custom_dkim_selector", value)

    @_builtins.property
    @pulumi.getter(name="customSpf")
    def custom_spf(self) -> Optional[pulumi.Input[_builtins.bool]]:
        return pulumi.get(self, "custom_spf")

    @custom_spf.setter
    def custom_spf(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "custom_spf", value)

    @_builtins.property
    @pulumi.getter
    def default(self) -> Optional[pulumi.Input[_builtins.bool]]:
        return pulumi.get(self, "default")

    @default.setter
    def default(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "default", value)

    @_builtins.property
    @pulumi.getter
    def ips(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]:
        return pulumi.get(self, "ips")

    @ips.setter
    def ips(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "ips", value)

    @_builtins.property
    @pulumi.getter
    def region(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "region")

    @region.setter
    def region(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "region", value)

    @_builtins.property
    @pulumi.getter
    def subdomain(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "subdomain")

    @subdomain.setter
    def subdomain(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "subdomain", value)


@pulumi.type_token("sendgrid:index:DomainAuthentication")
class DomainAuthentication(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 automatic_security: Optional[pulumi.Input[_builtins.bool]] = None,
                 custom_dkim_selector: Optional[pulumi.Input[_builtins.str]] = None,
                 custom_spf: Optional[pulumi.Input[_builtins.bool]] = None,
                 default: Optional[pulumi.Input[_builtins.bool]] = None,
                 domain: Optional[pulumi.Input[_builtins.str]] = None,
                 ips: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 region: Optional[pulumi.Input[_builtins.str]] = None,
                 subdomain: Optional[pulumi.Input[_builtins.str]] = None,
                 __props__=None):
        """
        Manages a SendGrid Domain Authentication.

        Domain Authentication (formerly Domain Whitelabel) allows you to authenticate your domain so that emails appear to come directly from your domain, removing the 'via sendgrid.net' message that recipients may see.

        After creating this resource, you must add the DNS records to your domain's DNS settings and then validate the domain using the SendGrid console or API.

        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: DomainAuthenticationArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Manages a SendGrid Domain Authentication.

        Domain Authentication (formerly Domain Whitelabel) allows you to authenticate your domain so that emails appear to come directly from your domain, removing the 'via sendgrid.net' message that recipients may see.

        After creating this resource, you must add the DNS records to your domain's DNS settings and then validate the domain using the SendGrid console or API.

        :param str resource_name: The name of the resource.
        :param DomainAuthenticationArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(DomainAuthenticationArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 automatic_security: Optional[pulumi.Input[_builtins.bool]] = None,
                 custom_dkim_selector: Optional[pulumi.Input[_builtins.str]] = None,
                 custom_spf: Optional[pulumi.Input[_builtins.bool]] = None,
                 default: Optional[pulumi.Input[_builtins.bool]] = None,
                 domain: Optional[pulumi.Input[_builtins.str]] = None,
                 ips: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 region: Optional[pulumi.Input[_builtins.str]] = None,
                 subdomain: Optional[pulumi.Input[_builtins.str]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = DomainAuthenticationArgs.__new__(DomainAuthenticationArgs)

            __props__.__dict__["automatic_security"] = automatic_security
            __props__.__dict__["custom_dkim_selector"] = custom_dkim_selector
            __props__.__dict__["custom_spf"] = custom_spf
            __props__.__dict__["default"] = default
            if domain is None and not opts.urn:
                raise TypeError("Missing required property 'domain'")
            __props__.__dict__["domain"] = domain
            __props__.__dict__["ips"] = ips
            __props__.__dict__["region"] = region
            __props__.__dict__["subdomain"] = subdomain
            __props__.__dict__["dkim1"] = None
            __props__.__dict__["dkim2"] = None
            __props__.__dict__["domain_id"] = None
            __props__.__dict__["legacy"] = None
            __props__.__dict__["mail_cname"] = None
            __props__.__dict__["user_id"] = None
            __props__.__dict__["username"] = None
            __props__.__dict__["valid"] = None
        super(DomainAuthentication, __self__).__init__(
            'sendgrid:index:DomainAuthentication',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None) -> 'DomainAuthentication':
        """
        Get an existing DomainAuthentication resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = DomainAuthenticationArgs.__new__(DomainAuthenticationArgs)

        __props__.__dict__["automatic_security"] = None
        __props__.__dict__["custom_dkim_selector"] = None
        __props__.__dict__["custom_spf"] = None
        __props__.__dict__["default"] = None
        __props__.__dict__["dkim1"] = None
        __props__.__dict__["dkim2"] = None
        __props__.__dict__["domain"] = None
        __props__.__dict__["domain_id"] = None
        __props__.__dict__["ips"] = None
        __props__.__dict__["legacy"] = None
        __props__.__dict__["mail_cname"] = None
        __props__.__dict__["region"] = None
        __props__.__dict__["subdomain"] = None
        __props__.__dict__["user_id"] = None
        __props__.__dict__["username"] = None
        __props__.__dict__["valid"] = None
        return DomainAuthentication(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter(name="automaticSecurity")
    def automatic_security(self) -> pulumi.Output[Optional[_builtins.bool]]:
        return pulumi.get(self, "automatic_security")

    @_builtins.property
    @pulumi.getter(name="customDkimSelector")
    def custom_dkim_selector(self) -> pulumi.Output[Optional[_builtins.str]]:
        return pulumi.get(self, "custom_dkim_selector")

    @_builtins.property
    @pulumi.getter(name="customSpf")
    def custom_spf(self) -> pulumi.Output[Optional[_builtins.bool]]:
        return pulumi.get(self, "custom_spf")

    @_builtins.property
    @pulumi.getter
    def default(self) -> pulumi.Output[Optional[_builtins.bool]]:
        return pulumi.get(self, "default")

    @_builtins.property
    @pulumi.getter
    def dkim1(self) -> pulumi.Output[Optional['outputs.DNSRecord']]:
        return pulumi.get(self, "dkim1")

    @_builtins.property
    @pulumi.getter
    def dkim2(self) -> pulumi.Output[Optional['outputs.DNSRecord']]:
        return pulumi.get(self, "dkim2")

    @_builtins.property
    @pulumi.getter
    def domain(self) -> pulumi.Output[_builtins.str]:
        return pulumi.get(self, "domain")

    @_builtins.property
    @pulumi.getter(name="domainId")
    def domain_id(self) -> pulumi.Output[_builtins.int]:
        return pulumi.get(self, "domain_id")

    @_builtins.property
    @pulumi.getter
    def ips(self) -> pulumi.Output[Optional[Sequence[_builtins.str]]]:
        return pulumi.get(self, "ips")

    @_builtins.property
    @pulumi.getter
    def legacy(self) -> pulumi.Output[_builtins.bool]:
        return pulumi.get(self, "legacy")

    @_builtins.property
    @pulumi.getter(name="mailCname")
    def mail_cname(self) -> pulumi.Output[Optional['outputs.DNSRecord']]:
        return pulumi.get(self, "mail_cname")

    @_builtins.property
    @pulumi.getter
    def region(self) -> pulumi.Output[Optional[_builtins.str]]:
        return pulumi.get(self, "region")

    @_builtins.property
    @pulumi.getter
    def subdomain(self) -> pulumi.Output[Optional[_builtins.str]]:
        return pulumi.get(self, "subdomain")

    @_builtins.property
    @pulumi.getter(name="userId")
    def user_id(self) -> pulumi.Output[_builtins.int]:
        return pulumi.get(self, "user_id")

    @_builtins.property
    @pulumi.getter
    def username(self) -> pulumi.Output[_builtins.str]:
        return pulumi.get(self, "username")

    @_builtins.property
    @pulumi.getter
    def valid(self) -> pulumi.Output[_builtins.bool]:
        return pulumi.get(self, "valid")

