# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from . import outputs

__all__ = ['LinkBrandingArgs', 'LinkBranding']

@pulumi.input_type
class LinkBrandingArgs:
    def __init__(__self__, *,
                 domain: pulumi.Input[_builtins.str],
                 default: Optional[pulumi.Input[_builtins.bool]] = None,
                 region: Optional[pulumi.Input[_builtins.str]] = None,
                 subdomain: Optional[pulumi.Input[_builtins.str]] = None):
        """
        The set of arguments for constructing a LinkBranding resource.
        """
        pulumi.set(__self__, "domain", domain)
        if default is not None:
            pulumi.set(__self__, "default", default)
        if region is not None:
            pulumi.set(__self__, "region", region)
        if subdomain is not None:
            pulumi.set(__self__, "subdomain", subdomain)

    @_builtins.property
    @pulumi.getter
    def domain(self) -> pulumi.Input[_builtins.str]:
        return pulumi.get(self, "domain")

    @domain.setter
    def domain(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "domain", value)

    @_builtins.property
    @pulumi.getter
    def default(self) -> Optional[pulumi.Input[_builtins.bool]]:
        return pulumi.get(self, "default")

    @default.setter
    def default(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "default", value)

    @_builtins.property
    @pulumi.getter
    def region(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "region")

    @region.setter
    def region(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "region", value)

    @_builtins.property
    @pulumi.getter
    def subdomain(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "subdomain")

    @subdomain.setter
    def subdomain(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "subdomain", value)


@pulumi.type_token("sendgrid:index:LinkBranding")
class LinkBranding(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 default: Optional[pulumi.Input[_builtins.bool]] = None,
                 domain: Optional[pulumi.Input[_builtins.str]] = None,
                 region: Optional[pulumi.Input[_builtins.str]] = None,
                 subdomain: Optional[pulumi.Input[_builtins.str]] = None,
                 __props__=None):
        """
        Manages a SendGrid Link Branding.

        Link Branding (formerly Link Whitelabel) allows you to customize the links in your emails to use your own domain instead of sendgrid.net. This helps improve deliverability and brand recognition.

        After creating this resource, you must add the DNS records to your domain's DNS settings and then validate the link branding using the SendGrid console or API.

        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: LinkBrandingArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Manages a SendGrid Link Branding.

        Link Branding (formerly Link Whitelabel) allows you to customize the links in your emails to use your own domain instead of sendgrid.net. This helps improve deliverability and brand recognition.

        After creating this resource, you must add the DNS records to your domain's DNS settings and then validate the link branding using the SendGrid console or API.

        :param str resource_name: The name of the resource.
        :param LinkBrandingArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(LinkBrandingArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 default: Optional[pulumi.Input[_builtins.bool]] = None,
                 domain: Optional[pulumi.Input[_builtins.str]] = None,
                 region: Optional[pulumi.Input[_builtins.str]] = None,
                 subdomain: Optional[pulumi.Input[_builtins.str]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = LinkBrandingArgs.__new__(LinkBrandingArgs)

            __props__.__dict__["default"] = default
            if domain is None and not opts.urn:
                raise TypeError("Missing required property 'domain'")
            __props__.__dict__["domain"] = domain
            __props__.__dict__["region"] = region
            __props__.__dict__["subdomain"] = subdomain
            __props__.__dict__["brand_cname"] = None
            __props__.__dict__["legacy"] = None
            __props__.__dict__["link_id"] = None
            __props__.__dict__["owner_cname"] = None
            __props__.__dict__["user_id"] = None
            __props__.__dict__["username"] = None
            __props__.__dict__["valid"] = None
        super(LinkBranding, __self__).__init__(
            'sendgrid:index:LinkBranding',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None) -> 'LinkBranding':
        """
        Get an existing LinkBranding resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = LinkBrandingArgs.__new__(LinkBrandingArgs)

        __props__.__dict__["brand_cname"] = None
        __props__.__dict__["default"] = None
        __props__.__dict__["domain"] = None
        __props__.__dict__["legacy"] = None
        __props__.__dict__["link_id"] = None
        __props__.__dict__["owner_cname"] = None
        __props__.__dict__["region"] = None
        __props__.__dict__["subdomain"] = None
        __props__.__dict__["user_id"] = None
        __props__.__dict__["username"] = None
        __props__.__dict__["valid"] = None
        return LinkBranding(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter(name="brandCname")
    def brand_cname(self) -> pulumi.Output[Optional['outputs.LinkBrandingDNSRecord']]:
        return pulumi.get(self, "brand_cname")

    @_builtins.property
    @pulumi.getter
    def default(self) -> pulumi.Output[Optional[_builtins.bool]]:
        return pulumi.get(self, "default")

    @_builtins.property
    @pulumi.getter
    def domain(self) -> pulumi.Output[_builtins.str]:
        return pulumi.get(self, "domain")

    @_builtins.property
    @pulumi.getter
    def legacy(self) -> pulumi.Output[_builtins.bool]:
        return pulumi.get(self, "legacy")

    @_builtins.property
    @pulumi.getter(name="linkId")
    def link_id(self) -> pulumi.Output[_builtins.int]:
        return pulumi.get(self, "link_id")

    @_builtins.property
    @pulumi.getter(name="ownerCname")
    def owner_cname(self) -> pulumi.Output[Optional['outputs.LinkBrandingDNSRecord']]:
        return pulumi.get(self, "owner_cname")

    @_builtins.property
    @pulumi.getter
    def region(self) -> pulumi.Output[Optional[_builtins.str]]:
        return pulumi.get(self, "region")

    @_builtins.property
    @pulumi.getter
    def subdomain(self) -> pulumi.Output[Optional[_builtins.str]]:
        return pulumi.get(self, "subdomain")

    @_builtins.property
    @pulumi.getter(name="userId")
    def user_id(self) -> pulumi.Output[_builtins.int]:
        return pulumi.get(self, "user_id")

    @_builtins.property
    @pulumi.getter
    def username(self) -> pulumi.Output[_builtins.str]:
        return pulumi.get(self, "username")

    @_builtins.property
    @pulumi.getter
    def valid(self) -> pulumi.Output[_builtins.bool]:
        return pulumi.get(self, "valid")

