# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = ['TemplateVersionArgs', 'TemplateVersion']

@pulumi.input_type
class TemplateVersionArgs:
    def __init__(__self__, *,
                 name: pulumi.Input[_builtins.str],
                 template_id: pulumi.Input[_builtins.str],
                 active: Optional[pulumi.Input[_builtins.int]] = None,
                 editor: Optional[pulumi.Input[_builtins.str]] = None,
                 generate_plain_content: Optional[pulumi.Input[_builtins.bool]] = None,
                 html_content: Optional[pulumi.Input[_builtins.str]] = None,
                 plain_content: Optional[pulumi.Input[_builtins.str]] = None,
                 subject: Optional[pulumi.Input[_builtins.str]] = None,
                 test_data: Optional[pulumi.Input[_builtins.str]] = None):
        """
        The set of arguments for constructing a TemplateVersion resource.
        """
        pulumi.set(__self__, "name", name)
        pulumi.set(__self__, "template_id", template_id)
        if active is not None:
            pulumi.set(__self__, "active", active)
        if editor is not None:
            pulumi.set(__self__, "editor", editor)
        if generate_plain_content is not None:
            pulumi.set(__self__, "generate_plain_content", generate_plain_content)
        if html_content is not None:
            pulumi.set(__self__, "html_content", html_content)
        if plain_content is not None:
            pulumi.set(__self__, "plain_content", plain_content)
        if subject is not None:
            pulumi.set(__self__, "subject", subject)
        if test_data is not None:
            pulumi.set(__self__, "test_data", test_data)

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Input[_builtins.str]:
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter(name="templateId")
    def template_id(self) -> pulumi.Input[_builtins.str]:
        return pulumi.get(self, "template_id")

    @template_id.setter
    def template_id(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "template_id", value)

    @_builtins.property
    @pulumi.getter
    def active(self) -> Optional[pulumi.Input[_builtins.int]]:
        return pulumi.get(self, "active")

    @active.setter
    def active(self, value: Optional[pulumi.Input[_builtins.int]]):
        pulumi.set(self, "active", value)

    @_builtins.property
    @pulumi.getter
    def editor(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "editor")

    @editor.setter
    def editor(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "editor", value)

    @_builtins.property
    @pulumi.getter(name="generatePlainContent")
    def generate_plain_content(self) -> Optional[pulumi.Input[_builtins.bool]]:
        return pulumi.get(self, "generate_plain_content")

    @generate_plain_content.setter
    def generate_plain_content(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "generate_plain_content", value)

    @_builtins.property
    @pulumi.getter(name="htmlContent")
    def html_content(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "html_content")

    @html_content.setter
    def html_content(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "html_content", value)

    @_builtins.property
    @pulumi.getter(name="plainContent")
    def plain_content(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "plain_content")

    @plain_content.setter
    def plain_content(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "plain_content", value)

    @_builtins.property
    @pulumi.getter
    def subject(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "subject")

    @subject.setter
    def subject(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "subject", value)

    @_builtins.property
    @pulumi.getter(name="testData")
    def test_data(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "test_data")

    @test_data.setter
    def test_data(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "test_data", value)


@pulumi.type_token("sendgrid:index:TemplateVersion")
class TemplateVersion(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 active: Optional[pulumi.Input[_builtins.int]] = None,
                 editor: Optional[pulumi.Input[_builtins.str]] = None,
                 generate_plain_content: Optional[pulumi.Input[_builtins.bool]] = None,
                 html_content: Optional[pulumi.Input[_builtins.str]] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 plain_content: Optional[pulumi.Input[_builtins.str]] = None,
                 subject: Optional[pulumi.Input[_builtins.str]] = None,
                 template_id: Optional[pulumi.Input[_builtins.str]] = None,
                 test_data: Optional[pulumi.Input[_builtins.str]] = None,
                 __props__=None):
        """
        Manages a SendGrid Template Version.

        Template versions contain the actual content of transactional emails, including the subject line, HTML content, and plain text content.

        Each template can have multiple versions, but only one can be active at a time. The active version is used when sending emails through the template.

        **Note:** Dynamic templates support handlebars syntax for personalization.

        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: TemplateVersionArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Manages a SendGrid Template Version.

        Template versions contain the actual content of transactional emails, including the subject line, HTML content, and plain text content.

        Each template can have multiple versions, but only one can be active at a time. The active version is used when sending emails through the template.

        **Note:** Dynamic templates support handlebars syntax for personalization.

        :param str resource_name: The name of the resource.
        :param TemplateVersionArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(TemplateVersionArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 active: Optional[pulumi.Input[_builtins.int]] = None,
                 editor: Optional[pulumi.Input[_builtins.str]] = None,
                 generate_plain_content: Optional[pulumi.Input[_builtins.bool]] = None,
                 html_content: Optional[pulumi.Input[_builtins.str]] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 plain_content: Optional[pulumi.Input[_builtins.str]] = None,
                 subject: Optional[pulumi.Input[_builtins.str]] = None,
                 template_id: Optional[pulumi.Input[_builtins.str]] = None,
                 test_data: Optional[pulumi.Input[_builtins.str]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = TemplateVersionArgs.__new__(TemplateVersionArgs)

            __props__.__dict__["active"] = active
            __props__.__dict__["editor"] = editor
            __props__.__dict__["generate_plain_content"] = generate_plain_content
            __props__.__dict__["html_content"] = html_content
            if name is None and not opts.urn:
                raise TypeError("Missing required property 'name'")
            __props__.__dict__["name"] = name
            __props__.__dict__["plain_content"] = plain_content
            __props__.__dict__["subject"] = subject
            if template_id is None and not opts.urn:
                raise TypeError("Missing required property 'template_id'")
            __props__.__dict__["template_id"] = template_id
            __props__.__dict__["test_data"] = test_data
            __props__.__dict__["thumbnail_url"] = None
            __props__.__dict__["updated_at"] = None
            __props__.__dict__["version_id"] = None
        super(TemplateVersion, __self__).__init__(
            'sendgrid:index:TemplateVersion',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None) -> 'TemplateVersion':
        """
        Get an existing TemplateVersion resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = TemplateVersionArgs.__new__(TemplateVersionArgs)

        __props__.__dict__["active"] = None
        __props__.__dict__["editor"] = None
        __props__.__dict__["generate_plain_content"] = None
        __props__.__dict__["html_content"] = None
        __props__.__dict__["name"] = None
        __props__.__dict__["plain_content"] = None
        __props__.__dict__["subject"] = None
        __props__.__dict__["template_id"] = None
        __props__.__dict__["test_data"] = None
        __props__.__dict__["thumbnail_url"] = None
        __props__.__dict__["updated_at"] = None
        __props__.__dict__["version_id"] = None
        return TemplateVersion(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter
    def active(self) -> pulumi.Output[Optional[_builtins.int]]:
        return pulumi.get(self, "active")

    @_builtins.property
    @pulumi.getter
    def editor(self) -> pulumi.Output[Optional[_builtins.str]]:
        return pulumi.get(self, "editor")

    @_builtins.property
    @pulumi.getter(name="generatePlainContent")
    def generate_plain_content(self) -> pulumi.Output[Optional[_builtins.bool]]:
        return pulumi.get(self, "generate_plain_content")

    @_builtins.property
    @pulumi.getter(name="htmlContent")
    def html_content(self) -> pulumi.Output[Optional[_builtins.str]]:
        return pulumi.get(self, "html_content")

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Output[_builtins.str]:
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter(name="plainContent")
    def plain_content(self) -> pulumi.Output[Optional[_builtins.str]]:
        return pulumi.get(self, "plain_content")

    @_builtins.property
    @pulumi.getter
    def subject(self) -> pulumi.Output[Optional[_builtins.str]]:
        return pulumi.get(self, "subject")

    @_builtins.property
    @pulumi.getter(name="templateId")
    def template_id(self) -> pulumi.Output[_builtins.str]:
        return pulumi.get(self, "template_id")

    @_builtins.property
    @pulumi.getter(name="testData")
    def test_data(self) -> pulumi.Output[Optional[_builtins.str]]:
        return pulumi.get(self, "test_data")

    @_builtins.property
    @pulumi.getter(name="thumbnailUrl")
    def thumbnail_url(self) -> pulumi.Output[Optional[_builtins.str]]:
        return pulumi.get(self, "thumbnail_url")

    @_builtins.property
    @pulumi.getter(name="updatedAt")
    def updated_at(self) -> pulumi.Output[Optional[_builtins.str]]:
        return pulumi.get(self, "updated_at")

    @_builtins.property
    @pulumi.getter(name="versionId")
    def version_id(self) -> pulumi.Output[_builtins.str]:
        return pulumi.get(self, "version_id")

