# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = ['VerifiedSenderArgs', 'VerifiedSender']

@pulumi.input_type
class VerifiedSenderArgs:
    def __init__(__self__, *,
                 address: pulumi.Input[_builtins.str],
                 city: pulumi.Input[_builtins.str],
                 country: pulumi.Input[_builtins.str],
                 from_email: pulumi.Input[_builtins.str],
                 nickname: pulumi.Input[_builtins.str],
                 reply_to: pulumi.Input[_builtins.str],
                 address2: Optional[pulumi.Input[_builtins.str]] = None,
                 from_name: Optional[pulumi.Input[_builtins.str]] = None,
                 reply_to_name: Optional[pulumi.Input[_builtins.str]] = None,
                 state: Optional[pulumi.Input[_builtins.str]] = None,
                 zip: Optional[pulumi.Input[_builtins.str]] = None):
        """
        The set of arguments for constructing a VerifiedSender resource.
        """
        pulumi.set(__self__, "address", address)
        pulumi.set(__self__, "city", city)
        pulumi.set(__self__, "country", country)
        pulumi.set(__self__, "from_email", from_email)
        pulumi.set(__self__, "nickname", nickname)
        pulumi.set(__self__, "reply_to", reply_to)
        if address2 is not None:
            pulumi.set(__self__, "address2", address2)
        if from_name is not None:
            pulumi.set(__self__, "from_name", from_name)
        if reply_to_name is not None:
            pulumi.set(__self__, "reply_to_name", reply_to_name)
        if state is not None:
            pulumi.set(__self__, "state", state)
        if zip is not None:
            pulumi.set(__self__, "zip", zip)

    @_builtins.property
    @pulumi.getter
    def address(self) -> pulumi.Input[_builtins.str]:
        return pulumi.get(self, "address")

    @address.setter
    def address(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "address", value)

    @_builtins.property
    @pulumi.getter
    def city(self) -> pulumi.Input[_builtins.str]:
        return pulumi.get(self, "city")

    @city.setter
    def city(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "city", value)

    @_builtins.property
    @pulumi.getter
    def country(self) -> pulumi.Input[_builtins.str]:
        return pulumi.get(self, "country")

    @country.setter
    def country(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "country", value)

    @_builtins.property
    @pulumi.getter(name="fromEmail")
    def from_email(self) -> pulumi.Input[_builtins.str]:
        return pulumi.get(self, "from_email")

    @from_email.setter
    def from_email(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "from_email", value)

    @_builtins.property
    @pulumi.getter
    def nickname(self) -> pulumi.Input[_builtins.str]:
        return pulumi.get(self, "nickname")

    @nickname.setter
    def nickname(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "nickname", value)

    @_builtins.property
    @pulumi.getter(name="replyTo")
    def reply_to(self) -> pulumi.Input[_builtins.str]:
        return pulumi.get(self, "reply_to")

    @reply_to.setter
    def reply_to(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "reply_to", value)

    @_builtins.property
    @pulumi.getter
    def address2(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "address2")

    @address2.setter
    def address2(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "address2", value)

    @_builtins.property
    @pulumi.getter(name="fromName")
    def from_name(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "from_name")

    @from_name.setter
    def from_name(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "from_name", value)

    @_builtins.property
    @pulumi.getter(name="replyToName")
    def reply_to_name(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "reply_to_name")

    @reply_to_name.setter
    def reply_to_name(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "reply_to_name", value)

    @_builtins.property
    @pulumi.getter
    def state(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "state")

    @state.setter
    def state(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "state", value)

    @_builtins.property
    @pulumi.getter
    def zip(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "zip")

    @zip.setter
    def zip(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "zip", value)


@pulumi.type_token("sendgrid:index:VerifiedSender")
class VerifiedSender(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 address: Optional[pulumi.Input[_builtins.str]] = None,
                 address2: Optional[pulumi.Input[_builtins.str]] = None,
                 city: Optional[pulumi.Input[_builtins.str]] = None,
                 country: Optional[pulumi.Input[_builtins.str]] = None,
                 from_email: Optional[pulumi.Input[_builtins.str]] = None,
                 from_name: Optional[pulumi.Input[_builtins.str]] = None,
                 nickname: Optional[pulumi.Input[_builtins.str]] = None,
                 reply_to: Optional[pulumi.Input[_builtins.str]] = None,
                 reply_to_name: Optional[pulumi.Input[_builtins.str]] = None,
                 state: Optional[pulumi.Input[_builtins.str]] = None,
                 zip: Optional[pulumi.Input[_builtins.str]] = None,
                 __props__=None):
        """
        Manages a SendGrid Verified Sender.

        Verified Senders are sender identities that have been verified for sending email. After creation, SendGrid will send a verification email to the from_email address. The sender must click the verification link to complete the verification process.

        **Note:** The `verified` status will be `false` until the verification email is confirmed.

        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: VerifiedSenderArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Manages a SendGrid Verified Sender.

        Verified Senders are sender identities that have been verified for sending email. After creation, SendGrid will send a verification email to the from_email address. The sender must click the verification link to complete the verification process.

        **Note:** The `verified` status will be `false` until the verification email is confirmed.

        :param str resource_name: The name of the resource.
        :param VerifiedSenderArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(VerifiedSenderArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 address: Optional[pulumi.Input[_builtins.str]] = None,
                 address2: Optional[pulumi.Input[_builtins.str]] = None,
                 city: Optional[pulumi.Input[_builtins.str]] = None,
                 country: Optional[pulumi.Input[_builtins.str]] = None,
                 from_email: Optional[pulumi.Input[_builtins.str]] = None,
                 from_name: Optional[pulumi.Input[_builtins.str]] = None,
                 nickname: Optional[pulumi.Input[_builtins.str]] = None,
                 reply_to: Optional[pulumi.Input[_builtins.str]] = None,
                 reply_to_name: Optional[pulumi.Input[_builtins.str]] = None,
                 state: Optional[pulumi.Input[_builtins.str]] = None,
                 zip: Optional[pulumi.Input[_builtins.str]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = VerifiedSenderArgs.__new__(VerifiedSenderArgs)

            if address is None and not opts.urn:
                raise TypeError("Missing required property 'address'")
            __props__.__dict__["address"] = address
            __props__.__dict__["address2"] = address2
            if city is None and not opts.urn:
                raise TypeError("Missing required property 'city'")
            __props__.__dict__["city"] = city
            if country is None and not opts.urn:
                raise TypeError("Missing required property 'country'")
            __props__.__dict__["country"] = country
            if from_email is None and not opts.urn:
                raise TypeError("Missing required property 'from_email'")
            __props__.__dict__["from_email"] = from_email
            __props__.__dict__["from_name"] = from_name
            if nickname is None and not opts.urn:
                raise TypeError("Missing required property 'nickname'")
            __props__.__dict__["nickname"] = nickname
            if reply_to is None and not opts.urn:
                raise TypeError("Missing required property 'reply_to'")
            __props__.__dict__["reply_to"] = reply_to
            __props__.__dict__["reply_to_name"] = reply_to_name
            __props__.__dict__["state"] = state
            __props__.__dict__["zip"] = zip
            __props__.__dict__["locked"] = None
            __props__.__dict__["sender_id"] = None
            __props__.__dict__["verified"] = None
        super(VerifiedSender, __self__).__init__(
            'sendgrid:index:VerifiedSender',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None) -> 'VerifiedSender':
        """
        Get an existing VerifiedSender resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = VerifiedSenderArgs.__new__(VerifiedSenderArgs)

        __props__.__dict__["address"] = None
        __props__.__dict__["address2"] = None
        __props__.__dict__["city"] = None
        __props__.__dict__["country"] = None
        __props__.__dict__["from_email"] = None
        __props__.__dict__["from_name"] = None
        __props__.__dict__["locked"] = None
        __props__.__dict__["nickname"] = None
        __props__.__dict__["reply_to"] = None
        __props__.__dict__["reply_to_name"] = None
        __props__.__dict__["sender_id"] = None
        __props__.__dict__["state"] = None
        __props__.__dict__["verified"] = None
        __props__.__dict__["zip"] = None
        return VerifiedSender(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter
    def address(self) -> pulumi.Output[_builtins.str]:
        return pulumi.get(self, "address")

    @_builtins.property
    @pulumi.getter
    def address2(self) -> pulumi.Output[Optional[_builtins.str]]:
        return pulumi.get(self, "address2")

    @_builtins.property
    @pulumi.getter
    def city(self) -> pulumi.Output[_builtins.str]:
        return pulumi.get(self, "city")

    @_builtins.property
    @pulumi.getter
    def country(self) -> pulumi.Output[_builtins.str]:
        return pulumi.get(self, "country")

    @_builtins.property
    @pulumi.getter(name="fromEmail")
    def from_email(self) -> pulumi.Output[_builtins.str]:
        return pulumi.get(self, "from_email")

    @_builtins.property
    @pulumi.getter(name="fromName")
    def from_name(self) -> pulumi.Output[Optional[_builtins.str]]:
        return pulumi.get(self, "from_name")

    @_builtins.property
    @pulumi.getter
    def locked(self) -> pulumi.Output[_builtins.bool]:
        return pulumi.get(self, "locked")

    @_builtins.property
    @pulumi.getter
    def nickname(self) -> pulumi.Output[_builtins.str]:
        return pulumi.get(self, "nickname")

    @_builtins.property
    @pulumi.getter(name="replyTo")
    def reply_to(self) -> pulumi.Output[_builtins.str]:
        return pulumi.get(self, "reply_to")

    @_builtins.property
    @pulumi.getter(name="replyToName")
    def reply_to_name(self) -> pulumi.Output[Optional[_builtins.str]]:
        return pulumi.get(self, "reply_to_name")

    @_builtins.property
    @pulumi.getter(name="senderId")
    def sender_id(self) -> pulumi.Output[_builtins.int]:
        return pulumi.get(self, "sender_id")

    @_builtins.property
    @pulumi.getter
    def state(self) -> pulumi.Output[Optional[_builtins.str]]:
        return pulumi.get(self, "state")

    @_builtins.property
    @pulumi.getter
    def verified(self) -> pulumi.Output[_builtins.bool]:
        return pulumi.get(self, "verified")

    @_builtins.property
    @pulumi.getter
    def zip(self) -> pulumi.Output[Optional[_builtins.str]]:
        return pulumi.get(self, "zip")

