// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Sendgrid
{
    /// <summary>
    /// Manages a SendGrid Domain Authentication.
    /// 
    /// Domain Authentication (formerly Domain Whitelabel) allows you to authenticate your domain so that emails appear to come directly from your domain, removing the 'via sendgrid.net' message that recipients may see.
    /// 
    /// After creating this resource, you must add the DNS records to your domain's DNS settings and then validate the domain using the SendGrid console or API.
    /// </summary>
    [SendgridResourceType("sendgrid:index:DomainAuthentication")]
    public partial class DomainAuthentication : global::Pulumi.CustomResource
    {
        [Output("automaticSecurity")]
        public Output<bool?> AutomaticSecurity { get; private set; } = null!;

        [Output("customDkimSelector")]
        public Output<string?> CustomDkimSelector { get; private set; } = null!;

        [Output("customSpf")]
        public Output<bool?> CustomSpf { get; private set; } = null!;

        [Output("default")]
        public Output<bool?> Default { get; private set; } = null!;

        [Output("dkim1")]
        public Output<Outputs.DNSRecord?> Dkim1 { get; private set; } = null!;

        [Output("dkim2")]
        public Output<Outputs.DNSRecord?> Dkim2 { get; private set; } = null!;

        [Output("domain")]
        public Output<string> Domain { get; private set; } = null!;

        [Output("domainId")]
        public Output<int> DomainId { get; private set; } = null!;

        [Output("ips")]
        public Output<ImmutableArray<string>> Ips { get; private set; } = null!;

        [Output("legacy")]
        public Output<bool> Legacy { get; private set; } = null!;

        [Output("mailCname")]
        public Output<Outputs.DNSRecord?> MailCname { get; private set; } = null!;

        [Output("region")]
        public Output<string?> Region { get; private set; } = null!;

        [Output("subdomain")]
        public Output<string?> Subdomain { get; private set; } = null!;

        [Output("userId")]
        public Output<int> UserId { get; private set; } = null!;

        [Output("username")]
        public Output<string> Username { get; private set; } = null!;

        [Output("valid")]
        public Output<bool> Valid { get; private set; } = null!;


        /// <summary>
        /// Create a DomainAuthentication resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public DomainAuthentication(string name, DomainAuthenticationArgs args, CustomResourceOptions? options = null)
            : base("sendgrid:index:DomainAuthentication", name, args ?? new DomainAuthenticationArgs(), MakeResourceOptions(options, ""))
        {
        }

        private DomainAuthentication(string name, Input<string> id, CustomResourceOptions? options = null)
            : base("sendgrid:index:DomainAuthentication", name, null, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing DomainAuthentication resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static DomainAuthentication Get(string name, Input<string> id, CustomResourceOptions? options = null)
        {
            return new DomainAuthentication(name, id, options);
        }
    }

    public sealed class DomainAuthenticationArgs : global::Pulumi.ResourceArgs
    {
        [Input("automaticSecurity")]
        public Input<bool>? AutomaticSecurity { get; set; }

        [Input("customDkimSelector")]
        public Input<string>? CustomDkimSelector { get; set; }

        [Input("customSpf")]
        public Input<bool>? CustomSpf { get; set; }

        [Input("default")]
        public Input<bool>? Default { get; set; }

        [Input("domain", required: true)]
        public Input<string> Domain { get; set; } = null!;

        [Input("ips")]
        private InputList<string>? _ips;
        public InputList<string> Ips
        {
            get => _ips ?? (_ips = new InputList<string>());
            set => _ips = value;
        }

        [Input("region")]
        public Input<string>? Region { get; set; }

        [Input("subdomain")]
        public Input<string>? Subdomain { get; set; }

        public DomainAuthenticationArgs()
        {
        }
        public static new DomainAuthenticationArgs Empty => new DomainAuthenticationArgs();
    }
}
