// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Sendgrid
{
    /// <summary>
    /// Manages a SendGrid Event Webhook.
    /// 
    /// Event Webhooks allow you to receive HTTP POST notifications when email events occur, such as delivery, opens, clicks, bounces, and more. Configure the URL endpoint and select which events to track.
    /// 
    /// Note: Only one webhook can be configured per URL. Signature verification must be configured separately after webhook creation.
    /// </summary>
    [SendgridResourceType("sendgrid:index:EventWebhook")]
    public partial class EventWebhook : global::Pulumi.CustomResource
    {
        [Output("bounce")]
        public Output<bool?> Bounce { get; private set; } = null!;

        [Output("click")]
        public Output<bool?> Click { get; private set; } = null!;

        [Output("deferred")]
        public Output<bool?> Deferred { get; private set; } = null!;

        [Output("delivered")]
        public Output<bool?> Delivered { get; private set; } = null!;

        [Output("dropped")]
        public Output<bool?> Dropped { get; private set; } = null!;

        [Output("enabled")]
        public Output<bool?> Enabled { get; private set; } = null!;

        [Output("friendlyName")]
        public Output<string?> FriendlyName { get; private set; } = null!;

        [Output("groupResubscribe")]
        public Output<bool?> GroupResubscribe { get; private set; } = null!;

        [Output("groupUnsubscribe")]
        public Output<bool?> GroupUnsubscribe { get; private set; } = null!;

        [Output("open")]
        public Output<bool?> Open { get; private set; } = null!;

        [Output("processed")]
        public Output<bool?> Processed { get; private set; } = null!;

        [Output("spamReport")]
        public Output<bool?> SpamReport { get; private set; } = null!;

        [Output("unsubscribe")]
        public Output<bool?> Unsubscribe { get; private set; } = null!;

        [Output("url")]
        public Output<string> Url { get; private set; } = null!;

        [Output("webhookId")]
        public Output<string> WebhookId { get; private set; } = null!;


        /// <summary>
        /// Create a EventWebhook resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public EventWebhook(string name, EventWebhookArgs args, CustomResourceOptions? options = null)
            : base("sendgrid:index:EventWebhook", name, args ?? new EventWebhookArgs(), MakeResourceOptions(options, ""))
        {
        }

        private EventWebhook(string name, Input<string> id, CustomResourceOptions? options = null)
            : base("sendgrid:index:EventWebhook", name, null, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing EventWebhook resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static EventWebhook Get(string name, Input<string> id, CustomResourceOptions? options = null)
        {
            return new EventWebhook(name, id, options);
        }
    }

    public sealed class EventWebhookArgs : global::Pulumi.ResourceArgs
    {
        [Input("bounce")]
        public Input<bool>? Bounce { get; set; }

        [Input("click")]
        public Input<bool>? Click { get; set; }

        [Input("deferred")]
        public Input<bool>? Deferred { get; set; }

        [Input("delivered")]
        public Input<bool>? Delivered { get; set; }

        [Input("dropped")]
        public Input<bool>? Dropped { get; set; }

        [Input("enabled")]
        public Input<bool>? Enabled { get; set; }

        [Input("friendlyName")]
        public Input<string>? FriendlyName { get; set; }

        [Input("groupResubscribe")]
        public Input<bool>? GroupResubscribe { get; set; }

        [Input("groupUnsubscribe")]
        public Input<bool>? GroupUnsubscribe { get; set; }

        [Input("open")]
        public Input<bool>? Open { get; set; }

        [Input("processed")]
        public Input<bool>? Processed { get; set; }

        [Input("spamReport")]
        public Input<bool>? SpamReport { get; set; }

        [Input("unsubscribe")]
        public Input<bool>? Unsubscribe { get; set; }

        [Input("url", required: true)]
        public Input<string> Url { get; set; } = null!;

        public EventWebhookArgs()
        {
        }
        public static new EventWebhookArgs Empty => new EventWebhookArgs();
    }
}
