// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Sendgrid
{
    /// <summary>
    /// Manages a SendGrid Subuser.
    /// 
    /// Subusers are separate accounts under a parent account that can be used to segment email sending, maintain separate sending reputations, and organize email workflows. Each subuser has their own credentials and can be assigned specific IP addresses.
    /// 
    /// Note: The password is only used during creation and cannot be retrieved. Regional subusers require a SendGrid Pro plan or above.
    /// </summary>
    [SendgridResourceType("sendgrid:index:Subuser")]
    public partial class Subuser : global::Pulumi.CustomResource
    {
        [Output("disabled")]
        public Output<bool> Disabled { get; private set; } = null!;

        [Output("email")]
        public Output<string> Email { get; private set; } = null!;

        [Output("ips")]
        public Output<ImmutableArray<string>> Ips { get; private set; } = null!;

        [Output("region")]
        public Output<string?> Region { get; private set; } = null!;

        [Output("userId")]
        public Output<int> UserId { get; private set; } = null!;

        [Output("username")]
        public Output<string> Username { get; private set; } = null!;


        /// <summary>
        /// Create a Subuser resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public Subuser(string name, SubuserArgs args, CustomResourceOptions? options = null)
            : base("sendgrid:index:Subuser", name, args ?? new SubuserArgs(), MakeResourceOptions(options, ""))
        {
        }

        private Subuser(string name, Input<string> id, CustomResourceOptions? options = null)
            : base("sendgrid:index:Subuser", name, null, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing Subuser resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static Subuser Get(string name, Input<string> id, CustomResourceOptions? options = null)
        {
            return new Subuser(name, id, options);
        }
    }

    public sealed class SubuserArgs : global::Pulumi.ResourceArgs
    {
        [Input("disabled")]
        public Input<bool>? Disabled { get; set; }

        [Input("email", required: true)]
        public Input<string> Email { get; set; } = null!;

        [Input("ips")]
        private InputList<string>? _ips;
        public InputList<string> Ips
        {
            get => _ips ?? (_ips = new InputList<string>());
            set => _ips = value;
        }

        [Input("password", required: true)]
        private Input<string>? _password;
        public Input<string>? Password
        {
            get => _password;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _password = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        [Input("region")]
        public Input<string>? Region { get; set; }

        [Input("username", required: true)]
        public Input<string> Username { get; set; } = null!;

        public SubuserArgs()
        {
        }
        public static new SubuserArgs Empty => new SubuserArgs();
    }
}
