// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Sendgrid
{
    /// <summary>
    /// Manages a SendGrid Teammate.
    /// 
    /// Teammates are users who have access to your SendGrid account with configurable permissions. You can invite teammates via email and set their initial permissions using scopes.
    /// 
    /// Note: Teammate invitations expire after 7 days. The invitation can be resent to reset the expiration. Free and Essentials plans allow only one teammate per account.
    /// </summary>
    [SendgridResourceType("sendgrid:index:Teammate")]
    public partial class Teammate : global::Pulumi.CustomResource
    {
        [Output("email")]
        public Output<string> Email { get; private set; } = null!;

        [Output("firstName")]
        public Output<string?> FirstName { get; private set; } = null!;

        [Output("isAdmin")]
        public Output<bool> IsAdmin { get; private set; } = null!;

        [Output("lastName")]
        public Output<string?> LastName { get; private set; } = null!;

        [Output("scopes")]
        public Output<ImmutableArray<string>> Scopes { get; private set; } = null!;

        [Output("token")]
        public Output<string?> Token { get; private set; } = null!;

        [Output("userType")]
        public Output<string?> UserType { get; private set; } = null!;

        [Output("username")]
        public Output<string?> Username { get; private set; } = null!;


        /// <summary>
        /// Create a Teammate resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public Teammate(string name, TeammateArgs args, CustomResourceOptions? options = null)
            : base("sendgrid:index:Teammate", name, args ?? new TeammateArgs(), MakeResourceOptions(options, ""))
        {
        }

        private Teammate(string name, Input<string> id, CustomResourceOptions? options = null)
            : base("sendgrid:index:Teammate", name, null, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing Teammate resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static Teammate Get(string name, Input<string> id, CustomResourceOptions? options = null)
        {
            return new Teammate(name, id, options);
        }
    }

    public sealed class TeammateArgs : global::Pulumi.ResourceArgs
    {
        [Input("email", required: true)]
        public Input<string> Email { get; set; } = null!;

        [Input("isAdmin")]
        public Input<bool>? IsAdmin { get; set; }

        [Input("scopes")]
        private InputList<string>? _scopes;
        public InputList<string> Scopes
        {
            get => _scopes ?? (_scopes = new InputList<string>());
            set => _scopes = value;
        }

        public TeammateArgs()
        {
        }
        public static new TeammateArgs Empty => new TeammateArgs();
    }
}
