// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Sendgrid
{
    /// <summary>
    /// Manages a SendGrid Transactional Template.
    /// 
    /// Transactional templates are used to create reusable email templates for transactional emails like receipts, password resets, etc.
    /// 
    /// Templates can be either 'legacy' (plain text/HTML) or 'dynamic' (supporting handlebars syntax for personalization).
    /// 
    /// **Note:** Template versions are managed separately via the TemplateVersion resource.
    /// </summary>
    [SendgridResourceType("sendgrid:index:Template")]
    public partial class Template : global::Pulumi.CustomResource
    {
        [Output("generation")]
        public Output<string> Generation { get; private set; } = null!;

        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        [Output("templateId")]
        public Output<string> TemplateId { get; private set; } = null!;

        [Output("updatedAt")]
        public Output<string?> UpdatedAt { get; private set; } = null!;

        [Output("versions")]
        public Output<ImmutableArray<Outputs.TemplateVersionSummary>> Versions { get; private set; } = null!;


        /// <summary>
        /// Create a Template resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public Template(string name, TemplateArgs args, CustomResourceOptions? options = null)
            : base("sendgrid:index:Template", name, args ?? new TemplateArgs(), MakeResourceOptions(options, ""))
        {
        }

        private Template(string name, Input<string> id, CustomResourceOptions? options = null)
            : base("sendgrid:index:Template", name, null, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing Template resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static Template Get(string name, Input<string> id, CustomResourceOptions? options = null)
        {
            return new Template(name, id, options);
        }
    }

    public sealed class TemplateArgs : global::Pulumi.ResourceArgs
    {
        [Input("generation", required: true)]
        public Input<string> Generation { get; set; } = null!;

        [Input("name", required: true)]
        public Input<string> Name { get; set; } = null!;

        public TemplateArgs()
        {
        }
        public static new TemplateArgs Empty => new TemplateArgs();
    }
}
