// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package sendgrid

import (
	"context"
	"reflect"

	"errors"
	"github.com/JDetmar/pulumi-sendgrid/sdk/go/sendgrid/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Manages a SendGrid API Key.
//
// API keys are used to authenticate access to SendGrid services. You can create keys with specific scopes to limit their permissions.
//
// **Note:** The actual API key value is only returned on creation and cannot be retrieved again. Make sure to store it securely.
type APIKey struct {
	pulumi.CustomResourceState

	ApiKey   pulumi.StringPtrOutput   `pulumi:"apiKey"`
	ApiKeyId pulumi.StringOutput      `pulumi:"apiKeyId"`
	Name     pulumi.StringOutput      `pulumi:"name"`
	Scopes   pulumi.StringArrayOutput `pulumi:"scopes"`
}

// NewAPIKey registers a new resource with the given unique name, arguments, and options.
func NewAPIKey(ctx *pulumi.Context,
	name string, args *APIKeyArgs, opts ...pulumi.ResourceOption) (*APIKey, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Name == nil {
		return nil, errors.New("invalid value for required argument 'Name'")
	}
	secrets := pulumi.AdditionalSecretOutputs([]string{
		"apiKey",
	})
	opts = append(opts, secrets)
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource APIKey
	err := ctx.RegisterResource("sendgrid:index:APIKey", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetAPIKey gets an existing APIKey resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetAPIKey(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *APIKeyState, opts ...pulumi.ResourceOption) (*APIKey, error) {
	var resource APIKey
	err := ctx.ReadResource("sendgrid:index:APIKey", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering APIKey resources.
type apikeyState struct {
}

type APIKeyState struct {
}

func (APIKeyState) ElementType() reflect.Type {
	return reflect.TypeOf((*apikeyState)(nil)).Elem()
}

type apikeyArgs struct {
	Name   string   `pulumi:"name"`
	Scopes []string `pulumi:"scopes"`
}

// The set of arguments for constructing a APIKey resource.
type APIKeyArgs struct {
	Name   pulumi.StringInput
	Scopes pulumi.StringArrayInput
}

func (APIKeyArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*apikeyArgs)(nil)).Elem()
}

type APIKeyInput interface {
	pulumi.Input

	ToAPIKeyOutput() APIKeyOutput
	ToAPIKeyOutputWithContext(ctx context.Context) APIKeyOutput
}

func (*APIKey) ElementType() reflect.Type {
	return reflect.TypeOf((**APIKey)(nil)).Elem()
}

func (i *APIKey) ToAPIKeyOutput() APIKeyOutput {
	return i.ToAPIKeyOutputWithContext(context.Background())
}

func (i *APIKey) ToAPIKeyOutputWithContext(ctx context.Context) APIKeyOutput {
	return pulumi.ToOutputWithContext(ctx, i).(APIKeyOutput)
}

// APIKeyArrayInput is an input type that accepts APIKeyArray and APIKeyArrayOutput values.
// You can construct a concrete instance of `APIKeyArrayInput` via:
//
//	APIKeyArray{ APIKeyArgs{...} }
type APIKeyArrayInput interface {
	pulumi.Input

	ToAPIKeyArrayOutput() APIKeyArrayOutput
	ToAPIKeyArrayOutputWithContext(context.Context) APIKeyArrayOutput
}

type APIKeyArray []APIKeyInput

func (APIKeyArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*APIKey)(nil)).Elem()
}

func (i APIKeyArray) ToAPIKeyArrayOutput() APIKeyArrayOutput {
	return i.ToAPIKeyArrayOutputWithContext(context.Background())
}

func (i APIKeyArray) ToAPIKeyArrayOutputWithContext(ctx context.Context) APIKeyArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(APIKeyArrayOutput)
}

// APIKeyMapInput is an input type that accepts APIKeyMap and APIKeyMapOutput values.
// You can construct a concrete instance of `APIKeyMapInput` via:
//
//	APIKeyMap{ "key": APIKeyArgs{...} }
type APIKeyMapInput interface {
	pulumi.Input

	ToAPIKeyMapOutput() APIKeyMapOutput
	ToAPIKeyMapOutputWithContext(context.Context) APIKeyMapOutput
}

type APIKeyMap map[string]APIKeyInput

func (APIKeyMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*APIKey)(nil)).Elem()
}

func (i APIKeyMap) ToAPIKeyMapOutput() APIKeyMapOutput {
	return i.ToAPIKeyMapOutputWithContext(context.Background())
}

func (i APIKeyMap) ToAPIKeyMapOutputWithContext(ctx context.Context) APIKeyMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(APIKeyMapOutput)
}

type APIKeyOutput struct{ *pulumi.OutputState }

func (APIKeyOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**APIKey)(nil)).Elem()
}

func (o APIKeyOutput) ToAPIKeyOutput() APIKeyOutput {
	return o
}

func (o APIKeyOutput) ToAPIKeyOutputWithContext(ctx context.Context) APIKeyOutput {
	return o
}

func (o APIKeyOutput) ApiKey() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *APIKey) pulumi.StringPtrOutput { return v.ApiKey }).(pulumi.StringPtrOutput)
}

func (o APIKeyOutput) ApiKeyId() pulumi.StringOutput {
	return o.ApplyT(func(v *APIKey) pulumi.StringOutput { return v.ApiKeyId }).(pulumi.StringOutput)
}

func (o APIKeyOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *APIKey) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

func (o APIKeyOutput) Scopes() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *APIKey) pulumi.StringArrayOutput { return v.Scopes }).(pulumi.StringArrayOutput)
}

type APIKeyArrayOutput struct{ *pulumi.OutputState }

func (APIKeyArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*APIKey)(nil)).Elem()
}

func (o APIKeyArrayOutput) ToAPIKeyArrayOutput() APIKeyArrayOutput {
	return o
}

func (o APIKeyArrayOutput) ToAPIKeyArrayOutputWithContext(ctx context.Context) APIKeyArrayOutput {
	return o
}

func (o APIKeyArrayOutput) Index(i pulumi.IntInput) APIKeyOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *APIKey {
		return vs[0].([]*APIKey)[vs[1].(int)]
	}).(APIKeyOutput)
}

type APIKeyMapOutput struct{ *pulumi.OutputState }

func (APIKeyMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*APIKey)(nil)).Elem()
}

func (o APIKeyMapOutput) ToAPIKeyMapOutput() APIKeyMapOutput {
	return o
}

func (o APIKeyMapOutput) ToAPIKeyMapOutputWithContext(ctx context.Context) APIKeyMapOutput {
	return o
}

func (o APIKeyMapOutput) MapIndex(k pulumi.StringInput) APIKeyOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *APIKey {
		return vs[0].(map[string]*APIKey)[vs[1].(string)]
	}).(APIKeyOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*APIKeyInput)(nil)).Elem(), &APIKey{})
	pulumi.RegisterInputType(reflect.TypeOf((*APIKeyArrayInput)(nil)).Elem(), APIKeyArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*APIKeyMapInput)(nil)).Elem(), APIKeyMap{})
	pulumi.RegisterOutputType(APIKeyOutput{})
	pulumi.RegisterOutputType(APIKeyArrayOutput{})
	pulumi.RegisterOutputType(APIKeyMapOutput{})
}
