// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package sendgrid

import (
	"context"
	"reflect"

	"errors"
	"github.com/JDetmar/pulumi-sendgrid/sdk/go/sendgrid/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Manages a SendGrid Event Webhook.
//
// Event Webhooks allow you to receive HTTP POST notifications when email events occur, such as delivery, opens, clicks, bounces, and more. Configure the URL endpoint and select which events to track.
//
// Note: Only one webhook can be configured per URL. Signature verification must be configured separately after webhook creation.
type EventWebhook struct {
	pulumi.CustomResourceState

	Bounce           pulumi.BoolPtrOutput   `pulumi:"bounce"`
	Click            pulumi.BoolPtrOutput   `pulumi:"click"`
	Deferred         pulumi.BoolPtrOutput   `pulumi:"deferred"`
	Delivered        pulumi.BoolPtrOutput   `pulumi:"delivered"`
	Dropped          pulumi.BoolPtrOutput   `pulumi:"dropped"`
	Enabled          pulumi.BoolPtrOutput   `pulumi:"enabled"`
	FriendlyName     pulumi.StringPtrOutput `pulumi:"friendlyName"`
	GroupResubscribe pulumi.BoolPtrOutput   `pulumi:"groupResubscribe"`
	GroupUnsubscribe pulumi.BoolPtrOutput   `pulumi:"groupUnsubscribe"`
	Open             pulumi.BoolPtrOutput   `pulumi:"open"`
	Processed        pulumi.BoolPtrOutput   `pulumi:"processed"`
	SpamReport       pulumi.BoolPtrOutput   `pulumi:"spamReport"`
	Unsubscribe      pulumi.BoolPtrOutput   `pulumi:"unsubscribe"`
	Url              pulumi.StringOutput    `pulumi:"url"`
	WebhookId        pulumi.StringOutput    `pulumi:"webhookId"`
}

// NewEventWebhook registers a new resource with the given unique name, arguments, and options.
func NewEventWebhook(ctx *pulumi.Context,
	name string, args *EventWebhookArgs, opts ...pulumi.ResourceOption) (*EventWebhook, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Url == nil {
		return nil, errors.New("invalid value for required argument 'Url'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource EventWebhook
	err := ctx.RegisterResource("sendgrid:index:EventWebhook", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetEventWebhook gets an existing EventWebhook resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetEventWebhook(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *EventWebhookState, opts ...pulumi.ResourceOption) (*EventWebhook, error) {
	var resource EventWebhook
	err := ctx.ReadResource("sendgrid:index:EventWebhook", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering EventWebhook resources.
type eventWebhookState struct {
}

type EventWebhookState struct {
}

func (EventWebhookState) ElementType() reflect.Type {
	return reflect.TypeOf((*eventWebhookState)(nil)).Elem()
}

type eventWebhookArgs struct {
	Bounce           *bool   `pulumi:"bounce"`
	Click            *bool   `pulumi:"click"`
	Deferred         *bool   `pulumi:"deferred"`
	Delivered        *bool   `pulumi:"delivered"`
	Dropped          *bool   `pulumi:"dropped"`
	Enabled          *bool   `pulumi:"enabled"`
	FriendlyName     *string `pulumi:"friendlyName"`
	GroupResubscribe *bool   `pulumi:"groupResubscribe"`
	GroupUnsubscribe *bool   `pulumi:"groupUnsubscribe"`
	Open             *bool   `pulumi:"open"`
	Processed        *bool   `pulumi:"processed"`
	SpamReport       *bool   `pulumi:"spamReport"`
	Unsubscribe      *bool   `pulumi:"unsubscribe"`
	Url              string  `pulumi:"url"`
}

// The set of arguments for constructing a EventWebhook resource.
type EventWebhookArgs struct {
	Bounce           pulumi.BoolPtrInput
	Click            pulumi.BoolPtrInput
	Deferred         pulumi.BoolPtrInput
	Delivered        pulumi.BoolPtrInput
	Dropped          pulumi.BoolPtrInput
	Enabled          pulumi.BoolPtrInput
	FriendlyName     pulumi.StringPtrInput
	GroupResubscribe pulumi.BoolPtrInput
	GroupUnsubscribe pulumi.BoolPtrInput
	Open             pulumi.BoolPtrInput
	Processed        pulumi.BoolPtrInput
	SpamReport       pulumi.BoolPtrInput
	Unsubscribe      pulumi.BoolPtrInput
	Url              pulumi.StringInput
}

func (EventWebhookArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*eventWebhookArgs)(nil)).Elem()
}

type EventWebhookInput interface {
	pulumi.Input

	ToEventWebhookOutput() EventWebhookOutput
	ToEventWebhookOutputWithContext(ctx context.Context) EventWebhookOutput
}

func (*EventWebhook) ElementType() reflect.Type {
	return reflect.TypeOf((**EventWebhook)(nil)).Elem()
}

func (i *EventWebhook) ToEventWebhookOutput() EventWebhookOutput {
	return i.ToEventWebhookOutputWithContext(context.Background())
}

func (i *EventWebhook) ToEventWebhookOutputWithContext(ctx context.Context) EventWebhookOutput {
	return pulumi.ToOutputWithContext(ctx, i).(EventWebhookOutput)
}

type EventWebhookOutput struct{ *pulumi.OutputState }

func (EventWebhookOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**EventWebhook)(nil)).Elem()
}

func (o EventWebhookOutput) ToEventWebhookOutput() EventWebhookOutput {
	return o
}

func (o EventWebhookOutput) ToEventWebhookOutputWithContext(ctx context.Context) EventWebhookOutput {
	return o
}

func (o EventWebhookOutput) Bounce() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *EventWebhook) pulumi.BoolPtrOutput { return v.Bounce }).(pulumi.BoolPtrOutput)
}

func (o EventWebhookOutput) Click() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *EventWebhook) pulumi.BoolPtrOutput { return v.Click }).(pulumi.BoolPtrOutput)
}

func (o EventWebhookOutput) Deferred() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *EventWebhook) pulumi.BoolPtrOutput { return v.Deferred }).(pulumi.BoolPtrOutput)
}

func (o EventWebhookOutput) Delivered() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *EventWebhook) pulumi.BoolPtrOutput { return v.Delivered }).(pulumi.BoolPtrOutput)
}

func (o EventWebhookOutput) Dropped() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *EventWebhook) pulumi.BoolPtrOutput { return v.Dropped }).(pulumi.BoolPtrOutput)
}

func (o EventWebhookOutput) Enabled() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *EventWebhook) pulumi.BoolPtrOutput { return v.Enabled }).(pulumi.BoolPtrOutput)
}

func (o EventWebhookOutput) FriendlyName() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *EventWebhook) pulumi.StringPtrOutput { return v.FriendlyName }).(pulumi.StringPtrOutput)
}

func (o EventWebhookOutput) GroupResubscribe() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *EventWebhook) pulumi.BoolPtrOutput { return v.GroupResubscribe }).(pulumi.BoolPtrOutput)
}

func (o EventWebhookOutput) GroupUnsubscribe() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *EventWebhook) pulumi.BoolPtrOutput { return v.GroupUnsubscribe }).(pulumi.BoolPtrOutput)
}

func (o EventWebhookOutput) Open() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *EventWebhook) pulumi.BoolPtrOutput { return v.Open }).(pulumi.BoolPtrOutput)
}

func (o EventWebhookOutput) Processed() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *EventWebhook) pulumi.BoolPtrOutput { return v.Processed }).(pulumi.BoolPtrOutput)
}

func (o EventWebhookOutput) SpamReport() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *EventWebhook) pulumi.BoolPtrOutput { return v.SpamReport }).(pulumi.BoolPtrOutput)
}

func (o EventWebhookOutput) Unsubscribe() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *EventWebhook) pulumi.BoolPtrOutput { return v.Unsubscribe }).(pulumi.BoolPtrOutput)
}

func (o EventWebhookOutput) Url() pulumi.StringOutput {
	return o.ApplyT(func(v *EventWebhook) pulumi.StringOutput { return v.Url }).(pulumi.StringOutput)
}

func (o EventWebhookOutput) WebhookId() pulumi.StringOutput {
	return o.ApplyT(func(v *EventWebhook) pulumi.StringOutput { return v.WebhookId }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*EventWebhookInput)(nil)).Elem(), &EventWebhook{})
	pulumi.RegisterOutputType(EventWebhookOutput{})
}
