// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package sendgrid

import (
	"context"
	"reflect"

	"errors"
	"github.com/JDetmar/pulumi-sendgrid/sdk/go/sendgrid/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Manages a SendGrid Global Suppression.
//
// Global suppressions are email addresses that have been unsubscribed from all types of emails. When an email address is globally suppressed, no emails will be sent to that address regardless of the unsubscribe group.
//
// This is useful for managing email addresses that have permanently opted out of all communications, or for test addresses that should never receive emails.
type GlobalSuppression struct {
	pulumi.CustomResourceState

	CreatedAt pulumi.IntPtrOutput `pulumi:"createdAt"`
	Email     pulumi.StringOutput `pulumi:"email"`
}

// NewGlobalSuppression registers a new resource with the given unique name, arguments, and options.
func NewGlobalSuppression(ctx *pulumi.Context,
	name string, args *GlobalSuppressionArgs, opts ...pulumi.ResourceOption) (*GlobalSuppression, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Email == nil {
		return nil, errors.New("invalid value for required argument 'Email'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource GlobalSuppression
	err := ctx.RegisterResource("sendgrid:index:GlobalSuppression", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetGlobalSuppression gets an existing GlobalSuppression resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetGlobalSuppression(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *GlobalSuppressionState, opts ...pulumi.ResourceOption) (*GlobalSuppression, error) {
	var resource GlobalSuppression
	err := ctx.ReadResource("sendgrid:index:GlobalSuppression", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering GlobalSuppression resources.
type globalSuppressionState struct {
}

type GlobalSuppressionState struct {
}

func (GlobalSuppressionState) ElementType() reflect.Type {
	return reflect.TypeOf((*globalSuppressionState)(nil)).Elem()
}

type globalSuppressionArgs struct {
	Email string `pulumi:"email"`
}

// The set of arguments for constructing a GlobalSuppression resource.
type GlobalSuppressionArgs struct {
	Email pulumi.StringInput
}

func (GlobalSuppressionArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*globalSuppressionArgs)(nil)).Elem()
}

type GlobalSuppressionInput interface {
	pulumi.Input

	ToGlobalSuppressionOutput() GlobalSuppressionOutput
	ToGlobalSuppressionOutputWithContext(ctx context.Context) GlobalSuppressionOutput
}

func (*GlobalSuppression) ElementType() reflect.Type {
	return reflect.TypeOf((**GlobalSuppression)(nil)).Elem()
}

func (i *GlobalSuppression) ToGlobalSuppressionOutput() GlobalSuppressionOutput {
	return i.ToGlobalSuppressionOutputWithContext(context.Background())
}

func (i *GlobalSuppression) ToGlobalSuppressionOutputWithContext(ctx context.Context) GlobalSuppressionOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GlobalSuppressionOutput)
}

// GlobalSuppressionArrayInput is an input type that accepts GlobalSuppressionArray and GlobalSuppressionArrayOutput values.
// You can construct a concrete instance of `GlobalSuppressionArrayInput` via:
//
//	GlobalSuppressionArray{ GlobalSuppressionArgs{...} }
type GlobalSuppressionArrayInput interface {
	pulumi.Input

	ToGlobalSuppressionArrayOutput() GlobalSuppressionArrayOutput
	ToGlobalSuppressionArrayOutputWithContext(context.Context) GlobalSuppressionArrayOutput
}

type GlobalSuppressionArray []GlobalSuppressionInput

func (GlobalSuppressionArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*GlobalSuppression)(nil)).Elem()
}

func (i GlobalSuppressionArray) ToGlobalSuppressionArrayOutput() GlobalSuppressionArrayOutput {
	return i.ToGlobalSuppressionArrayOutputWithContext(context.Background())
}

func (i GlobalSuppressionArray) ToGlobalSuppressionArrayOutputWithContext(ctx context.Context) GlobalSuppressionArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GlobalSuppressionArrayOutput)
}

// GlobalSuppressionMapInput is an input type that accepts GlobalSuppressionMap and GlobalSuppressionMapOutput values.
// You can construct a concrete instance of `GlobalSuppressionMapInput` via:
//
//	GlobalSuppressionMap{ "key": GlobalSuppressionArgs{...} }
type GlobalSuppressionMapInput interface {
	pulumi.Input

	ToGlobalSuppressionMapOutput() GlobalSuppressionMapOutput
	ToGlobalSuppressionMapOutputWithContext(context.Context) GlobalSuppressionMapOutput
}

type GlobalSuppressionMap map[string]GlobalSuppressionInput

func (GlobalSuppressionMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*GlobalSuppression)(nil)).Elem()
}

func (i GlobalSuppressionMap) ToGlobalSuppressionMapOutput() GlobalSuppressionMapOutput {
	return i.ToGlobalSuppressionMapOutputWithContext(context.Background())
}

func (i GlobalSuppressionMap) ToGlobalSuppressionMapOutputWithContext(ctx context.Context) GlobalSuppressionMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GlobalSuppressionMapOutput)
}

type GlobalSuppressionOutput struct{ *pulumi.OutputState }

func (GlobalSuppressionOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**GlobalSuppression)(nil)).Elem()
}

func (o GlobalSuppressionOutput) ToGlobalSuppressionOutput() GlobalSuppressionOutput {
	return o
}

func (o GlobalSuppressionOutput) ToGlobalSuppressionOutputWithContext(ctx context.Context) GlobalSuppressionOutput {
	return o
}

func (o GlobalSuppressionOutput) CreatedAt() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *GlobalSuppression) pulumi.IntPtrOutput { return v.CreatedAt }).(pulumi.IntPtrOutput)
}

func (o GlobalSuppressionOutput) Email() pulumi.StringOutput {
	return o.ApplyT(func(v *GlobalSuppression) pulumi.StringOutput { return v.Email }).(pulumi.StringOutput)
}

type GlobalSuppressionArrayOutput struct{ *pulumi.OutputState }

func (GlobalSuppressionArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*GlobalSuppression)(nil)).Elem()
}

func (o GlobalSuppressionArrayOutput) ToGlobalSuppressionArrayOutput() GlobalSuppressionArrayOutput {
	return o
}

func (o GlobalSuppressionArrayOutput) ToGlobalSuppressionArrayOutputWithContext(ctx context.Context) GlobalSuppressionArrayOutput {
	return o
}

func (o GlobalSuppressionArrayOutput) Index(i pulumi.IntInput) GlobalSuppressionOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *GlobalSuppression {
		return vs[0].([]*GlobalSuppression)[vs[1].(int)]
	}).(GlobalSuppressionOutput)
}

type GlobalSuppressionMapOutput struct{ *pulumi.OutputState }

func (GlobalSuppressionMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*GlobalSuppression)(nil)).Elem()
}

func (o GlobalSuppressionMapOutput) ToGlobalSuppressionMapOutput() GlobalSuppressionMapOutput {
	return o
}

func (o GlobalSuppressionMapOutput) ToGlobalSuppressionMapOutputWithContext(ctx context.Context) GlobalSuppressionMapOutput {
	return o
}

func (o GlobalSuppressionMapOutput) MapIndex(k pulumi.StringInput) GlobalSuppressionOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *GlobalSuppression {
		return vs[0].(map[string]*GlobalSuppression)[vs[1].(string)]
	}).(GlobalSuppressionOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*GlobalSuppressionInput)(nil)).Elem(), &GlobalSuppression{})
	pulumi.RegisterInputType(reflect.TypeOf((*GlobalSuppressionArrayInput)(nil)).Elem(), GlobalSuppressionArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*GlobalSuppressionMapInput)(nil)).Elem(), GlobalSuppressionMap{})
	pulumi.RegisterOutputType(GlobalSuppressionOutput{})
	pulumi.RegisterOutputType(GlobalSuppressionArrayOutput{})
	pulumi.RegisterOutputType(GlobalSuppressionMapOutput{})
}
