// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package sendgrid

import (
	"context"
	"reflect"

	"errors"
	"github.com/JDetmar/pulumi-sendgrid/sdk/go/sendgrid/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Manages a SendGrid Global Suppression.
//
// Global suppressions are email addresses that have been unsubscribed from all types of emails. When an email address is globally suppressed, no emails will be sent to that address regardless of the unsubscribe group.
//
// This is useful for managing email addresses that have permanently opted out of all communications, or for test addresses that should never receive emails.
type GlobalSuppression struct {
	pulumi.CustomResourceState

	CreatedAt pulumi.IntPtrOutput `pulumi:"createdAt"`
	Email     pulumi.StringOutput `pulumi:"email"`
}

// NewGlobalSuppression registers a new resource with the given unique name, arguments, and options.
func NewGlobalSuppression(ctx *pulumi.Context,
	name string, args *GlobalSuppressionArgs, opts ...pulumi.ResourceOption) (*GlobalSuppression, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Email == nil {
		return nil, errors.New("invalid value for required argument 'Email'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource GlobalSuppression
	err := ctx.RegisterResource("sendgrid:index:GlobalSuppression", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetGlobalSuppression gets an existing GlobalSuppression resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetGlobalSuppression(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *GlobalSuppressionState, opts ...pulumi.ResourceOption) (*GlobalSuppression, error) {
	var resource GlobalSuppression
	err := ctx.ReadResource("sendgrid:index:GlobalSuppression", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering GlobalSuppression resources.
type globalSuppressionState struct {
}

type GlobalSuppressionState struct {
}

func (GlobalSuppressionState) ElementType() reflect.Type {
	return reflect.TypeOf((*globalSuppressionState)(nil)).Elem()
}

type globalSuppressionArgs struct {
	Email string `pulumi:"email"`
}

// The set of arguments for constructing a GlobalSuppression resource.
type GlobalSuppressionArgs struct {
	Email pulumi.StringInput
}

func (GlobalSuppressionArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*globalSuppressionArgs)(nil)).Elem()
}

type GlobalSuppressionInput interface {
	pulumi.Input

	ToGlobalSuppressionOutput() GlobalSuppressionOutput
	ToGlobalSuppressionOutputWithContext(ctx context.Context) GlobalSuppressionOutput
}

func (*GlobalSuppression) ElementType() reflect.Type {
	return reflect.TypeOf((**GlobalSuppression)(nil)).Elem()
}

func (i *GlobalSuppression) ToGlobalSuppressionOutput() GlobalSuppressionOutput {
	return i.ToGlobalSuppressionOutputWithContext(context.Background())
}

func (i *GlobalSuppression) ToGlobalSuppressionOutputWithContext(ctx context.Context) GlobalSuppressionOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GlobalSuppressionOutput)
}

type GlobalSuppressionOutput struct{ *pulumi.OutputState }

func (GlobalSuppressionOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**GlobalSuppression)(nil)).Elem()
}

func (o GlobalSuppressionOutput) ToGlobalSuppressionOutput() GlobalSuppressionOutput {
	return o
}

func (o GlobalSuppressionOutput) ToGlobalSuppressionOutputWithContext(ctx context.Context) GlobalSuppressionOutput {
	return o
}

func (o GlobalSuppressionOutput) CreatedAt() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *GlobalSuppression) pulumi.IntPtrOutput { return v.CreatedAt }).(pulumi.IntPtrOutput)
}

func (o GlobalSuppressionOutput) Email() pulumi.StringOutput {
	return o.ApplyT(func(v *GlobalSuppression) pulumi.StringOutput { return v.Email }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*GlobalSuppressionInput)(nil)).Elem(), &GlobalSuppression{})
	pulumi.RegisterOutputType(GlobalSuppressionOutput{})
}
