// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package sendgrid

import (
	"context"
	"reflect"

	"errors"
	"github.com/JDetmar/pulumi-sendgrid/sdk/go/sendgrid/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Manages a SendGrid IP Pool.
//
// IP Pools allow you to group your dedicated SendGrid IP addresses together. For example, you might have separate pools for transactional and marketing emails, so that each pool maintains its own reputation.
//
// Note: Each account can create up to 100 IP pools. IP pools can only be used with IP addresses that have reverse DNS configured.
type IPPool struct {
	pulumi.CustomResourceState

	Ips      pulumi.StringArrayOutput `pulumi:"ips"`
	Name     pulumi.StringOutput      `pulumi:"name"`
	PoolName pulumi.StringOutput      `pulumi:"poolName"`
}

// NewIPPool registers a new resource with the given unique name, arguments, and options.
func NewIPPool(ctx *pulumi.Context,
	name string, args *IPPoolArgs, opts ...pulumi.ResourceOption) (*IPPool, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Name == nil {
		return nil, errors.New("invalid value for required argument 'Name'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource IPPool
	err := ctx.RegisterResource("sendgrid:index:IPPool", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetIPPool gets an existing IPPool resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetIPPool(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *IPPoolState, opts ...pulumi.ResourceOption) (*IPPool, error) {
	var resource IPPool
	err := ctx.ReadResource("sendgrid:index:IPPool", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering IPPool resources.
type ippoolState struct {
}

type IPPoolState struct {
}

func (IPPoolState) ElementType() reflect.Type {
	return reflect.TypeOf((*ippoolState)(nil)).Elem()
}

type ippoolArgs struct {
	Name string `pulumi:"name"`
}

// The set of arguments for constructing a IPPool resource.
type IPPoolArgs struct {
	Name pulumi.StringInput
}

func (IPPoolArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*ippoolArgs)(nil)).Elem()
}

type IPPoolInput interface {
	pulumi.Input

	ToIPPoolOutput() IPPoolOutput
	ToIPPoolOutputWithContext(ctx context.Context) IPPoolOutput
}

func (*IPPool) ElementType() reflect.Type {
	return reflect.TypeOf((**IPPool)(nil)).Elem()
}

func (i *IPPool) ToIPPoolOutput() IPPoolOutput {
	return i.ToIPPoolOutputWithContext(context.Background())
}

func (i *IPPool) ToIPPoolOutputWithContext(ctx context.Context) IPPoolOutput {
	return pulumi.ToOutputWithContext(ctx, i).(IPPoolOutput)
}

// IPPoolArrayInput is an input type that accepts IPPoolArray and IPPoolArrayOutput values.
// You can construct a concrete instance of `IPPoolArrayInput` via:
//
//	IPPoolArray{ IPPoolArgs{...} }
type IPPoolArrayInput interface {
	pulumi.Input

	ToIPPoolArrayOutput() IPPoolArrayOutput
	ToIPPoolArrayOutputWithContext(context.Context) IPPoolArrayOutput
}

type IPPoolArray []IPPoolInput

func (IPPoolArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*IPPool)(nil)).Elem()
}

func (i IPPoolArray) ToIPPoolArrayOutput() IPPoolArrayOutput {
	return i.ToIPPoolArrayOutputWithContext(context.Background())
}

func (i IPPoolArray) ToIPPoolArrayOutputWithContext(ctx context.Context) IPPoolArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(IPPoolArrayOutput)
}

// IPPoolMapInput is an input type that accepts IPPoolMap and IPPoolMapOutput values.
// You can construct a concrete instance of `IPPoolMapInput` via:
//
//	IPPoolMap{ "key": IPPoolArgs{...} }
type IPPoolMapInput interface {
	pulumi.Input

	ToIPPoolMapOutput() IPPoolMapOutput
	ToIPPoolMapOutputWithContext(context.Context) IPPoolMapOutput
}

type IPPoolMap map[string]IPPoolInput

func (IPPoolMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*IPPool)(nil)).Elem()
}

func (i IPPoolMap) ToIPPoolMapOutput() IPPoolMapOutput {
	return i.ToIPPoolMapOutputWithContext(context.Background())
}

func (i IPPoolMap) ToIPPoolMapOutputWithContext(ctx context.Context) IPPoolMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(IPPoolMapOutput)
}

type IPPoolOutput struct{ *pulumi.OutputState }

func (IPPoolOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**IPPool)(nil)).Elem()
}

func (o IPPoolOutput) ToIPPoolOutput() IPPoolOutput {
	return o
}

func (o IPPoolOutput) ToIPPoolOutputWithContext(ctx context.Context) IPPoolOutput {
	return o
}

func (o IPPoolOutput) Ips() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *IPPool) pulumi.StringArrayOutput { return v.Ips }).(pulumi.StringArrayOutput)
}

func (o IPPoolOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *IPPool) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

func (o IPPoolOutput) PoolName() pulumi.StringOutput {
	return o.ApplyT(func(v *IPPool) pulumi.StringOutput { return v.PoolName }).(pulumi.StringOutput)
}

type IPPoolArrayOutput struct{ *pulumi.OutputState }

func (IPPoolArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*IPPool)(nil)).Elem()
}

func (o IPPoolArrayOutput) ToIPPoolArrayOutput() IPPoolArrayOutput {
	return o
}

func (o IPPoolArrayOutput) ToIPPoolArrayOutputWithContext(ctx context.Context) IPPoolArrayOutput {
	return o
}

func (o IPPoolArrayOutput) Index(i pulumi.IntInput) IPPoolOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *IPPool {
		return vs[0].([]*IPPool)[vs[1].(int)]
	}).(IPPoolOutput)
}

type IPPoolMapOutput struct{ *pulumi.OutputState }

func (IPPoolMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*IPPool)(nil)).Elem()
}

func (o IPPoolMapOutput) ToIPPoolMapOutput() IPPoolMapOutput {
	return o
}

func (o IPPoolMapOutput) ToIPPoolMapOutputWithContext(ctx context.Context) IPPoolMapOutput {
	return o
}

func (o IPPoolMapOutput) MapIndex(k pulumi.StringInput) IPPoolOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *IPPool {
		return vs[0].(map[string]*IPPool)[vs[1].(string)]
	}).(IPPoolOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*IPPoolInput)(nil)).Elem(), &IPPool{})
	pulumi.RegisterInputType(reflect.TypeOf((*IPPoolArrayInput)(nil)).Elem(), IPPoolArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*IPPoolMapInput)(nil)).Elem(), IPPoolMap{})
	pulumi.RegisterOutputType(IPPoolOutput{})
	pulumi.RegisterOutputType(IPPoolArrayOutput{})
	pulumi.RegisterOutputType(IPPoolMapOutput{})
}
