// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package sendgrid

import (
	"context"
	"reflect"

	"errors"
	"github.com/JDetmar/pulumi-sendgrid/sdk/go/sendgrid/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Manages a SendGrid Link Branding.
//
// Link Branding (formerly Link Whitelabel) allows you to customize the links in your emails to use your own domain instead of sendgrid.net. This helps improve deliverability and brand recognition.
//
// After creating this resource, you must add the DNS records to your domain's DNS settings and then validate the link branding using the SendGrid console or API.
type LinkBranding struct {
	pulumi.CustomResourceState

	BrandCname LinkBrandingDNSRecordPtrOutput `pulumi:"brandCname"`
	Default    pulumi.BoolPtrOutput           `pulumi:"default"`
	Domain     pulumi.StringOutput            `pulumi:"domain"`
	Legacy     pulumi.BoolOutput              `pulumi:"legacy"`
	LinkId     pulumi.IntOutput               `pulumi:"linkId"`
	OwnerCname LinkBrandingDNSRecordPtrOutput `pulumi:"ownerCname"`
	Region     pulumi.StringPtrOutput         `pulumi:"region"`
	Subdomain  pulumi.StringPtrOutput         `pulumi:"subdomain"`
	UserId     pulumi.IntOutput               `pulumi:"userId"`
	Username   pulumi.StringOutput            `pulumi:"username"`
	Valid      pulumi.BoolOutput              `pulumi:"valid"`
}

// NewLinkBranding registers a new resource with the given unique name, arguments, and options.
func NewLinkBranding(ctx *pulumi.Context,
	name string, args *LinkBrandingArgs, opts ...pulumi.ResourceOption) (*LinkBranding, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Domain == nil {
		return nil, errors.New("invalid value for required argument 'Domain'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource LinkBranding
	err := ctx.RegisterResource("sendgrid:index:LinkBranding", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetLinkBranding gets an existing LinkBranding resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetLinkBranding(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *LinkBrandingState, opts ...pulumi.ResourceOption) (*LinkBranding, error) {
	var resource LinkBranding
	err := ctx.ReadResource("sendgrid:index:LinkBranding", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering LinkBranding resources.
type linkBrandingState struct {
}

type LinkBrandingState struct {
}

func (LinkBrandingState) ElementType() reflect.Type {
	return reflect.TypeOf((*linkBrandingState)(nil)).Elem()
}

type linkBrandingArgs struct {
	Default   *bool   `pulumi:"default"`
	Domain    string  `pulumi:"domain"`
	Region    *string `pulumi:"region"`
	Subdomain *string `pulumi:"subdomain"`
}

// The set of arguments for constructing a LinkBranding resource.
type LinkBrandingArgs struct {
	Default   pulumi.BoolPtrInput
	Domain    pulumi.StringInput
	Region    pulumi.StringPtrInput
	Subdomain pulumi.StringPtrInput
}

func (LinkBrandingArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*linkBrandingArgs)(nil)).Elem()
}

type LinkBrandingInput interface {
	pulumi.Input

	ToLinkBrandingOutput() LinkBrandingOutput
	ToLinkBrandingOutputWithContext(ctx context.Context) LinkBrandingOutput
}

func (*LinkBranding) ElementType() reflect.Type {
	return reflect.TypeOf((**LinkBranding)(nil)).Elem()
}

func (i *LinkBranding) ToLinkBrandingOutput() LinkBrandingOutput {
	return i.ToLinkBrandingOutputWithContext(context.Background())
}

func (i *LinkBranding) ToLinkBrandingOutputWithContext(ctx context.Context) LinkBrandingOutput {
	return pulumi.ToOutputWithContext(ctx, i).(LinkBrandingOutput)
}

type LinkBrandingOutput struct{ *pulumi.OutputState }

func (LinkBrandingOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**LinkBranding)(nil)).Elem()
}

func (o LinkBrandingOutput) ToLinkBrandingOutput() LinkBrandingOutput {
	return o
}

func (o LinkBrandingOutput) ToLinkBrandingOutputWithContext(ctx context.Context) LinkBrandingOutput {
	return o
}

func (o LinkBrandingOutput) BrandCname() LinkBrandingDNSRecordPtrOutput {
	return o.ApplyT(func(v *LinkBranding) LinkBrandingDNSRecordPtrOutput { return v.BrandCname }).(LinkBrandingDNSRecordPtrOutput)
}

func (o LinkBrandingOutput) Default() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *LinkBranding) pulumi.BoolPtrOutput { return v.Default }).(pulumi.BoolPtrOutput)
}

func (o LinkBrandingOutput) Domain() pulumi.StringOutput {
	return o.ApplyT(func(v *LinkBranding) pulumi.StringOutput { return v.Domain }).(pulumi.StringOutput)
}

func (o LinkBrandingOutput) Legacy() pulumi.BoolOutput {
	return o.ApplyT(func(v *LinkBranding) pulumi.BoolOutput { return v.Legacy }).(pulumi.BoolOutput)
}

func (o LinkBrandingOutput) LinkId() pulumi.IntOutput {
	return o.ApplyT(func(v *LinkBranding) pulumi.IntOutput { return v.LinkId }).(pulumi.IntOutput)
}

func (o LinkBrandingOutput) OwnerCname() LinkBrandingDNSRecordPtrOutput {
	return o.ApplyT(func(v *LinkBranding) LinkBrandingDNSRecordPtrOutput { return v.OwnerCname }).(LinkBrandingDNSRecordPtrOutput)
}

func (o LinkBrandingOutput) Region() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *LinkBranding) pulumi.StringPtrOutput { return v.Region }).(pulumi.StringPtrOutput)
}

func (o LinkBrandingOutput) Subdomain() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *LinkBranding) pulumi.StringPtrOutput { return v.Subdomain }).(pulumi.StringPtrOutput)
}

func (o LinkBrandingOutput) UserId() pulumi.IntOutput {
	return o.ApplyT(func(v *LinkBranding) pulumi.IntOutput { return v.UserId }).(pulumi.IntOutput)
}

func (o LinkBrandingOutput) Username() pulumi.StringOutput {
	return o.ApplyT(func(v *LinkBranding) pulumi.StringOutput { return v.Username }).(pulumi.StringOutput)
}

func (o LinkBrandingOutput) Valid() pulumi.BoolOutput {
	return o.ApplyT(func(v *LinkBranding) pulumi.BoolOutput { return v.Valid }).(pulumi.BoolOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*LinkBrandingInput)(nil)).Elem(), &LinkBranding{})
	pulumi.RegisterOutputType(LinkBrandingOutput{})
}
