// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package sendgrid

import (
	"context"
	"reflect"

	"github.com/JDetmar/pulumi-sendgrid/sdk/go/sendgrid/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

var _ = internal.GetEnvOrDefault

type DNSRecord struct {
	Data  string `pulumi:"data"`
	Host  string `pulumi:"host"`
	Type  string `pulumi:"type"`
	Valid bool   `pulumi:"valid"`
}

type DNSRecordOutput struct{ *pulumi.OutputState }

func (DNSRecordOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*DNSRecord)(nil)).Elem()
}

func (o DNSRecordOutput) ToDNSRecordOutput() DNSRecordOutput {
	return o
}

func (o DNSRecordOutput) ToDNSRecordOutputWithContext(ctx context.Context) DNSRecordOutput {
	return o
}

func (o DNSRecordOutput) Data() pulumi.StringOutput {
	return o.ApplyT(func(v DNSRecord) string { return v.Data }).(pulumi.StringOutput)
}

func (o DNSRecordOutput) Host() pulumi.StringOutput {
	return o.ApplyT(func(v DNSRecord) string { return v.Host }).(pulumi.StringOutput)
}

func (o DNSRecordOutput) Type() pulumi.StringOutput {
	return o.ApplyT(func(v DNSRecord) string { return v.Type }).(pulumi.StringOutput)
}

func (o DNSRecordOutput) Valid() pulumi.BoolOutput {
	return o.ApplyT(func(v DNSRecord) bool { return v.Valid }).(pulumi.BoolOutput)
}

type DNSRecordPtrOutput struct{ *pulumi.OutputState }

func (DNSRecordPtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**DNSRecord)(nil)).Elem()
}

func (o DNSRecordPtrOutput) ToDNSRecordPtrOutput() DNSRecordPtrOutput {
	return o
}

func (o DNSRecordPtrOutput) ToDNSRecordPtrOutputWithContext(ctx context.Context) DNSRecordPtrOutput {
	return o
}

func (o DNSRecordPtrOutput) Elem() DNSRecordOutput {
	return o.ApplyT(func(v *DNSRecord) DNSRecord {
		if v != nil {
			return *v
		}
		var ret DNSRecord
		return ret
	}).(DNSRecordOutput)
}

func (o DNSRecordPtrOutput) Data() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *DNSRecord) *string {
		if v == nil {
			return nil
		}
		return &v.Data
	}).(pulumi.StringPtrOutput)
}

func (o DNSRecordPtrOutput) Host() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *DNSRecord) *string {
		if v == nil {
			return nil
		}
		return &v.Host
	}).(pulumi.StringPtrOutput)
}

func (o DNSRecordPtrOutput) Type() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *DNSRecord) *string {
		if v == nil {
			return nil
		}
		return &v.Type
	}).(pulumi.StringPtrOutput)
}

func (o DNSRecordPtrOutput) Valid() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *DNSRecord) *bool {
		if v == nil {
			return nil
		}
		return &v.Valid
	}).(pulumi.BoolPtrOutput)
}

type TemplateVersionSummary struct {
	Active     bool    `pulumi:"active"`
	Id         string  `pulumi:"id"`
	Name       string  `pulumi:"name"`
	TemplateId string  `pulumi:"templateId"`
	UpdatedAt  *string `pulumi:"updatedAt"`
}

type TemplateVersionSummaryOutput struct{ *pulumi.OutputState }

func (TemplateVersionSummaryOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*TemplateVersionSummary)(nil)).Elem()
}

func (o TemplateVersionSummaryOutput) ToTemplateVersionSummaryOutput() TemplateVersionSummaryOutput {
	return o
}

func (o TemplateVersionSummaryOutput) ToTemplateVersionSummaryOutputWithContext(ctx context.Context) TemplateVersionSummaryOutput {
	return o
}

func (o TemplateVersionSummaryOutput) Active() pulumi.BoolOutput {
	return o.ApplyT(func(v TemplateVersionSummary) bool { return v.Active }).(pulumi.BoolOutput)
}

func (o TemplateVersionSummaryOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v TemplateVersionSummary) string { return v.Id }).(pulumi.StringOutput)
}

func (o TemplateVersionSummaryOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v TemplateVersionSummary) string { return v.Name }).(pulumi.StringOutput)
}

func (o TemplateVersionSummaryOutput) TemplateId() pulumi.StringOutput {
	return o.ApplyT(func(v TemplateVersionSummary) string { return v.TemplateId }).(pulumi.StringOutput)
}

func (o TemplateVersionSummaryOutput) UpdatedAt() pulumi.StringPtrOutput {
	return o.ApplyT(func(v TemplateVersionSummary) *string { return v.UpdatedAt }).(pulumi.StringPtrOutput)
}

type TemplateVersionSummaryArrayOutput struct{ *pulumi.OutputState }

func (TemplateVersionSummaryArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]TemplateVersionSummary)(nil)).Elem()
}

func (o TemplateVersionSummaryArrayOutput) ToTemplateVersionSummaryArrayOutput() TemplateVersionSummaryArrayOutput {
	return o
}

func (o TemplateVersionSummaryArrayOutput) ToTemplateVersionSummaryArrayOutputWithContext(ctx context.Context) TemplateVersionSummaryArrayOutput {
	return o
}

func (o TemplateVersionSummaryArrayOutput) Index(i pulumi.IntInput) TemplateVersionSummaryOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) TemplateVersionSummary {
		return vs[0].([]TemplateVersionSummary)[vs[1].(int)]
	}).(TemplateVersionSummaryOutput)
}

func init() {
	pulumi.RegisterOutputType(DNSRecordOutput{})
	pulumi.RegisterOutputType(DNSRecordPtrOutput{})
	pulumi.RegisterOutputType(TemplateVersionSummaryOutput{})
	pulumi.RegisterOutputType(TemplateVersionSummaryArrayOutput{})
}
