// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package sendgrid

import (
	"context"
	"reflect"

	"errors"
	"github.com/JDetmar/pulumi-sendgrid/sdk/go/sendgrid/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Manages a SendGrid Subuser.
//
// Subusers are separate accounts under a parent account that can be used to segment email sending, maintain separate sending reputations, and organize email workflows. Each subuser has their own credentials and can be assigned specific IP addresses.
//
// Note: The password is only used during creation and cannot be retrieved. Regional subusers require a SendGrid Pro plan or above.
type Subuser struct {
	pulumi.CustomResourceState

	Disabled pulumi.BoolOutput        `pulumi:"disabled"`
	Email    pulumi.StringOutput      `pulumi:"email"`
	Ips      pulumi.StringArrayOutput `pulumi:"ips"`
	Region   pulumi.StringPtrOutput   `pulumi:"region"`
	UserId   pulumi.IntOutput         `pulumi:"userId"`
	Username pulumi.StringOutput      `pulumi:"username"`
}

// NewSubuser registers a new resource with the given unique name, arguments, and options.
func NewSubuser(ctx *pulumi.Context,
	name string, args *SubuserArgs, opts ...pulumi.ResourceOption) (*Subuser, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Email == nil {
		return nil, errors.New("invalid value for required argument 'Email'")
	}
	if args.Password == nil {
		return nil, errors.New("invalid value for required argument 'Password'")
	}
	if args.Username == nil {
		return nil, errors.New("invalid value for required argument 'Username'")
	}
	if args.Password != nil {
		args.Password = pulumi.ToSecret(args.Password).(pulumi.StringInput)
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource Subuser
	err := ctx.RegisterResource("sendgrid:index:Subuser", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetSubuser gets an existing Subuser resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetSubuser(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *SubuserState, opts ...pulumi.ResourceOption) (*Subuser, error) {
	var resource Subuser
	err := ctx.ReadResource("sendgrid:index:Subuser", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering Subuser resources.
type subuserState struct {
}

type SubuserState struct {
}

func (SubuserState) ElementType() reflect.Type {
	return reflect.TypeOf((*subuserState)(nil)).Elem()
}

type subuserArgs struct {
	Disabled *bool    `pulumi:"disabled"`
	Email    string   `pulumi:"email"`
	Ips      []string `pulumi:"ips"`
	Password string   `pulumi:"password"`
	Region   *string  `pulumi:"region"`
	Username string   `pulumi:"username"`
}

// The set of arguments for constructing a Subuser resource.
type SubuserArgs struct {
	Disabled pulumi.BoolPtrInput
	Email    pulumi.StringInput
	Ips      pulumi.StringArrayInput
	Password pulumi.StringInput
	Region   pulumi.StringPtrInput
	Username pulumi.StringInput
}

func (SubuserArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*subuserArgs)(nil)).Elem()
}

type SubuserInput interface {
	pulumi.Input

	ToSubuserOutput() SubuserOutput
	ToSubuserOutputWithContext(ctx context.Context) SubuserOutput
}

func (*Subuser) ElementType() reflect.Type {
	return reflect.TypeOf((**Subuser)(nil)).Elem()
}

func (i *Subuser) ToSubuserOutput() SubuserOutput {
	return i.ToSubuserOutputWithContext(context.Background())
}

func (i *Subuser) ToSubuserOutputWithContext(ctx context.Context) SubuserOutput {
	return pulumi.ToOutputWithContext(ctx, i).(SubuserOutput)
}

// SubuserArrayInput is an input type that accepts SubuserArray and SubuserArrayOutput values.
// You can construct a concrete instance of `SubuserArrayInput` via:
//
//	SubuserArray{ SubuserArgs{...} }
type SubuserArrayInput interface {
	pulumi.Input

	ToSubuserArrayOutput() SubuserArrayOutput
	ToSubuserArrayOutputWithContext(context.Context) SubuserArrayOutput
}

type SubuserArray []SubuserInput

func (SubuserArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*Subuser)(nil)).Elem()
}

func (i SubuserArray) ToSubuserArrayOutput() SubuserArrayOutput {
	return i.ToSubuserArrayOutputWithContext(context.Background())
}

func (i SubuserArray) ToSubuserArrayOutputWithContext(ctx context.Context) SubuserArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(SubuserArrayOutput)
}

// SubuserMapInput is an input type that accepts SubuserMap and SubuserMapOutput values.
// You can construct a concrete instance of `SubuserMapInput` via:
//
//	SubuserMap{ "key": SubuserArgs{...} }
type SubuserMapInput interface {
	pulumi.Input

	ToSubuserMapOutput() SubuserMapOutput
	ToSubuserMapOutputWithContext(context.Context) SubuserMapOutput
}

type SubuserMap map[string]SubuserInput

func (SubuserMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*Subuser)(nil)).Elem()
}

func (i SubuserMap) ToSubuserMapOutput() SubuserMapOutput {
	return i.ToSubuserMapOutputWithContext(context.Background())
}

func (i SubuserMap) ToSubuserMapOutputWithContext(ctx context.Context) SubuserMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(SubuserMapOutput)
}

type SubuserOutput struct{ *pulumi.OutputState }

func (SubuserOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Subuser)(nil)).Elem()
}

func (o SubuserOutput) ToSubuserOutput() SubuserOutput {
	return o
}

func (o SubuserOutput) ToSubuserOutputWithContext(ctx context.Context) SubuserOutput {
	return o
}

func (o SubuserOutput) Disabled() pulumi.BoolOutput {
	return o.ApplyT(func(v *Subuser) pulumi.BoolOutput { return v.Disabled }).(pulumi.BoolOutput)
}

func (o SubuserOutput) Email() pulumi.StringOutput {
	return o.ApplyT(func(v *Subuser) pulumi.StringOutput { return v.Email }).(pulumi.StringOutput)
}

func (o SubuserOutput) Ips() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *Subuser) pulumi.StringArrayOutput { return v.Ips }).(pulumi.StringArrayOutput)
}

func (o SubuserOutput) Region() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Subuser) pulumi.StringPtrOutput { return v.Region }).(pulumi.StringPtrOutput)
}

func (o SubuserOutput) UserId() pulumi.IntOutput {
	return o.ApplyT(func(v *Subuser) pulumi.IntOutput { return v.UserId }).(pulumi.IntOutput)
}

func (o SubuserOutput) Username() pulumi.StringOutput {
	return o.ApplyT(func(v *Subuser) pulumi.StringOutput { return v.Username }).(pulumi.StringOutput)
}

type SubuserArrayOutput struct{ *pulumi.OutputState }

func (SubuserArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*Subuser)(nil)).Elem()
}

func (o SubuserArrayOutput) ToSubuserArrayOutput() SubuserArrayOutput {
	return o
}

func (o SubuserArrayOutput) ToSubuserArrayOutputWithContext(ctx context.Context) SubuserArrayOutput {
	return o
}

func (o SubuserArrayOutput) Index(i pulumi.IntInput) SubuserOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *Subuser {
		return vs[0].([]*Subuser)[vs[1].(int)]
	}).(SubuserOutput)
}

type SubuserMapOutput struct{ *pulumi.OutputState }

func (SubuserMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*Subuser)(nil)).Elem()
}

func (o SubuserMapOutput) ToSubuserMapOutput() SubuserMapOutput {
	return o
}

func (o SubuserMapOutput) ToSubuserMapOutputWithContext(ctx context.Context) SubuserMapOutput {
	return o
}

func (o SubuserMapOutput) MapIndex(k pulumi.StringInput) SubuserOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *Subuser {
		return vs[0].(map[string]*Subuser)[vs[1].(string)]
	}).(SubuserOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*SubuserInput)(nil)).Elem(), &Subuser{})
	pulumi.RegisterInputType(reflect.TypeOf((*SubuserArrayInput)(nil)).Elem(), SubuserArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*SubuserMapInput)(nil)).Elem(), SubuserMap{})
	pulumi.RegisterOutputType(SubuserOutput{})
	pulumi.RegisterOutputType(SubuserArrayOutput{})
	pulumi.RegisterOutputType(SubuserMapOutput{})
}
