// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package sendgrid

import (
	"context"
	"reflect"

	"errors"
	"github.com/JDetmar/pulumi-sendgrid/sdk/go/sendgrid/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Manages a SendGrid Template Version.
//
// Template versions contain the actual content of transactional emails, including the subject line, HTML content, and plain text content.
//
// Each template can have multiple versions, but only one can be active at a time. The active version is used when sending emails through the template.
//
// **Note:** Dynamic templates support handlebars syntax for personalization.
type TemplateVersion struct {
	pulumi.CustomResourceState

	Active               pulumi.IntPtrOutput    `pulumi:"active"`
	Editor               pulumi.StringPtrOutput `pulumi:"editor"`
	GeneratePlainContent pulumi.BoolPtrOutput   `pulumi:"generatePlainContent"`
	HtmlContent          pulumi.StringPtrOutput `pulumi:"htmlContent"`
	Name                 pulumi.StringOutput    `pulumi:"name"`
	PlainContent         pulumi.StringPtrOutput `pulumi:"plainContent"`
	Subject              pulumi.StringPtrOutput `pulumi:"subject"`
	TemplateId           pulumi.StringOutput    `pulumi:"templateId"`
	TestData             pulumi.StringPtrOutput `pulumi:"testData"`
	ThumbnailUrl         pulumi.StringPtrOutput `pulumi:"thumbnailUrl"`
	UpdatedAt            pulumi.StringPtrOutput `pulumi:"updatedAt"`
	VersionId            pulumi.StringOutput    `pulumi:"versionId"`
}

// NewTemplateVersion registers a new resource with the given unique name, arguments, and options.
func NewTemplateVersion(ctx *pulumi.Context,
	name string, args *TemplateVersionArgs, opts ...pulumi.ResourceOption) (*TemplateVersion, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Name == nil {
		return nil, errors.New("invalid value for required argument 'Name'")
	}
	if args.TemplateId == nil {
		return nil, errors.New("invalid value for required argument 'TemplateId'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource TemplateVersion
	err := ctx.RegisterResource("sendgrid:index:TemplateVersion", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetTemplateVersion gets an existing TemplateVersion resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetTemplateVersion(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *TemplateVersionState, opts ...pulumi.ResourceOption) (*TemplateVersion, error) {
	var resource TemplateVersion
	err := ctx.ReadResource("sendgrid:index:TemplateVersion", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering TemplateVersion resources.
type templateVersionState struct {
}

type TemplateVersionState struct {
}

func (TemplateVersionState) ElementType() reflect.Type {
	return reflect.TypeOf((*templateVersionState)(nil)).Elem()
}

type templateVersionArgs struct {
	Active               *int    `pulumi:"active"`
	Editor               *string `pulumi:"editor"`
	GeneratePlainContent *bool   `pulumi:"generatePlainContent"`
	HtmlContent          *string `pulumi:"htmlContent"`
	Name                 string  `pulumi:"name"`
	PlainContent         *string `pulumi:"plainContent"`
	Subject              *string `pulumi:"subject"`
	TemplateId           string  `pulumi:"templateId"`
	TestData             *string `pulumi:"testData"`
}

// The set of arguments for constructing a TemplateVersion resource.
type TemplateVersionArgs struct {
	Active               pulumi.IntPtrInput
	Editor               pulumi.StringPtrInput
	GeneratePlainContent pulumi.BoolPtrInput
	HtmlContent          pulumi.StringPtrInput
	Name                 pulumi.StringInput
	PlainContent         pulumi.StringPtrInput
	Subject              pulumi.StringPtrInput
	TemplateId           pulumi.StringInput
	TestData             pulumi.StringPtrInput
}

func (TemplateVersionArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*templateVersionArgs)(nil)).Elem()
}

type TemplateVersionInput interface {
	pulumi.Input

	ToTemplateVersionOutput() TemplateVersionOutput
	ToTemplateVersionOutputWithContext(ctx context.Context) TemplateVersionOutput
}

func (*TemplateVersion) ElementType() reflect.Type {
	return reflect.TypeOf((**TemplateVersion)(nil)).Elem()
}

func (i *TemplateVersion) ToTemplateVersionOutput() TemplateVersionOutput {
	return i.ToTemplateVersionOutputWithContext(context.Background())
}

func (i *TemplateVersion) ToTemplateVersionOutputWithContext(ctx context.Context) TemplateVersionOutput {
	return pulumi.ToOutputWithContext(ctx, i).(TemplateVersionOutput)
}

// TemplateVersionArrayInput is an input type that accepts TemplateVersionArray and TemplateVersionArrayOutput values.
// You can construct a concrete instance of `TemplateVersionArrayInput` via:
//
//	TemplateVersionArray{ TemplateVersionArgs{...} }
type TemplateVersionArrayInput interface {
	pulumi.Input

	ToTemplateVersionArrayOutput() TemplateVersionArrayOutput
	ToTemplateVersionArrayOutputWithContext(context.Context) TemplateVersionArrayOutput
}

type TemplateVersionArray []TemplateVersionInput

func (TemplateVersionArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*TemplateVersion)(nil)).Elem()
}

func (i TemplateVersionArray) ToTemplateVersionArrayOutput() TemplateVersionArrayOutput {
	return i.ToTemplateVersionArrayOutputWithContext(context.Background())
}

func (i TemplateVersionArray) ToTemplateVersionArrayOutputWithContext(ctx context.Context) TemplateVersionArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(TemplateVersionArrayOutput)
}

// TemplateVersionMapInput is an input type that accepts TemplateVersionMap and TemplateVersionMapOutput values.
// You can construct a concrete instance of `TemplateVersionMapInput` via:
//
//	TemplateVersionMap{ "key": TemplateVersionArgs{...} }
type TemplateVersionMapInput interface {
	pulumi.Input

	ToTemplateVersionMapOutput() TemplateVersionMapOutput
	ToTemplateVersionMapOutputWithContext(context.Context) TemplateVersionMapOutput
}

type TemplateVersionMap map[string]TemplateVersionInput

func (TemplateVersionMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*TemplateVersion)(nil)).Elem()
}

func (i TemplateVersionMap) ToTemplateVersionMapOutput() TemplateVersionMapOutput {
	return i.ToTemplateVersionMapOutputWithContext(context.Background())
}

func (i TemplateVersionMap) ToTemplateVersionMapOutputWithContext(ctx context.Context) TemplateVersionMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(TemplateVersionMapOutput)
}

type TemplateVersionOutput struct{ *pulumi.OutputState }

func (TemplateVersionOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**TemplateVersion)(nil)).Elem()
}

func (o TemplateVersionOutput) ToTemplateVersionOutput() TemplateVersionOutput {
	return o
}

func (o TemplateVersionOutput) ToTemplateVersionOutputWithContext(ctx context.Context) TemplateVersionOutput {
	return o
}

func (o TemplateVersionOutput) Active() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *TemplateVersion) pulumi.IntPtrOutput { return v.Active }).(pulumi.IntPtrOutput)
}

func (o TemplateVersionOutput) Editor() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *TemplateVersion) pulumi.StringPtrOutput { return v.Editor }).(pulumi.StringPtrOutput)
}

func (o TemplateVersionOutput) GeneratePlainContent() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *TemplateVersion) pulumi.BoolPtrOutput { return v.GeneratePlainContent }).(pulumi.BoolPtrOutput)
}

func (o TemplateVersionOutput) HtmlContent() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *TemplateVersion) pulumi.StringPtrOutput { return v.HtmlContent }).(pulumi.StringPtrOutput)
}

func (o TemplateVersionOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *TemplateVersion) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

func (o TemplateVersionOutput) PlainContent() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *TemplateVersion) pulumi.StringPtrOutput { return v.PlainContent }).(pulumi.StringPtrOutput)
}

func (o TemplateVersionOutput) Subject() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *TemplateVersion) pulumi.StringPtrOutput { return v.Subject }).(pulumi.StringPtrOutput)
}

func (o TemplateVersionOutput) TemplateId() pulumi.StringOutput {
	return o.ApplyT(func(v *TemplateVersion) pulumi.StringOutput { return v.TemplateId }).(pulumi.StringOutput)
}

func (o TemplateVersionOutput) TestData() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *TemplateVersion) pulumi.StringPtrOutput { return v.TestData }).(pulumi.StringPtrOutput)
}

func (o TemplateVersionOutput) ThumbnailUrl() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *TemplateVersion) pulumi.StringPtrOutput { return v.ThumbnailUrl }).(pulumi.StringPtrOutput)
}

func (o TemplateVersionOutput) UpdatedAt() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *TemplateVersion) pulumi.StringPtrOutput { return v.UpdatedAt }).(pulumi.StringPtrOutput)
}

func (o TemplateVersionOutput) VersionId() pulumi.StringOutput {
	return o.ApplyT(func(v *TemplateVersion) pulumi.StringOutput { return v.VersionId }).(pulumi.StringOutput)
}

type TemplateVersionArrayOutput struct{ *pulumi.OutputState }

func (TemplateVersionArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*TemplateVersion)(nil)).Elem()
}

func (o TemplateVersionArrayOutput) ToTemplateVersionArrayOutput() TemplateVersionArrayOutput {
	return o
}

func (o TemplateVersionArrayOutput) ToTemplateVersionArrayOutputWithContext(ctx context.Context) TemplateVersionArrayOutput {
	return o
}

func (o TemplateVersionArrayOutput) Index(i pulumi.IntInput) TemplateVersionOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *TemplateVersion {
		return vs[0].([]*TemplateVersion)[vs[1].(int)]
	}).(TemplateVersionOutput)
}

type TemplateVersionMapOutput struct{ *pulumi.OutputState }

func (TemplateVersionMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*TemplateVersion)(nil)).Elem()
}

func (o TemplateVersionMapOutput) ToTemplateVersionMapOutput() TemplateVersionMapOutput {
	return o
}

func (o TemplateVersionMapOutput) ToTemplateVersionMapOutputWithContext(ctx context.Context) TemplateVersionMapOutput {
	return o
}

func (o TemplateVersionMapOutput) MapIndex(k pulumi.StringInput) TemplateVersionOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *TemplateVersion {
		return vs[0].(map[string]*TemplateVersion)[vs[1].(string)]
	}).(TemplateVersionOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*TemplateVersionInput)(nil)).Elem(), &TemplateVersion{})
	pulumi.RegisterInputType(reflect.TypeOf((*TemplateVersionArrayInput)(nil)).Elem(), TemplateVersionArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*TemplateVersionMapInput)(nil)).Elem(), TemplateVersionMap{})
	pulumi.RegisterOutputType(TemplateVersionOutput{})
	pulumi.RegisterOutputType(TemplateVersionArrayOutput{})
	pulumi.RegisterOutputType(TemplateVersionMapOutput{})
}
