// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package sendgrid

import (
	"context"
	"reflect"

	"errors"
	"github.com/JDetmar/pulumi-sendgrid/sdk/go/sendgrid/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Manages a SendGrid Unsubscribe Group (Advanced Suppression Management).
//
// Unsubscribe groups allow recipients to opt out of specific types of emails while still receiving others. For example, you might have separate groups for marketing, newsletters, and product updates, allowing users to choose which types of emails they want to receive.
//
// When a recipient unsubscribes from a group, they will no longer receive emails that are associated with that group.
type UnsubscribeGroup struct {
	pulumi.CustomResourceState

	Description  pulumi.StringPtrOutput `pulumi:"description"`
	GroupId      pulumi.IntOutput       `pulumi:"groupId"`
	IsDefault    pulumi.BoolPtrOutput   `pulumi:"isDefault"`
	Name         pulumi.StringOutput    `pulumi:"name"`
	Unsubscribes pulumi.IntOutput       `pulumi:"unsubscribes"`
}

// NewUnsubscribeGroup registers a new resource with the given unique name, arguments, and options.
func NewUnsubscribeGroup(ctx *pulumi.Context,
	name string, args *UnsubscribeGroupArgs, opts ...pulumi.ResourceOption) (*UnsubscribeGroup, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Name == nil {
		return nil, errors.New("invalid value for required argument 'Name'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource UnsubscribeGroup
	err := ctx.RegisterResource("sendgrid:index:UnsubscribeGroup", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetUnsubscribeGroup gets an existing UnsubscribeGroup resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetUnsubscribeGroup(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *UnsubscribeGroupState, opts ...pulumi.ResourceOption) (*UnsubscribeGroup, error) {
	var resource UnsubscribeGroup
	err := ctx.ReadResource("sendgrid:index:UnsubscribeGroup", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering UnsubscribeGroup resources.
type unsubscribeGroupState struct {
}

type UnsubscribeGroupState struct {
}

func (UnsubscribeGroupState) ElementType() reflect.Type {
	return reflect.TypeOf((*unsubscribeGroupState)(nil)).Elem()
}

type unsubscribeGroupArgs struct {
	Description *string `pulumi:"description"`
	IsDefault   *bool   `pulumi:"isDefault"`
	Name        string  `pulumi:"name"`
}

// The set of arguments for constructing a UnsubscribeGroup resource.
type UnsubscribeGroupArgs struct {
	Description pulumi.StringPtrInput
	IsDefault   pulumi.BoolPtrInput
	Name        pulumi.StringInput
}

func (UnsubscribeGroupArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*unsubscribeGroupArgs)(nil)).Elem()
}

type UnsubscribeGroupInput interface {
	pulumi.Input

	ToUnsubscribeGroupOutput() UnsubscribeGroupOutput
	ToUnsubscribeGroupOutputWithContext(ctx context.Context) UnsubscribeGroupOutput
}

func (*UnsubscribeGroup) ElementType() reflect.Type {
	return reflect.TypeOf((**UnsubscribeGroup)(nil)).Elem()
}

func (i *UnsubscribeGroup) ToUnsubscribeGroupOutput() UnsubscribeGroupOutput {
	return i.ToUnsubscribeGroupOutputWithContext(context.Background())
}

func (i *UnsubscribeGroup) ToUnsubscribeGroupOutputWithContext(ctx context.Context) UnsubscribeGroupOutput {
	return pulumi.ToOutputWithContext(ctx, i).(UnsubscribeGroupOutput)
}

// UnsubscribeGroupArrayInput is an input type that accepts UnsubscribeGroupArray and UnsubscribeGroupArrayOutput values.
// You can construct a concrete instance of `UnsubscribeGroupArrayInput` via:
//
//	UnsubscribeGroupArray{ UnsubscribeGroupArgs{...} }
type UnsubscribeGroupArrayInput interface {
	pulumi.Input

	ToUnsubscribeGroupArrayOutput() UnsubscribeGroupArrayOutput
	ToUnsubscribeGroupArrayOutputWithContext(context.Context) UnsubscribeGroupArrayOutput
}

type UnsubscribeGroupArray []UnsubscribeGroupInput

func (UnsubscribeGroupArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*UnsubscribeGroup)(nil)).Elem()
}

func (i UnsubscribeGroupArray) ToUnsubscribeGroupArrayOutput() UnsubscribeGroupArrayOutput {
	return i.ToUnsubscribeGroupArrayOutputWithContext(context.Background())
}

func (i UnsubscribeGroupArray) ToUnsubscribeGroupArrayOutputWithContext(ctx context.Context) UnsubscribeGroupArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(UnsubscribeGroupArrayOutput)
}

// UnsubscribeGroupMapInput is an input type that accepts UnsubscribeGroupMap and UnsubscribeGroupMapOutput values.
// You can construct a concrete instance of `UnsubscribeGroupMapInput` via:
//
//	UnsubscribeGroupMap{ "key": UnsubscribeGroupArgs{...} }
type UnsubscribeGroupMapInput interface {
	pulumi.Input

	ToUnsubscribeGroupMapOutput() UnsubscribeGroupMapOutput
	ToUnsubscribeGroupMapOutputWithContext(context.Context) UnsubscribeGroupMapOutput
}

type UnsubscribeGroupMap map[string]UnsubscribeGroupInput

func (UnsubscribeGroupMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*UnsubscribeGroup)(nil)).Elem()
}

func (i UnsubscribeGroupMap) ToUnsubscribeGroupMapOutput() UnsubscribeGroupMapOutput {
	return i.ToUnsubscribeGroupMapOutputWithContext(context.Background())
}

func (i UnsubscribeGroupMap) ToUnsubscribeGroupMapOutputWithContext(ctx context.Context) UnsubscribeGroupMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(UnsubscribeGroupMapOutput)
}

type UnsubscribeGroupOutput struct{ *pulumi.OutputState }

func (UnsubscribeGroupOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**UnsubscribeGroup)(nil)).Elem()
}

func (o UnsubscribeGroupOutput) ToUnsubscribeGroupOutput() UnsubscribeGroupOutput {
	return o
}

func (o UnsubscribeGroupOutput) ToUnsubscribeGroupOutputWithContext(ctx context.Context) UnsubscribeGroupOutput {
	return o
}

func (o UnsubscribeGroupOutput) Description() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *UnsubscribeGroup) pulumi.StringPtrOutput { return v.Description }).(pulumi.StringPtrOutput)
}

func (o UnsubscribeGroupOutput) GroupId() pulumi.IntOutput {
	return o.ApplyT(func(v *UnsubscribeGroup) pulumi.IntOutput { return v.GroupId }).(pulumi.IntOutput)
}

func (o UnsubscribeGroupOutput) IsDefault() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *UnsubscribeGroup) pulumi.BoolPtrOutput { return v.IsDefault }).(pulumi.BoolPtrOutput)
}

func (o UnsubscribeGroupOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *UnsubscribeGroup) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

func (o UnsubscribeGroupOutput) Unsubscribes() pulumi.IntOutput {
	return o.ApplyT(func(v *UnsubscribeGroup) pulumi.IntOutput { return v.Unsubscribes }).(pulumi.IntOutput)
}

type UnsubscribeGroupArrayOutput struct{ *pulumi.OutputState }

func (UnsubscribeGroupArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*UnsubscribeGroup)(nil)).Elem()
}

func (o UnsubscribeGroupArrayOutput) ToUnsubscribeGroupArrayOutput() UnsubscribeGroupArrayOutput {
	return o
}

func (o UnsubscribeGroupArrayOutput) ToUnsubscribeGroupArrayOutputWithContext(ctx context.Context) UnsubscribeGroupArrayOutput {
	return o
}

func (o UnsubscribeGroupArrayOutput) Index(i pulumi.IntInput) UnsubscribeGroupOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *UnsubscribeGroup {
		return vs[0].([]*UnsubscribeGroup)[vs[1].(int)]
	}).(UnsubscribeGroupOutput)
}

type UnsubscribeGroupMapOutput struct{ *pulumi.OutputState }

func (UnsubscribeGroupMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*UnsubscribeGroup)(nil)).Elem()
}

func (o UnsubscribeGroupMapOutput) ToUnsubscribeGroupMapOutput() UnsubscribeGroupMapOutput {
	return o
}

func (o UnsubscribeGroupMapOutput) ToUnsubscribeGroupMapOutputWithContext(ctx context.Context) UnsubscribeGroupMapOutput {
	return o
}

func (o UnsubscribeGroupMapOutput) MapIndex(k pulumi.StringInput) UnsubscribeGroupOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *UnsubscribeGroup {
		return vs[0].(map[string]*UnsubscribeGroup)[vs[1].(string)]
	}).(UnsubscribeGroupOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*UnsubscribeGroupInput)(nil)).Elem(), &UnsubscribeGroup{})
	pulumi.RegisterInputType(reflect.TypeOf((*UnsubscribeGroupArrayInput)(nil)).Elem(), UnsubscribeGroupArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*UnsubscribeGroupMapInput)(nil)).Elem(), UnsubscribeGroupMap{})
	pulumi.RegisterOutputType(UnsubscribeGroupOutput{})
	pulumi.RegisterOutputType(UnsubscribeGroupArrayOutput{})
	pulumi.RegisterOutputType(UnsubscribeGroupMapOutput{})
}
