// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package sendgrid

import (
	"context"
	"reflect"

	"errors"
	"github.com/JDetmar/pulumi-sendgrid/sdk/go/sendgrid/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Manages a SendGrid Verified Sender.
//
// Verified Senders are sender identities that have been verified for sending email. After creation, SendGrid will send a verification email to the from_email address. The sender must click the verification link to complete the verification process.
//
// **Note:** The `verified` status will be `false` until the verification email is confirmed.
type VerifiedSender struct {
	pulumi.CustomResourceState

	Address     pulumi.StringOutput    `pulumi:"address"`
	Address2    pulumi.StringPtrOutput `pulumi:"address2"`
	City        pulumi.StringOutput    `pulumi:"city"`
	Country     pulumi.StringOutput    `pulumi:"country"`
	FromEmail   pulumi.StringOutput    `pulumi:"fromEmail"`
	FromName    pulumi.StringPtrOutput `pulumi:"fromName"`
	Locked      pulumi.BoolOutput      `pulumi:"locked"`
	Nickname    pulumi.StringOutput    `pulumi:"nickname"`
	ReplyTo     pulumi.StringOutput    `pulumi:"replyTo"`
	ReplyToName pulumi.StringPtrOutput `pulumi:"replyToName"`
	SenderId    pulumi.IntOutput       `pulumi:"senderId"`
	State       pulumi.StringPtrOutput `pulumi:"state"`
	Verified    pulumi.BoolOutput      `pulumi:"verified"`
	Zip         pulumi.StringPtrOutput `pulumi:"zip"`
}

// NewVerifiedSender registers a new resource with the given unique name, arguments, and options.
func NewVerifiedSender(ctx *pulumi.Context,
	name string, args *VerifiedSenderArgs, opts ...pulumi.ResourceOption) (*VerifiedSender, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Address == nil {
		return nil, errors.New("invalid value for required argument 'Address'")
	}
	if args.City == nil {
		return nil, errors.New("invalid value for required argument 'City'")
	}
	if args.Country == nil {
		return nil, errors.New("invalid value for required argument 'Country'")
	}
	if args.FromEmail == nil {
		return nil, errors.New("invalid value for required argument 'FromEmail'")
	}
	if args.Nickname == nil {
		return nil, errors.New("invalid value for required argument 'Nickname'")
	}
	if args.ReplyTo == nil {
		return nil, errors.New("invalid value for required argument 'ReplyTo'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource VerifiedSender
	err := ctx.RegisterResource("sendgrid:index:VerifiedSender", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetVerifiedSender gets an existing VerifiedSender resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetVerifiedSender(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *VerifiedSenderState, opts ...pulumi.ResourceOption) (*VerifiedSender, error) {
	var resource VerifiedSender
	err := ctx.ReadResource("sendgrid:index:VerifiedSender", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering VerifiedSender resources.
type verifiedSenderState struct {
}

type VerifiedSenderState struct {
}

func (VerifiedSenderState) ElementType() reflect.Type {
	return reflect.TypeOf((*verifiedSenderState)(nil)).Elem()
}

type verifiedSenderArgs struct {
	Address     string  `pulumi:"address"`
	Address2    *string `pulumi:"address2"`
	City        string  `pulumi:"city"`
	Country     string  `pulumi:"country"`
	FromEmail   string  `pulumi:"fromEmail"`
	FromName    *string `pulumi:"fromName"`
	Nickname    string  `pulumi:"nickname"`
	ReplyTo     string  `pulumi:"replyTo"`
	ReplyToName *string `pulumi:"replyToName"`
	State       *string `pulumi:"state"`
	Zip         *string `pulumi:"zip"`
}

// The set of arguments for constructing a VerifiedSender resource.
type VerifiedSenderArgs struct {
	Address     pulumi.StringInput
	Address2    pulumi.StringPtrInput
	City        pulumi.StringInput
	Country     pulumi.StringInput
	FromEmail   pulumi.StringInput
	FromName    pulumi.StringPtrInput
	Nickname    pulumi.StringInput
	ReplyTo     pulumi.StringInput
	ReplyToName pulumi.StringPtrInput
	State       pulumi.StringPtrInput
	Zip         pulumi.StringPtrInput
}

func (VerifiedSenderArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*verifiedSenderArgs)(nil)).Elem()
}

type VerifiedSenderInput interface {
	pulumi.Input

	ToVerifiedSenderOutput() VerifiedSenderOutput
	ToVerifiedSenderOutputWithContext(ctx context.Context) VerifiedSenderOutput
}

func (*VerifiedSender) ElementType() reflect.Type {
	return reflect.TypeOf((**VerifiedSender)(nil)).Elem()
}

func (i *VerifiedSender) ToVerifiedSenderOutput() VerifiedSenderOutput {
	return i.ToVerifiedSenderOutputWithContext(context.Background())
}

func (i *VerifiedSender) ToVerifiedSenderOutputWithContext(ctx context.Context) VerifiedSenderOutput {
	return pulumi.ToOutputWithContext(ctx, i).(VerifiedSenderOutput)
}

type VerifiedSenderOutput struct{ *pulumi.OutputState }

func (VerifiedSenderOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**VerifiedSender)(nil)).Elem()
}

func (o VerifiedSenderOutput) ToVerifiedSenderOutput() VerifiedSenderOutput {
	return o
}

func (o VerifiedSenderOutput) ToVerifiedSenderOutputWithContext(ctx context.Context) VerifiedSenderOutput {
	return o
}

func (o VerifiedSenderOutput) Address() pulumi.StringOutput {
	return o.ApplyT(func(v *VerifiedSender) pulumi.StringOutput { return v.Address }).(pulumi.StringOutput)
}

func (o VerifiedSenderOutput) Address2() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *VerifiedSender) pulumi.StringPtrOutput { return v.Address2 }).(pulumi.StringPtrOutput)
}

func (o VerifiedSenderOutput) City() pulumi.StringOutput {
	return o.ApplyT(func(v *VerifiedSender) pulumi.StringOutput { return v.City }).(pulumi.StringOutput)
}

func (o VerifiedSenderOutput) Country() pulumi.StringOutput {
	return o.ApplyT(func(v *VerifiedSender) pulumi.StringOutput { return v.Country }).(pulumi.StringOutput)
}

func (o VerifiedSenderOutput) FromEmail() pulumi.StringOutput {
	return o.ApplyT(func(v *VerifiedSender) pulumi.StringOutput { return v.FromEmail }).(pulumi.StringOutput)
}

func (o VerifiedSenderOutput) FromName() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *VerifiedSender) pulumi.StringPtrOutput { return v.FromName }).(pulumi.StringPtrOutput)
}

func (o VerifiedSenderOutput) Locked() pulumi.BoolOutput {
	return o.ApplyT(func(v *VerifiedSender) pulumi.BoolOutput { return v.Locked }).(pulumi.BoolOutput)
}

func (o VerifiedSenderOutput) Nickname() pulumi.StringOutput {
	return o.ApplyT(func(v *VerifiedSender) pulumi.StringOutput { return v.Nickname }).(pulumi.StringOutput)
}

func (o VerifiedSenderOutput) ReplyTo() pulumi.StringOutput {
	return o.ApplyT(func(v *VerifiedSender) pulumi.StringOutput { return v.ReplyTo }).(pulumi.StringOutput)
}

func (o VerifiedSenderOutput) ReplyToName() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *VerifiedSender) pulumi.StringPtrOutput { return v.ReplyToName }).(pulumi.StringPtrOutput)
}

func (o VerifiedSenderOutput) SenderId() pulumi.IntOutput {
	return o.ApplyT(func(v *VerifiedSender) pulumi.IntOutput { return v.SenderId }).(pulumi.IntOutput)
}

func (o VerifiedSenderOutput) State() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *VerifiedSender) pulumi.StringPtrOutput { return v.State }).(pulumi.StringPtrOutput)
}

func (o VerifiedSenderOutput) Verified() pulumi.BoolOutput {
	return o.ApplyT(func(v *VerifiedSender) pulumi.BoolOutput { return v.Verified }).(pulumi.BoolOutput)
}

func (o VerifiedSenderOutput) Zip() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *VerifiedSender) pulumi.StringPtrOutput { return v.Zip }).(pulumi.StringPtrOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*VerifiedSenderInput)(nil)).Elem(), &VerifiedSender{})
	pulumi.RegisterOutputType(VerifiedSenderOutput{})
}
