// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.github.jdetmar.pulumi.sendgrid;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Integer;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class AlertArgs extends com.pulumi.resources.ResourceArgs {

    public static final AlertArgs Empty = new AlertArgs();

    @Import(name="emailTo", required=true)
    private Output<String> emailTo;

    public Output<String> emailTo() {
        return this.emailTo;
    }

    @Import(name="frequency")
    private @Nullable Output<String> frequency;

    public Optional<Output<String>> frequency() {
        return Optional.ofNullable(this.frequency);
    }

    @Import(name="percentage")
    private @Nullable Output<Integer> percentage;

    public Optional<Output<Integer>> percentage() {
        return Optional.ofNullable(this.percentage);
    }

    @Import(name="type", required=true)
    private Output<String> type;

    public Output<String> type() {
        return this.type;
    }

    private AlertArgs() {}

    private AlertArgs(AlertArgs $) {
        this.emailTo = $.emailTo;
        this.frequency = $.frequency;
        this.percentage = $.percentage;
        this.type = $.type;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(AlertArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private AlertArgs $;

        public Builder() {
            $ = new AlertArgs();
        }

        public Builder(AlertArgs defaults) {
            $ = new AlertArgs(Objects.requireNonNull(defaults));
        }

        public Builder emailTo(Output<String> emailTo) {
            $.emailTo = emailTo;
            return this;
        }

        public Builder emailTo(String emailTo) {
            return emailTo(Output.of(emailTo));
        }

        public Builder frequency(@Nullable Output<String> frequency) {
            $.frequency = frequency;
            return this;
        }

        public Builder frequency(String frequency) {
            return frequency(Output.of(frequency));
        }

        public Builder percentage(@Nullable Output<Integer> percentage) {
            $.percentage = percentage;
            return this;
        }

        public Builder percentage(Integer percentage) {
            return percentage(Output.of(percentage));
        }

        public Builder type(Output<String> type) {
            $.type = type;
            return this;
        }

        public Builder type(String type) {
            return type(Output.of(type));
        }

        public AlertArgs build() {
            if ($.emailTo == null) {
                throw new MissingRequiredPropertyException("AlertArgs", "emailTo");
            }
            if ($.type == null) {
                throw new MissingRequiredPropertyException("AlertArgs", "type");
            }
            return $;
        }
    }

}
