// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.github.jdetmar.pulumi.sendgrid;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import io.github.jdetmar.pulumi.sendgrid.AlertArgs;
import io.github.jdetmar.pulumi.sendgrid.Utilities;
import java.lang.Integer;
import java.lang.String;
import java.util.Optional;
import javax.annotation.Nullable;

/**
 * Manages a SendGrid Alert.
 * 
 * Alerts notify you via email about important account events. Two types are available:
 * 
 * 1. **usage_limit**: Notifies when your email usage reaches a specified percentage of your plan limit.
 * 2. **stats_notification**: Sends periodic email statistics (daily, weekly, or monthly).
 * 
 * You can create multiple alerts of the same type with different email recipients.
 * 
 */
@ResourceType(type="sendgrid:index:Alert")
public class Alert extends com.pulumi.resources.CustomResource {
    @Export(name="alertId", refs={Integer.class}, tree="[0]")
    private Output<Integer> alertId;

    public Output<Integer> alertId() {
        return this.alertId;
    }
    @Export(name="createdAt", refs={Integer.class}, tree="[0]")
    private Output<Integer> createdAt;

    public Output<Integer> createdAt() {
        return this.createdAt;
    }
    @Export(name="emailTo", refs={String.class}, tree="[0]")
    private Output<String> emailTo;

    public Output<String> emailTo() {
        return this.emailTo;
    }
    @Export(name="frequency", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> frequency;

    public Output<Optional<String>> frequency() {
        return Codegen.optional(this.frequency);
    }
    @Export(name="percentage", refs={Integer.class}, tree="[0]")
    private Output</* @Nullable */ Integer> percentage;

    public Output<Optional<Integer>> percentage() {
        return Codegen.optional(this.percentage);
    }
    @Export(name="type", refs={String.class}, tree="[0]")
    private Output<String> type;

    public Output<String> type() {
        return this.type;
    }
    @Export(name="updatedAt", refs={Integer.class}, tree="[0]")
    private Output<Integer> updatedAt;

    public Output<Integer> updatedAt() {
        return this.updatedAt;
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public Alert(java.lang.String name) {
        this(name, AlertArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public Alert(java.lang.String name, AlertArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public Alert(java.lang.String name, AlertArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("sendgrid:index:Alert", name, makeArgs(args, options), makeResourceOptions(options, Codegen.empty()), false);
    }

    private Alert(java.lang.String name, Output<java.lang.String> id, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("sendgrid:index:Alert", name, null, makeResourceOptions(options, id), false);
    }

    private static AlertArgs makeArgs(AlertArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        if (options != null && options.getUrn().isPresent()) {
            return null;
        }
        return args == null ? AlertArgs.Empty : args;
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<java.lang.String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .pluginDownloadURL("github://api.github.com/JDetmar/pulumi-sendgrid")
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static Alert get(java.lang.String name, Output<java.lang.String> id, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new Alert(name, id, options);
    }
}
