// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.github.jdetmar.pulumi.sendgrid;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Boolean;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class EventWebhookArgs extends com.pulumi.resources.ResourceArgs {

    public static final EventWebhookArgs Empty = new EventWebhookArgs();

    @Import(name="bounce")
    private @Nullable Output<Boolean> bounce;

    public Optional<Output<Boolean>> bounce() {
        return Optional.ofNullable(this.bounce);
    }

    @Import(name="click")
    private @Nullable Output<Boolean> click;

    public Optional<Output<Boolean>> click() {
        return Optional.ofNullable(this.click);
    }

    @Import(name="deferred")
    private @Nullable Output<Boolean> deferred;

    public Optional<Output<Boolean>> deferred() {
        return Optional.ofNullable(this.deferred);
    }

    @Import(name="delivered")
    private @Nullable Output<Boolean> delivered;

    public Optional<Output<Boolean>> delivered() {
        return Optional.ofNullable(this.delivered);
    }

    @Import(name="dropped")
    private @Nullable Output<Boolean> dropped;

    public Optional<Output<Boolean>> dropped() {
        return Optional.ofNullable(this.dropped);
    }

    @Import(name="enabled")
    private @Nullable Output<Boolean> enabled;

    public Optional<Output<Boolean>> enabled() {
        return Optional.ofNullable(this.enabled);
    }

    @Import(name="friendlyName")
    private @Nullable Output<String> friendlyName;

    public Optional<Output<String>> friendlyName() {
        return Optional.ofNullable(this.friendlyName);
    }

    @Import(name="groupResubscribe")
    private @Nullable Output<Boolean> groupResubscribe;

    public Optional<Output<Boolean>> groupResubscribe() {
        return Optional.ofNullable(this.groupResubscribe);
    }

    @Import(name="groupUnsubscribe")
    private @Nullable Output<Boolean> groupUnsubscribe;

    public Optional<Output<Boolean>> groupUnsubscribe() {
        return Optional.ofNullable(this.groupUnsubscribe);
    }

    @Import(name="open")
    private @Nullable Output<Boolean> open;

    public Optional<Output<Boolean>> open() {
        return Optional.ofNullable(this.open);
    }

    @Import(name="processed")
    private @Nullable Output<Boolean> processed;

    public Optional<Output<Boolean>> processed() {
        return Optional.ofNullable(this.processed);
    }

    @Import(name="spamReport")
    private @Nullable Output<Boolean> spamReport;

    public Optional<Output<Boolean>> spamReport() {
        return Optional.ofNullable(this.spamReport);
    }

    @Import(name="unsubscribe")
    private @Nullable Output<Boolean> unsubscribe;

    public Optional<Output<Boolean>> unsubscribe() {
        return Optional.ofNullable(this.unsubscribe);
    }

    @Import(name="url", required=true)
    private Output<String> url;

    public Output<String> url() {
        return this.url;
    }

    private EventWebhookArgs() {}

    private EventWebhookArgs(EventWebhookArgs $) {
        this.bounce = $.bounce;
        this.click = $.click;
        this.deferred = $.deferred;
        this.delivered = $.delivered;
        this.dropped = $.dropped;
        this.enabled = $.enabled;
        this.friendlyName = $.friendlyName;
        this.groupResubscribe = $.groupResubscribe;
        this.groupUnsubscribe = $.groupUnsubscribe;
        this.open = $.open;
        this.processed = $.processed;
        this.spamReport = $.spamReport;
        this.unsubscribe = $.unsubscribe;
        this.url = $.url;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(EventWebhookArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private EventWebhookArgs $;

        public Builder() {
            $ = new EventWebhookArgs();
        }

        public Builder(EventWebhookArgs defaults) {
            $ = new EventWebhookArgs(Objects.requireNonNull(defaults));
        }

        public Builder bounce(@Nullable Output<Boolean> bounce) {
            $.bounce = bounce;
            return this;
        }

        public Builder bounce(Boolean bounce) {
            return bounce(Output.of(bounce));
        }

        public Builder click(@Nullable Output<Boolean> click) {
            $.click = click;
            return this;
        }

        public Builder click(Boolean click) {
            return click(Output.of(click));
        }

        public Builder deferred(@Nullable Output<Boolean> deferred) {
            $.deferred = deferred;
            return this;
        }

        public Builder deferred(Boolean deferred) {
            return deferred(Output.of(deferred));
        }

        public Builder delivered(@Nullable Output<Boolean> delivered) {
            $.delivered = delivered;
            return this;
        }

        public Builder delivered(Boolean delivered) {
            return delivered(Output.of(delivered));
        }

        public Builder dropped(@Nullable Output<Boolean> dropped) {
            $.dropped = dropped;
            return this;
        }

        public Builder dropped(Boolean dropped) {
            return dropped(Output.of(dropped));
        }

        public Builder enabled(@Nullable Output<Boolean> enabled) {
            $.enabled = enabled;
            return this;
        }

        public Builder enabled(Boolean enabled) {
            return enabled(Output.of(enabled));
        }

        public Builder friendlyName(@Nullable Output<String> friendlyName) {
            $.friendlyName = friendlyName;
            return this;
        }

        public Builder friendlyName(String friendlyName) {
            return friendlyName(Output.of(friendlyName));
        }

        public Builder groupResubscribe(@Nullable Output<Boolean> groupResubscribe) {
            $.groupResubscribe = groupResubscribe;
            return this;
        }

        public Builder groupResubscribe(Boolean groupResubscribe) {
            return groupResubscribe(Output.of(groupResubscribe));
        }

        public Builder groupUnsubscribe(@Nullable Output<Boolean> groupUnsubscribe) {
            $.groupUnsubscribe = groupUnsubscribe;
            return this;
        }

        public Builder groupUnsubscribe(Boolean groupUnsubscribe) {
            return groupUnsubscribe(Output.of(groupUnsubscribe));
        }

        public Builder open(@Nullable Output<Boolean> open) {
            $.open = open;
            return this;
        }

        public Builder open(Boolean open) {
            return open(Output.of(open));
        }

        public Builder processed(@Nullable Output<Boolean> processed) {
            $.processed = processed;
            return this;
        }

        public Builder processed(Boolean processed) {
            return processed(Output.of(processed));
        }

        public Builder spamReport(@Nullable Output<Boolean> spamReport) {
            $.spamReport = spamReport;
            return this;
        }

        public Builder spamReport(Boolean spamReport) {
            return spamReport(Output.of(spamReport));
        }

        public Builder unsubscribe(@Nullable Output<Boolean> unsubscribe) {
            $.unsubscribe = unsubscribe;
            return this;
        }

        public Builder unsubscribe(Boolean unsubscribe) {
            return unsubscribe(Output.of(unsubscribe));
        }

        public Builder url(Output<String> url) {
            $.url = url;
            return this;
        }

        public Builder url(String url) {
            return url(Output.of(url));
        }

        public EventWebhookArgs build() {
            if ($.url == null) {
                throw new MissingRequiredPropertyException("EventWebhookArgs", "url");
            }
            return $;
        }
    }

}
