// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.github.jdetmar.pulumi.sendgrid;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;


public final class GlobalSuppressionArgs extends com.pulumi.resources.ResourceArgs {

    public static final GlobalSuppressionArgs Empty = new GlobalSuppressionArgs();

    @Import(name="email", required=true)
    private Output<String> email;

    public Output<String> email() {
        return this.email;
    }

    private GlobalSuppressionArgs() {}

    private GlobalSuppressionArgs(GlobalSuppressionArgs $) {
        this.email = $.email;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GlobalSuppressionArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GlobalSuppressionArgs $;

        public Builder() {
            $ = new GlobalSuppressionArgs();
        }

        public Builder(GlobalSuppressionArgs defaults) {
            $ = new GlobalSuppressionArgs(Objects.requireNonNull(defaults));
        }

        public Builder email(Output<String> email) {
            $.email = email;
            return this;
        }

        public Builder email(String email) {
            return email(Output.of(email));
        }

        public GlobalSuppressionArgs build() {
            if ($.email == null) {
                throw new MissingRequiredPropertyException("GlobalSuppressionArgs", "email");
            }
            return $;
        }
    }

}
