// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.github.jdetmar.pulumi.sendgrid;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import io.github.jdetmar.pulumi.sendgrid.GlobalSuppressionArgs;
import io.github.jdetmar.pulumi.sendgrid.Utilities;
import java.lang.Integer;
import java.lang.String;
import java.util.Optional;
import javax.annotation.Nullable;

/**
 * Manages a SendGrid Global Suppression.
 * 
 * Global suppressions are email addresses that have been unsubscribed from all types of emails. When an email address is globally suppressed, no emails will be sent to that address regardless of the unsubscribe group.
 * 
 * This is useful for managing email addresses that have permanently opted out of all communications, or for test addresses that should never receive emails.
 * 
 */
@ResourceType(type="sendgrid:index:GlobalSuppression")
public class GlobalSuppression extends com.pulumi.resources.CustomResource {
    @Export(name="createdAt", refs={Integer.class}, tree="[0]")
    private Output</* @Nullable */ Integer> createdAt;

    public Output<Optional<Integer>> createdAt() {
        return Codegen.optional(this.createdAt);
    }
    @Export(name="email", refs={String.class}, tree="[0]")
    private Output<String> email;

    public Output<String> email() {
        return this.email;
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public GlobalSuppression(java.lang.String name) {
        this(name, GlobalSuppressionArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public GlobalSuppression(java.lang.String name, GlobalSuppressionArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public GlobalSuppression(java.lang.String name, GlobalSuppressionArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("sendgrid:index:GlobalSuppression", name, makeArgs(args, options), makeResourceOptions(options, Codegen.empty()), false);
    }

    private GlobalSuppression(java.lang.String name, Output<java.lang.String> id, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("sendgrid:index:GlobalSuppression", name, null, makeResourceOptions(options, id), false);
    }

    private static GlobalSuppressionArgs makeArgs(GlobalSuppressionArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        if (options != null && options.getUrn().isPresent()) {
            return null;
        }
        return args == null ? GlobalSuppressionArgs.Empty : args;
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<java.lang.String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .pluginDownloadURL("github://api.github.com/JDetmar/pulumi-sendgrid")
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static GlobalSuppression get(java.lang.String name, Output<java.lang.String> id, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new GlobalSuppression(name, id, options);
    }
}
