// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.github.jdetmar.pulumi.sendgrid;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import io.github.jdetmar.pulumi.sendgrid.IpPoolArgs;
import io.github.jdetmar.pulumi.sendgrid.Utilities;
import java.lang.String;
import java.util.List;
import javax.annotation.Nullable;

/**
 * Manages a SendGrid IP Pool.
 * 
 * IP Pools allow you to group your dedicated SendGrid IP addresses together. For example, you might have separate pools for transactional and marketing emails, so that each pool maintains its own reputation.
 * 
 * Note: Each account can create up to 100 IP pools. IP pools can only be used with IP addresses that have reverse DNS configured.
 * 
 */
@ResourceType(type="sendgrid:index:IpPool")
public class IpPool extends com.pulumi.resources.CustomResource {
    @Export(name="ips", refs={List.class,String.class}, tree="[0,1]")
    private Output<List<String>> ips;

    public Output<List<String>> ips() {
        return this.ips;
    }
    @Export(name="name", refs={String.class}, tree="[0]")
    private Output<String> name;

    public Output<String> name() {
        return this.name;
    }
    @Export(name="poolName", refs={String.class}, tree="[0]")
    private Output<String> poolName;

    public Output<String> poolName() {
        return this.poolName;
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public IpPool(java.lang.String name) {
        this(name, IpPoolArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public IpPool(java.lang.String name, IpPoolArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public IpPool(java.lang.String name, IpPoolArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("sendgrid:index:IpPool", name, makeArgs(args, options), makeResourceOptions(options, Codegen.empty()), false);
    }

    private IpPool(java.lang.String name, Output<java.lang.String> id, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("sendgrid:index:IpPool", name, null, makeResourceOptions(options, id), false);
    }

    private static IpPoolArgs makeArgs(IpPoolArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        if (options != null && options.getUrn().isPresent()) {
            return null;
        }
        return args == null ? IpPoolArgs.Empty : args;
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<java.lang.String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .pluginDownloadURL("github://api.github.com/JDetmar/pulumi-sendgrid")
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static IpPool get(java.lang.String name, Output<java.lang.String> id, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new IpPool(name, id, options);
    }
}
