// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.github.jdetmar.pulumi.sendgrid;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Boolean;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class LinkBrandingArgs extends com.pulumi.resources.ResourceArgs {

    public static final LinkBrandingArgs Empty = new LinkBrandingArgs();

    @Import(name="default")
    private @Nullable Output<Boolean> default_;

    public Optional<Output<Boolean>> default_() {
        return Optional.ofNullable(this.default_);
    }

    @Import(name="domain", required=true)
    private Output<String> domain;

    public Output<String> domain() {
        return this.domain;
    }

    @Import(name="region")
    private @Nullable Output<String> region;

    public Optional<Output<String>> region() {
        return Optional.ofNullable(this.region);
    }

    @Import(name="subdomain")
    private @Nullable Output<String> subdomain;

    public Optional<Output<String>> subdomain() {
        return Optional.ofNullable(this.subdomain);
    }

    private LinkBrandingArgs() {}

    private LinkBrandingArgs(LinkBrandingArgs $) {
        this.default_ = $.default_;
        this.domain = $.domain;
        this.region = $.region;
        this.subdomain = $.subdomain;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(LinkBrandingArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private LinkBrandingArgs $;

        public Builder() {
            $ = new LinkBrandingArgs();
        }

        public Builder(LinkBrandingArgs defaults) {
            $ = new LinkBrandingArgs(Objects.requireNonNull(defaults));
        }

        public Builder default_(@Nullable Output<Boolean> default_) {
            $.default_ = default_;
            return this;
        }

        public Builder default_(Boolean default_) {
            return default_(Output.of(default_));
        }

        public Builder domain(Output<String> domain) {
            $.domain = domain;
            return this;
        }

        public Builder domain(String domain) {
            return domain(Output.of(domain));
        }

        public Builder region(@Nullable Output<String> region) {
            $.region = region;
            return this;
        }

        public Builder region(String region) {
            return region(Output.of(region));
        }

        public Builder subdomain(@Nullable Output<String> subdomain) {
            $.subdomain = subdomain;
            return this;
        }

        public Builder subdomain(String subdomain) {
            return subdomain(Output.of(subdomain));
        }

        public LinkBrandingArgs build() {
            if ($.domain == null) {
                throw new MissingRequiredPropertyException("LinkBrandingArgs", "domain");
            }
            return $;
        }
    }

}
