// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.github.jdetmar.pulumi.sendgrid;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class VerifiedSenderArgs extends com.pulumi.resources.ResourceArgs {

    public static final VerifiedSenderArgs Empty = new VerifiedSenderArgs();

    @Import(name="address", required=true)
    private Output<String> address;

    public Output<String> address() {
        return this.address;
    }

    @Import(name="address2")
    private @Nullable Output<String> address2;

    public Optional<Output<String>> address2() {
        return Optional.ofNullable(this.address2);
    }

    @Import(name="city", required=true)
    private Output<String> city;

    public Output<String> city() {
        return this.city;
    }

    @Import(name="country", required=true)
    private Output<String> country;

    public Output<String> country() {
        return this.country;
    }

    @Import(name="fromEmail", required=true)
    private Output<String> fromEmail;

    public Output<String> fromEmail() {
        return this.fromEmail;
    }

    @Import(name="fromName")
    private @Nullable Output<String> fromName;

    public Optional<Output<String>> fromName() {
        return Optional.ofNullable(this.fromName);
    }

    @Import(name="nickname", required=true)
    private Output<String> nickname;

    public Output<String> nickname() {
        return this.nickname;
    }

    @Import(name="replyTo", required=true)
    private Output<String> replyTo;

    public Output<String> replyTo() {
        return this.replyTo;
    }

    @Import(name="replyToName")
    private @Nullable Output<String> replyToName;

    public Optional<Output<String>> replyToName() {
        return Optional.ofNullable(this.replyToName);
    }

    @Import(name="state")
    private @Nullable Output<String> state;

    public Optional<Output<String>> state() {
        return Optional.ofNullable(this.state);
    }

    @Import(name="zip")
    private @Nullable Output<String> zip;

    public Optional<Output<String>> zip() {
        return Optional.ofNullable(this.zip);
    }

    private VerifiedSenderArgs() {}

    private VerifiedSenderArgs(VerifiedSenderArgs $) {
        this.address = $.address;
        this.address2 = $.address2;
        this.city = $.city;
        this.country = $.country;
        this.fromEmail = $.fromEmail;
        this.fromName = $.fromName;
        this.nickname = $.nickname;
        this.replyTo = $.replyTo;
        this.replyToName = $.replyToName;
        this.state = $.state;
        this.zip = $.zip;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(VerifiedSenderArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private VerifiedSenderArgs $;

        public Builder() {
            $ = new VerifiedSenderArgs();
        }

        public Builder(VerifiedSenderArgs defaults) {
            $ = new VerifiedSenderArgs(Objects.requireNonNull(defaults));
        }

        public Builder address(Output<String> address) {
            $.address = address;
            return this;
        }

        public Builder address(String address) {
            return address(Output.of(address));
        }

        public Builder address2(@Nullable Output<String> address2) {
            $.address2 = address2;
            return this;
        }

        public Builder address2(String address2) {
            return address2(Output.of(address2));
        }

        public Builder city(Output<String> city) {
            $.city = city;
            return this;
        }

        public Builder city(String city) {
            return city(Output.of(city));
        }

        public Builder country(Output<String> country) {
            $.country = country;
            return this;
        }

        public Builder country(String country) {
            return country(Output.of(country));
        }

        public Builder fromEmail(Output<String> fromEmail) {
            $.fromEmail = fromEmail;
            return this;
        }

        public Builder fromEmail(String fromEmail) {
            return fromEmail(Output.of(fromEmail));
        }

        public Builder fromName(@Nullable Output<String> fromName) {
            $.fromName = fromName;
            return this;
        }

        public Builder fromName(String fromName) {
            return fromName(Output.of(fromName));
        }

        public Builder nickname(Output<String> nickname) {
            $.nickname = nickname;
            return this;
        }

        public Builder nickname(String nickname) {
            return nickname(Output.of(nickname));
        }

        public Builder replyTo(Output<String> replyTo) {
            $.replyTo = replyTo;
            return this;
        }

        public Builder replyTo(String replyTo) {
            return replyTo(Output.of(replyTo));
        }

        public Builder replyToName(@Nullable Output<String> replyToName) {
            $.replyToName = replyToName;
            return this;
        }

        public Builder replyToName(String replyToName) {
            return replyToName(Output.of(replyToName));
        }

        public Builder state(@Nullable Output<String> state) {
            $.state = state;
            return this;
        }

        public Builder state(String state) {
            return state(Output.of(state));
        }

        public Builder zip(@Nullable Output<String> zip) {
            $.zip = zip;
            return this;
        }

        public Builder zip(String zip) {
            return zip(Output.of(zip));
        }

        public VerifiedSenderArgs build() {
            if ($.address == null) {
                throw new MissingRequiredPropertyException("VerifiedSenderArgs", "address");
            }
            if ($.city == null) {
                throw new MissingRequiredPropertyException("VerifiedSenderArgs", "city");
            }
            if ($.country == null) {
                throw new MissingRequiredPropertyException("VerifiedSenderArgs", "country");
            }
            if ($.fromEmail == null) {
                throw new MissingRequiredPropertyException("VerifiedSenderArgs", "fromEmail");
            }
            if ($.nickname == null) {
                throw new MissingRequiredPropertyException("VerifiedSenderArgs", "nickname");
            }
            if ($.replyTo == null) {
                throw new MissingRequiredPropertyException("VerifiedSenderArgs", "replyTo");
            }
            return $;
        }
    }

}
