// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Community.Pulumi.Sendgrid
{
    /// <summary>
    /// Manages a SendGrid IP Pool.
    /// 
    /// IP Pools allow you to group your dedicated SendGrid IP addresses together. For example, you might have separate pools for transactional and marketing emails, so that each pool maintains its own reputation.
    /// 
    /// Note: Each account can create up to 100 IP pools. IP pools can only be used with IP addresses that have reverse DNS configured.
    /// </summary>
    [SendgridResourceType("sendgrid:index:IpPool")]
    public partial class IpPool : global::Pulumi.CustomResource
    {
        [Output("ips")]
        public Output<ImmutableArray<string>> Ips { get; private set; } = null!;

        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        [Output("poolName")]
        public Output<string> PoolName { get; private set; } = null!;


        /// <summary>
        /// Create a IpPool resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public IpPool(string name, IpPoolArgs args, CustomResourceOptions? options = null)
            : base("sendgrid:index:IpPool", name, args ?? new IpPoolArgs(), MakeResourceOptions(options, ""))
        {
        }

        private IpPool(string name, Input<string> id, CustomResourceOptions? options = null)
            : base("sendgrid:index:IpPool", name, null, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/JDetmar/pulumi-sendgrid",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing IpPool resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static IpPool Get(string name, Input<string> id, CustomResourceOptions? options = null)
        {
            return new IpPool(name, id, options);
        }
    }

    public sealed class IpPoolArgs : global::Pulumi.ResourceArgs
    {
        [Input("name", required: true)]
        public Input<string> Name { get; set; } = null!;

        public IpPoolArgs()
        {
        }
        public static new IpPoolArgs Empty => new IpPoolArgs();
    }
}
