// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Community.Pulumi.Sendgrid
{
    /// <summary>
    /// Manages a SendGrid Link Branding.
    /// 
    /// Link Branding (formerly Link Whitelabel) allows you to customize the links in your emails to use your own domain instead of sendgrid.net. This helps improve deliverability and brand recognition.
    /// 
    /// After creating this resource, you must add the DNS records to your domain's DNS settings and then validate the link branding using the SendGrid console or API.
    /// </summary>
    [SendgridResourceType("sendgrid:index:LinkBranding")]
    public partial class LinkBranding : global::Pulumi.CustomResource
    {
        [Output("brandCname")]
        public Output<Outputs.LinkBrandingDNSRecord?> BrandCname { get; private set; } = null!;

        [Output("default")]
        public Output<bool?> Default { get; private set; } = null!;

        [Output("domain")]
        public Output<string> Domain { get; private set; } = null!;

        [Output("legacy")]
        public Output<bool> Legacy { get; private set; } = null!;

        [Output("linkId")]
        public Output<int> LinkId { get; private set; } = null!;

        [Output("ownerCname")]
        public Output<Outputs.LinkBrandingDNSRecord?> OwnerCname { get; private set; } = null!;

        [Output("region")]
        public Output<string?> Region { get; private set; } = null!;

        [Output("subdomain")]
        public Output<string?> Subdomain { get; private set; } = null!;

        [Output("userId")]
        public Output<int> UserId { get; private set; } = null!;

        [Output("username")]
        public Output<string> Username { get; private set; } = null!;

        [Output("valid")]
        public Output<bool> Valid { get; private set; } = null!;


        /// <summary>
        /// Create a LinkBranding resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public LinkBranding(string name, LinkBrandingArgs args, CustomResourceOptions? options = null)
            : base("sendgrid:index:LinkBranding", name, args ?? new LinkBrandingArgs(), MakeResourceOptions(options, ""))
        {
        }

        private LinkBranding(string name, Input<string> id, CustomResourceOptions? options = null)
            : base("sendgrid:index:LinkBranding", name, null, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/JDetmar/pulumi-sendgrid",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing LinkBranding resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static LinkBranding Get(string name, Input<string> id, CustomResourceOptions? options = null)
        {
            return new LinkBranding(name, id, options);
        }
    }

    public sealed class LinkBrandingArgs : global::Pulumi.ResourceArgs
    {
        [Input("default")]
        public Input<bool>? Default { get; set; }

        [Input("domain", required: true)]
        public Input<string> Domain { get; set; } = null!;

        [Input("region")]
        public Input<string>? Region { get; set; }

        [Input("subdomain")]
        public Input<string>? Subdomain { get; set; }

        public LinkBrandingArgs()
        {
        }
        public static new LinkBrandingArgs Empty => new LinkBrandingArgs();
    }
}
