// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Community.Pulumi.Sendgrid
{
    /// <summary>
    /// Manages a SendGrid Template Version.
    /// 
    /// Template versions contain the actual content of transactional emails, including the subject line, HTML content, and plain text content.
    /// 
    /// Each template can have multiple versions, but only one can be active at a time. The active version is used when sending emails through the template.
    /// 
    /// **Note:** Dynamic templates support handlebars syntax for personalization.
    /// </summary>
    [SendgridResourceType("sendgrid:index:TemplateVersion")]
    public partial class TemplateVersion : global::Pulumi.CustomResource
    {
        [Output("active")]
        public Output<int?> Active { get; private set; } = null!;

        [Output("editor")]
        public Output<string?> Editor { get; private set; } = null!;

        [Output("generatePlainContent")]
        public Output<bool?> GeneratePlainContent { get; private set; } = null!;

        [Output("htmlContent")]
        public Output<string?> HtmlContent { get; private set; } = null!;

        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        [Output("plainContent")]
        public Output<string?> PlainContent { get; private set; } = null!;

        [Output("subject")]
        public Output<string?> Subject { get; private set; } = null!;

        [Output("templateId")]
        public Output<string> TemplateId { get; private set; } = null!;

        [Output("testData")]
        public Output<string?> TestData { get; private set; } = null!;

        [Output("thumbnailUrl")]
        public Output<string?> ThumbnailUrl { get; private set; } = null!;

        [Output("updatedAt")]
        public Output<string?> UpdatedAt { get; private set; } = null!;

        [Output("versionId")]
        public Output<string> VersionId { get; private set; } = null!;


        /// <summary>
        /// Create a TemplateVersion resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public TemplateVersion(string name, TemplateVersionArgs args, CustomResourceOptions? options = null)
            : base("sendgrid:index:TemplateVersion", name, args ?? new TemplateVersionArgs(), MakeResourceOptions(options, ""))
        {
        }

        private TemplateVersion(string name, Input<string> id, CustomResourceOptions? options = null)
            : base("sendgrid:index:TemplateVersion", name, null, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/JDetmar/pulumi-sendgrid",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing TemplateVersion resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static TemplateVersion Get(string name, Input<string> id, CustomResourceOptions? options = null)
        {
            return new TemplateVersion(name, id, options);
        }
    }

    public sealed class TemplateVersionArgs : global::Pulumi.ResourceArgs
    {
        [Input("active")]
        public Input<int>? Active { get; set; }

        [Input("editor")]
        public Input<string>? Editor { get; set; }

        [Input("generatePlainContent")]
        public Input<bool>? GeneratePlainContent { get; set; }

        [Input("htmlContent")]
        public Input<string>? HtmlContent { get; set; }

        [Input("name", required: true)]
        public Input<string> Name { get; set; } = null!;

        [Input("plainContent")]
        public Input<string>? PlainContent { get; set; }

        [Input("subject")]
        public Input<string>? Subject { get; set; }

        [Input("templateId", required: true)]
        public Input<string> TemplateId { get; set; } = null!;

        [Input("testData")]
        public Input<string>? TestData { get; set; }

        public TemplateVersionArgs()
        {
        }
        public static new TemplateVersionArgs Empty => new TemplateVersionArgs();
    }
}
