// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Community.Pulumi.Sendgrid
{
    /// <summary>
    /// Manages a SendGrid Verified Sender.
    /// 
    /// Verified Senders are sender identities that have been verified for sending email. After creation, SendGrid will send a verification email to the from_email address. The sender must click the verification link to complete the verification process.
    /// 
    /// **Note:** The `verified` status will be `false` until the verification email is confirmed.
    /// </summary>
    [SendgridResourceType("sendgrid:index:VerifiedSender")]
    public partial class VerifiedSender : global::Pulumi.CustomResource
    {
        [Output("address")]
        public Output<string> Address { get; private set; } = null!;

        [Output("address2")]
        public Output<string?> Address2 { get; private set; } = null!;

        [Output("city")]
        public Output<string> City { get; private set; } = null!;

        [Output("country")]
        public Output<string> Country { get; private set; } = null!;

        [Output("fromEmail")]
        public Output<string> FromEmail { get; private set; } = null!;

        [Output("fromName")]
        public Output<string?> FromName { get; private set; } = null!;

        [Output("locked")]
        public Output<bool> Locked { get; private set; } = null!;

        [Output("nickname")]
        public Output<string> Nickname { get; private set; } = null!;

        [Output("replyTo")]
        public Output<string> ReplyTo { get; private set; } = null!;

        [Output("replyToName")]
        public Output<string?> ReplyToName { get; private set; } = null!;

        [Output("senderId")]
        public Output<int> SenderId { get; private set; } = null!;

        [Output("state")]
        public Output<string?> State { get; private set; } = null!;

        [Output("verified")]
        public Output<bool> Verified { get; private set; } = null!;

        [Output("zip")]
        public Output<string?> Zip { get; private set; } = null!;


        /// <summary>
        /// Create a VerifiedSender resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public VerifiedSender(string name, VerifiedSenderArgs args, CustomResourceOptions? options = null)
            : base("sendgrid:index:VerifiedSender", name, args ?? new VerifiedSenderArgs(), MakeResourceOptions(options, ""))
        {
        }

        private VerifiedSender(string name, Input<string> id, CustomResourceOptions? options = null)
            : base("sendgrid:index:VerifiedSender", name, null, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/JDetmar/pulumi-sendgrid",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing VerifiedSender resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static VerifiedSender Get(string name, Input<string> id, CustomResourceOptions? options = null)
        {
            return new VerifiedSender(name, id, options);
        }
    }

    public sealed class VerifiedSenderArgs : global::Pulumi.ResourceArgs
    {
        [Input("address", required: true)]
        public Input<string> Address { get; set; } = null!;

        [Input("address2")]
        public Input<string>? Address2 { get; set; }

        [Input("city", required: true)]
        public Input<string> City { get; set; } = null!;

        [Input("country", required: true)]
        public Input<string> Country { get; set; } = null!;

        [Input("fromEmail", required: true)]
        public Input<string> FromEmail { get; set; } = null!;

        [Input("fromName")]
        public Input<string>? FromName { get; set; }

        [Input("nickname", required: true)]
        public Input<string> Nickname { get; set; } = null!;

        [Input("replyTo", required: true)]
        public Input<string> ReplyTo { get; set; } = null!;

        [Input("replyToName")]
        public Input<string>? ReplyToName { get; set; }

        [Input("state")]
        public Input<string>? State { get; set; }

        [Input("zip")]
        public Input<string>? Zip { get; set; }

        public VerifiedSenderArgs()
        {
        }
        public static new VerifiedSenderArgs Empty => new VerifiedSenderArgs();
    }
}
