// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * Manages a SendGrid Domain Authentication.
 *
 * Domain Authentication (formerly Domain Whitelabel) allows you to authenticate your domain so that emails appear to come directly from your domain, removing the 'via sendgrid.net' message that recipients may see.
 *
 * After creating this resource, you must add the DNS records to your domain's DNS settings and then validate the domain using the SendGrid console or API.
 */
export class DomainAuthentication extends pulumi.CustomResource {
    /**
     * Get an existing DomainAuthentication resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): DomainAuthentication {
        return new DomainAuthentication(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'sendgrid:index:DomainAuthentication';

    /**
     * Returns true if the given object is an instance of DomainAuthentication.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is DomainAuthentication {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === DomainAuthentication.__pulumiType;
    }

    declare public readonly automaticSecurity: pulumi.Output<boolean | undefined>;
    declare public readonly customDkimSelector: pulumi.Output<string | undefined>;
    declare public readonly customSpf: pulumi.Output<boolean | undefined>;
    declare public readonly default: pulumi.Output<boolean | undefined>;
    declare public /*out*/ readonly dkim1: pulumi.Output<outputs.DNSRecord | undefined>;
    declare public /*out*/ readonly dkim2: pulumi.Output<outputs.DNSRecord | undefined>;
    declare public readonly domain: pulumi.Output<string>;
    declare public /*out*/ readonly domainId: pulumi.Output<number>;
    declare public readonly ips: pulumi.Output<string[] | undefined>;
    declare public /*out*/ readonly legacy: pulumi.Output<boolean>;
    declare public /*out*/ readonly mailCname: pulumi.Output<outputs.DNSRecord | undefined>;
    declare public readonly region: pulumi.Output<string | undefined>;
    declare public readonly subdomain: pulumi.Output<string | undefined>;
    declare public /*out*/ readonly userId: pulumi.Output<number>;
    declare public /*out*/ readonly username: pulumi.Output<string>;
    declare public /*out*/ readonly valid: pulumi.Output<boolean>;

    /**
     * Create a DomainAuthentication resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: DomainAuthenticationArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if (args?.domain === undefined && !opts.urn) {
                throw new Error("Missing required property 'domain'");
            }
            resourceInputs["automaticSecurity"] = args?.automaticSecurity;
            resourceInputs["customDkimSelector"] = args?.customDkimSelector;
            resourceInputs["customSpf"] = args?.customSpf;
            resourceInputs["default"] = args?.default;
            resourceInputs["domain"] = args?.domain;
            resourceInputs["ips"] = args?.ips;
            resourceInputs["region"] = args?.region;
            resourceInputs["subdomain"] = args?.subdomain;
            resourceInputs["dkim1"] = undefined /*out*/;
            resourceInputs["dkim2"] = undefined /*out*/;
            resourceInputs["domainId"] = undefined /*out*/;
            resourceInputs["legacy"] = undefined /*out*/;
            resourceInputs["mailCname"] = undefined /*out*/;
            resourceInputs["userId"] = undefined /*out*/;
            resourceInputs["username"] = undefined /*out*/;
            resourceInputs["valid"] = undefined /*out*/;
        } else {
            resourceInputs["automaticSecurity"] = undefined /*out*/;
            resourceInputs["customDkimSelector"] = undefined /*out*/;
            resourceInputs["customSpf"] = undefined /*out*/;
            resourceInputs["default"] = undefined /*out*/;
            resourceInputs["dkim1"] = undefined /*out*/;
            resourceInputs["dkim2"] = undefined /*out*/;
            resourceInputs["domain"] = undefined /*out*/;
            resourceInputs["domainId"] = undefined /*out*/;
            resourceInputs["ips"] = undefined /*out*/;
            resourceInputs["legacy"] = undefined /*out*/;
            resourceInputs["mailCname"] = undefined /*out*/;
            resourceInputs["region"] = undefined /*out*/;
            resourceInputs["subdomain"] = undefined /*out*/;
            resourceInputs["userId"] = undefined /*out*/;
            resourceInputs["username"] = undefined /*out*/;
            resourceInputs["valid"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(DomainAuthentication.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a DomainAuthentication resource.
 */
export interface DomainAuthenticationArgs {
    automaticSecurity?: pulumi.Input<boolean>;
    customDkimSelector?: pulumi.Input<string>;
    customSpf?: pulumi.Input<boolean>;
    default?: pulumi.Input<boolean>;
    domain: pulumi.Input<string>;
    ips?: pulumi.Input<pulumi.Input<string>[]>;
    region?: pulumi.Input<string>;
    subdomain?: pulumi.Input<string>;
}
