// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Manages a SendGrid Event Webhook.
 *
 * Event Webhooks allow you to receive HTTP POST notifications when email events occur, such as delivery, opens, clicks, bounces, and more. Configure the URL endpoint and select which events to track.
 *
 * Note: Only one webhook can be configured per URL. Signature verification must be configured separately after webhook creation.
 */
export class EventWebhook extends pulumi.CustomResource {
    /**
     * Get an existing EventWebhook resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): EventWebhook {
        return new EventWebhook(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'sendgrid:index:EventWebhook';

    /**
     * Returns true if the given object is an instance of EventWebhook.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is EventWebhook {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === EventWebhook.__pulumiType;
    }

    public readonly bounce!: pulumi.Output<boolean | undefined>;
    public readonly click!: pulumi.Output<boolean | undefined>;
    public readonly deferred!: pulumi.Output<boolean | undefined>;
    public readonly delivered!: pulumi.Output<boolean | undefined>;
    public readonly dropped!: pulumi.Output<boolean | undefined>;
    public readonly enabled!: pulumi.Output<boolean | undefined>;
    public readonly friendlyName!: pulumi.Output<string | undefined>;
    public readonly groupResubscribe!: pulumi.Output<boolean | undefined>;
    public readonly groupUnsubscribe!: pulumi.Output<boolean | undefined>;
    public readonly open!: pulumi.Output<boolean | undefined>;
    public readonly processed!: pulumi.Output<boolean | undefined>;
    public readonly spamReport!: pulumi.Output<boolean | undefined>;
    public readonly unsubscribe!: pulumi.Output<boolean | undefined>;
    public readonly url!: pulumi.Output<string>;
    public /*out*/ readonly webhookId!: pulumi.Output<string>;

    /**
     * Create a EventWebhook resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: EventWebhookArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if ((!args || args.url === undefined) && !opts.urn) {
                throw new Error("Missing required property 'url'");
            }
            resourceInputs["bounce"] = args ? args.bounce : undefined;
            resourceInputs["click"] = args ? args.click : undefined;
            resourceInputs["deferred"] = args ? args.deferred : undefined;
            resourceInputs["delivered"] = args ? args.delivered : undefined;
            resourceInputs["dropped"] = args ? args.dropped : undefined;
            resourceInputs["enabled"] = args ? args.enabled : undefined;
            resourceInputs["friendlyName"] = args ? args.friendlyName : undefined;
            resourceInputs["groupResubscribe"] = args ? args.groupResubscribe : undefined;
            resourceInputs["groupUnsubscribe"] = args ? args.groupUnsubscribe : undefined;
            resourceInputs["open"] = args ? args.open : undefined;
            resourceInputs["processed"] = args ? args.processed : undefined;
            resourceInputs["spamReport"] = args ? args.spamReport : undefined;
            resourceInputs["unsubscribe"] = args ? args.unsubscribe : undefined;
            resourceInputs["url"] = args ? args.url : undefined;
            resourceInputs["webhookId"] = undefined /*out*/;
        } else {
            resourceInputs["bounce"] = undefined /*out*/;
            resourceInputs["click"] = undefined /*out*/;
            resourceInputs["deferred"] = undefined /*out*/;
            resourceInputs["delivered"] = undefined /*out*/;
            resourceInputs["dropped"] = undefined /*out*/;
            resourceInputs["enabled"] = undefined /*out*/;
            resourceInputs["friendlyName"] = undefined /*out*/;
            resourceInputs["groupResubscribe"] = undefined /*out*/;
            resourceInputs["groupUnsubscribe"] = undefined /*out*/;
            resourceInputs["open"] = undefined /*out*/;
            resourceInputs["processed"] = undefined /*out*/;
            resourceInputs["spamReport"] = undefined /*out*/;
            resourceInputs["unsubscribe"] = undefined /*out*/;
            resourceInputs["url"] = undefined /*out*/;
            resourceInputs["webhookId"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(EventWebhook.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a EventWebhook resource.
 */
export interface EventWebhookArgs {
    bounce?: pulumi.Input<boolean>;
    click?: pulumi.Input<boolean>;
    deferred?: pulumi.Input<boolean>;
    delivered?: pulumi.Input<boolean>;
    dropped?: pulumi.Input<boolean>;
    enabled?: pulumi.Input<boolean>;
    friendlyName?: pulumi.Input<string>;
    groupResubscribe?: pulumi.Input<boolean>;
    groupUnsubscribe?: pulumi.Input<boolean>;
    open?: pulumi.Input<boolean>;
    processed?: pulumi.Input<boolean>;
    spamReport?: pulumi.Input<boolean>;
    unsubscribe?: pulumi.Input<boolean>;
    url: pulumi.Input<string>;
}
