// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

// Export members:
export { AlertArgs } from "./alert";
export type Alert = import("./alert").Alert;
export const Alert: typeof import("./alert").Alert = null as any;
utilities.lazyLoad(exports, ["Alert"], () => require("./alert"));

export { ApiKeyArgs } from "./apiKey";
export type ApiKey = import("./apiKey").ApiKey;
export const ApiKey: typeof import("./apiKey").ApiKey = null as any;
utilities.lazyLoad(exports, ["ApiKey"], () => require("./apiKey"));

export { DomainAuthenticationArgs } from "./domainAuthentication";
export type DomainAuthentication = import("./domainAuthentication").DomainAuthentication;
export const DomainAuthentication: typeof import("./domainAuthentication").DomainAuthentication = null as any;
utilities.lazyLoad(exports, ["DomainAuthentication"], () => require("./domainAuthentication"));

export { EventWebhookArgs } from "./eventWebhook";
export type EventWebhook = import("./eventWebhook").EventWebhook;
export const EventWebhook: typeof import("./eventWebhook").EventWebhook = null as any;
utilities.lazyLoad(exports, ["EventWebhook"], () => require("./eventWebhook"));

export { GlobalSuppressionArgs } from "./globalSuppression";
export type GlobalSuppression = import("./globalSuppression").GlobalSuppression;
export const GlobalSuppression: typeof import("./globalSuppression").GlobalSuppression = null as any;
utilities.lazyLoad(exports, ["GlobalSuppression"], () => require("./globalSuppression"));

export { IpPoolArgs } from "./ipPool";
export type IpPool = import("./ipPool").IpPool;
export const IpPool: typeof import("./ipPool").IpPool = null as any;
utilities.lazyLoad(exports, ["IpPool"], () => require("./ipPool"));

export { LinkBrandingArgs } from "./linkBranding";
export type LinkBranding = import("./linkBranding").LinkBranding;
export const LinkBranding: typeof import("./linkBranding").LinkBranding = null as any;
utilities.lazyLoad(exports, ["LinkBranding"], () => require("./linkBranding"));

export { ProviderArgs } from "./provider";
export type Provider = import("./provider").Provider;
export const Provider: typeof import("./provider").Provider = null as any;
utilities.lazyLoad(exports, ["Provider"], () => require("./provider"));

export { SubuserArgs } from "./subuser";
export type Subuser = import("./subuser").Subuser;
export const Subuser: typeof import("./subuser").Subuser = null as any;
utilities.lazyLoad(exports, ["Subuser"], () => require("./subuser"));

export { TeammateArgs } from "./teammate";
export type Teammate = import("./teammate").Teammate;
export const Teammate: typeof import("./teammate").Teammate = null as any;
utilities.lazyLoad(exports, ["Teammate"], () => require("./teammate"));

export { TemplateArgs } from "./template";
export type Template = import("./template").Template;
export const Template: typeof import("./template").Template = null as any;
utilities.lazyLoad(exports, ["Template"], () => require("./template"));

export { TemplateVersionArgs } from "./templateVersion";
export type TemplateVersion = import("./templateVersion").TemplateVersion;
export const TemplateVersion: typeof import("./templateVersion").TemplateVersion = null as any;
utilities.lazyLoad(exports, ["TemplateVersion"], () => require("./templateVersion"));

export { UnsubscribeGroupArgs } from "./unsubscribeGroup";
export type UnsubscribeGroup = import("./unsubscribeGroup").UnsubscribeGroup;
export const UnsubscribeGroup: typeof import("./unsubscribeGroup").UnsubscribeGroup = null as any;
utilities.lazyLoad(exports, ["UnsubscribeGroup"], () => require("./unsubscribeGroup"));

export { VerifiedSenderArgs } from "./verifiedSender";
export type VerifiedSender = import("./verifiedSender").VerifiedSender;
export const VerifiedSender: typeof import("./verifiedSender").VerifiedSender = null as any;
utilities.lazyLoad(exports, ["VerifiedSender"], () => require("./verifiedSender"));


// Export sub-modules:
import * as config from "./config";
import * as types from "./types";

export {
    config,
    types,
};

const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "sendgrid:index:Alert":
                return new Alert(name, <any>undefined, { urn })
            case "sendgrid:index:ApiKey":
                return new ApiKey(name, <any>undefined, { urn })
            case "sendgrid:index:DomainAuthentication":
                return new DomainAuthentication(name, <any>undefined, { urn })
            case "sendgrid:index:EventWebhook":
                return new EventWebhook(name, <any>undefined, { urn })
            case "sendgrid:index:GlobalSuppression":
                return new GlobalSuppression(name, <any>undefined, { urn })
            case "sendgrid:index:IpPool":
                return new IpPool(name, <any>undefined, { urn })
            case "sendgrid:index:LinkBranding":
                return new LinkBranding(name, <any>undefined, { urn })
            case "sendgrid:index:Subuser":
                return new Subuser(name, <any>undefined, { urn })
            case "sendgrid:index:Teammate":
                return new Teammate(name, <any>undefined, { urn })
            case "sendgrid:index:Template":
                return new Template(name, <any>undefined, { urn })
            case "sendgrid:index:TemplateVersion":
                return new TemplateVersion(name, <any>undefined, { urn })
            case "sendgrid:index:UnsubscribeGroup":
                return new UnsubscribeGroup(name, <any>undefined, { urn })
            case "sendgrid:index:VerifiedSender":
                return new VerifiedSender(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("sendgrid", "index", _module)
pulumi.runtime.registerResourcePackage("sendgrid", {
    version: utilities.getVersion(),
    constructProvider: (name: string, type: string, urn: string): pulumi.ProviderResource => {
        if (type !== "pulumi:providers:sendgrid") {
            throw new Error(`unknown provider type ${type}`);
        }
        return new Provider(name, <any>undefined, { urn });
    },
});
