// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

// Export members:
export { ApiKeyArgs } from "./apiKey";
export type ApiKey = import("./apiKey").ApiKey;
export const ApiKey: typeof import("./apiKey").ApiKey = null as any;
utilities.lazyLoad(exports, ["ApiKey"], () => require("./apiKey"));

export { ProviderArgs } from "./provider";
export type Provider = import("./provider").Provider;
export const Provider: typeof import("./provider").Provider = null as any;
utilities.lazyLoad(exports, ["Provider"], () => require("./provider"));

export { TemplateArgs } from "./template";
export type Template = import("./template").Template;
export const Template: typeof import("./template").Template = null as any;
utilities.lazyLoad(exports, ["Template"], () => require("./template"));

export { TemplateVersionArgs } from "./templateVersion";
export type TemplateVersion = import("./templateVersion").TemplateVersion;
export const TemplateVersion: typeof import("./templateVersion").TemplateVersion = null as any;
utilities.lazyLoad(exports, ["TemplateVersion"], () => require("./templateVersion"));

export { VerifiedSenderArgs } from "./verifiedSender";
export type VerifiedSender = import("./verifiedSender").VerifiedSender;
export const VerifiedSender: typeof import("./verifiedSender").VerifiedSender = null as any;
utilities.lazyLoad(exports, ["VerifiedSender"], () => require("./verifiedSender"));


// Export sub-modules:
import * as config from "./config";
import * as types from "./types";

export {
    config,
    types,
};

const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "sendgrid:index:ApiKey":
                return new ApiKey(name, <any>undefined, { urn })
            case "sendgrid:index:Template":
                return new Template(name, <any>undefined, { urn })
            case "sendgrid:index:TemplateVersion":
                return new TemplateVersion(name, <any>undefined, { urn })
            case "sendgrid:index:VerifiedSender":
                return new VerifiedSender(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("sendgrid", "index", _module)
pulumi.runtime.registerResourcePackage("sendgrid", {
    version: utilities.getVersion(),
    constructProvider: (name: string, type: string, urn: string): pulumi.ProviderResource => {
        if (type !== "pulumi:providers:sendgrid") {
            throw new Error(`unknown provider type ${type}`);
        }
        return new Provider(name, <any>undefined, { urn });
    },
});
