// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Manages a SendGrid IP Pool.
 *
 * IP Pools allow you to group your dedicated SendGrid IP addresses together. For example, you might have separate pools for transactional and marketing emails, so that each pool maintains its own reputation.
 *
 * Note: Each account can create up to 100 IP pools. IP pools can only be used with IP addresses that have reverse DNS configured.
 */
export class IpPool extends pulumi.CustomResource {
    /**
     * Get an existing IpPool resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): IpPool {
        return new IpPool(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'sendgrid:index:IpPool';

    /**
     * Returns true if the given object is an instance of IpPool.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is IpPool {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === IpPool.__pulumiType;
    }

    public /*out*/ readonly ips!: pulumi.Output<string[]>;
    public readonly name!: pulumi.Output<string>;
    public /*out*/ readonly poolName!: pulumi.Output<string>;

    /**
     * Create a IpPool resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: IpPoolArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if ((!args || args.name === undefined) && !opts.urn) {
                throw new Error("Missing required property 'name'");
            }
            resourceInputs["name"] = args ? args.name : undefined;
            resourceInputs["ips"] = undefined /*out*/;
            resourceInputs["poolName"] = undefined /*out*/;
        } else {
            resourceInputs["ips"] = undefined /*out*/;
            resourceInputs["name"] = undefined /*out*/;
            resourceInputs["poolName"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(IpPool.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a IpPool resource.
 */
export interface IpPoolArgs {
    name: pulumi.Input<string>;
}
