// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * Manages a SendGrid Link Branding.
 *
 * Link Branding (formerly Link Whitelabel) allows you to customize the links in your emails to use your own domain instead of sendgrid.net. This helps improve deliverability and brand recognition.
 *
 * After creating this resource, you must add the DNS records to your domain's DNS settings and then validate the link branding using the SendGrid console or API.
 */
export class LinkBranding extends pulumi.CustomResource {
    /**
     * Get an existing LinkBranding resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): LinkBranding {
        return new LinkBranding(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'sendgrid:index:LinkBranding';

    /**
     * Returns true if the given object is an instance of LinkBranding.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is LinkBranding {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === LinkBranding.__pulumiType;
    }

    declare public /*out*/ readonly brandCname: pulumi.Output<outputs.LinkBrandingDNSRecord | undefined>;
    declare public readonly default: pulumi.Output<boolean | undefined>;
    declare public readonly domain: pulumi.Output<string>;
    declare public /*out*/ readonly legacy: pulumi.Output<boolean>;
    declare public /*out*/ readonly linkId: pulumi.Output<number>;
    declare public /*out*/ readonly ownerCname: pulumi.Output<outputs.LinkBrandingDNSRecord | undefined>;
    declare public readonly region: pulumi.Output<string | undefined>;
    declare public readonly subdomain: pulumi.Output<string | undefined>;
    declare public /*out*/ readonly userId: pulumi.Output<number>;
    declare public /*out*/ readonly username: pulumi.Output<string>;
    declare public /*out*/ readonly valid: pulumi.Output<boolean>;

    /**
     * Create a LinkBranding resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: LinkBrandingArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if (args?.domain === undefined && !opts.urn) {
                throw new Error("Missing required property 'domain'");
            }
            resourceInputs["default"] = args?.default;
            resourceInputs["domain"] = args?.domain;
            resourceInputs["region"] = args?.region;
            resourceInputs["subdomain"] = args?.subdomain;
            resourceInputs["brandCname"] = undefined /*out*/;
            resourceInputs["legacy"] = undefined /*out*/;
            resourceInputs["linkId"] = undefined /*out*/;
            resourceInputs["ownerCname"] = undefined /*out*/;
            resourceInputs["userId"] = undefined /*out*/;
            resourceInputs["username"] = undefined /*out*/;
            resourceInputs["valid"] = undefined /*out*/;
        } else {
            resourceInputs["brandCname"] = undefined /*out*/;
            resourceInputs["default"] = undefined /*out*/;
            resourceInputs["domain"] = undefined /*out*/;
            resourceInputs["legacy"] = undefined /*out*/;
            resourceInputs["linkId"] = undefined /*out*/;
            resourceInputs["ownerCname"] = undefined /*out*/;
            resourceInputs["region"] = undefined /*out*/;
            resourceInputs["subdomain"] = undefined /*out*/;
            resourceInputs["userId"] = undefined /*out*/;
            resourceInputs["username"] = undefined /*out*/;
            resourceInputs["valid"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(LinkBranding.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a LinkBranding resource.
 */
export interface LinkBrandingArgs {
    default?: pulumi.Input<boolean>;
    domain: pulumi.Input<string>;
    region?: pulumi.Input<string>;
    subdomain?: pulumi.Input<string>;
}
