// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Manages a SendGrid Subuser.
 *
 * Subusers are separate accounts under a parent account that can be used to segment email sending, maintain separate sending reputations, and organize email workflows. Each subuser has their own credentials and can be assigned specific IP addresses.
 *
 * Note: The password is only used during creation and cannot be retrieved. Regional subusers require a SendGrid Pro plan or above.
 */
export class Subuser extends pulumi.CustomResource {
    /**
     * Get an existing Subuser resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): Subuser {
        return new Subuser(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'sendgrid:index:Subuser';

    /**
     * Returns true if the given object is an instance of Subuser.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Subuser {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Subuser.__pulumiType;
    }

    declare public readonly disabled: pulumi.Output<boolean>;
    declare public readonly email: pulumi.Output<string>;
    declare public readonly ips: pulumi.Output<string[] | undefined>;
    declare public readonly region: pulumi.Output<string | undefined>;
    declare public /*out*/ readonly userId: pulumi.Output<number>;
    declare public readonly username: pulumi.Output<string>;

    /**
     * Create a Subuser resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: SubuserArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if (args?.email === undefined && !opts.urn) {
                throw new Error("Missing required property 'email'");
            }
            if (args?.password === undefined && !opts.urn) {
                throw new Error("Missing required property 'password'");
            }
            if (args?.username === undefined && !opts.urn) {
                throw new Error("Missing required property 'username'");
            }
            resourceInputs["disabled"] = args?.disabled;
            resourceInputs["email"] = args?.email;
            resourceInputs["ips"] = args?.ips;
            resourceInputs["password"] = args?.password ? pulumi.secret(args.password) : undefined;
            resourceInputs["region"] = args?.region;
            resourceInputs["username"] = args?.username;
            resourceInputs["userId"] = undefined /*out*/;
        } else {
            resourceInputs["disabled"] = undefined /*out*/;
            resourceInputs["email"] = undefined /*out*/;
            resourceInputs["ips"] = undefined /*out*/;
            resourceInputs["region"] = undefined /*out*/;
            resourceInputs["userId"] = undefined /*out*/;
            resourceInputs["username"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Subuser.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a Subuser resource.
 */
export interface SubuserArgs {
    disabled?: pulumi.Input<boolean>;
    email: pulumi.Input<string>;
    ips?: pulumi.Input<pulumi.Input<string>[]>;
    password: pulumi.Input<string>;
    region?: pulumi.Input<string>;
    username: pulumi.Input<string>;
}
