// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Manages a SendGrid Teammate.
 *
 * Teammates are users who have access to your SendGrid account with configurable permissions. You can invite teammates via email and set their initial permissions using scopes.
 *
 * Note: Teammate invitations expire after 7 days. The invitation can be resent to reset the expiration. Free and Essentials plans allow only one teammate per account.
 */
export class Teammate extends pulumi.CustomResource {
    /**
     * Get an existing Teammate resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): Teammate {
        return new Teammate(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'sendgrid:index:Teammate';

    /**
     * Returns true if the given object is an instance of Teammate.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Teammate {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Teammate.__pulumiType;
    }

    declare public readonly email: pulumi.Output<string>;
    declare public /*out*/ readonly firstName: pulumi.Output<string | undefined>;
    declare public readonly isAdmin: pulumi.Output<boolean>;
    declare public /*out*/ readonly lastName: pulumi.Output<string | undefined>;
    declare public readonly scopes: pulumi.Output<string[] | undefined>;
    declare public /*out*/ readonly token: pulumi.Output<string | undefined>;
    declare public /*out*/ readonly userType: pulumi.Output<string | undefined>;
    declare public /*out*/ readonly username: pulumi.Output<string | undefined>;

    /**
     * Create a Teammate resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: TeammateArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if (args?.email === undefined && !opts.urn) {
                throw new Error("Missing required property 'email'");
            }
            resourceInputs["email"] = args?.email;
            resourceInputs["isAdmin"] = args?.isAdmin;
            resourceInputs["scopes"] = args?.scopes;
            resourceInputs["firstName"] = undefined /*out*/;
            resourceInputs["lastName"] = undefined /*out*/;
            resourceInputs["token"] = undefined /*out*/;
            resourceInputs["userType"] = undefined /*out*/;
            resourceInputs["username"] = undefined /*out*/;
        } else {
            resourceInputs["email"] = undefined /*out*/;
            resourceInputs["firstName"] = undefined /*out*/;
            resourceInputs["isAdmin"] = undefined /*out*/;
            resourceInputs["lastName"] = undefined /*out*/;
            resourceInputs["scopes"] = undefined /*out*/;
            resourceInputs["token"] = undefined /*out*/;
            resourceInputs["userType"] = undefined /*out*/;
            resourceInputs["username"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Teammate.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a Teammate resource.
 */
export interface TeammateArgs {
    email: pulumi.Input<string>;
    isAdmin?: pulumi.Input<boolean>;
    scopes?: pulumi.Input<pulumi.Input<string>[]>;
}
