// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Manages a SendGrid Template Version.
 *
 * Template versions contain the actual content of transactional emails, including the subject line, HTML content, and plain text content.
 *
 * Each template can have multiple versions, but only one can be active at a time. The active version is used when sending emails through the template.
 *
 * **Note:** Dynamic templates support handlebars syntax for personalization.
 */
export class TemplateVersion extends pulumi.CustomResource {
    /**
     * Get an existing TemplateVersion resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): TemplateVersion {
        return new TemplateVersion(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'sendgrid:index:TemplateVersion';

    /**
     * Returns true if the given object is an instance of TemplateVersion.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is TemplateVersion {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === TemplateVersion.__pulumiType;
    }

    public readonly active!: pulumi.Output<number | undefined>;
    public readonly editor!: pulumi.Output<string | undefined>;
    public readonly generatePlainContent!: pulumi.Output<boolean | undefined>;
    public readonly htmlContent!: pulumi.Output<string | undefined>;
    public readonly name!: pulumi.Output<string>;
    public readonly plainContent!: pulumi.Output<string | undefined>;
    public readonly subject!: pulumi.Output<string | undefined>;
    public readonly templateId!: pulumi.Output<string>;
    public readonly testData!: pulumi.Output<string | undefined>;
    public /*out*/ readonly thumbnailUrl!: pulumi.Output<string | undefined>;
    public /*out*/ readonly updatedAt!: pulumi.Output<string | undefined>;
    public /*out*/ readonly versionId!: pulumi.Output<string>;

    /**
     * Create a TemplateVersion resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: TemplateVersionArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if ((!args || args.name === undefined) && !opts.urn) {
                throw new Error("Missing required property 'name'");
            }
            if ((!args || args.templateId === undefined) && !opts.urn) {
                throw new Error("Missing required property 'templateId'");
            }
            resourceInputs["active"] = args ? args.active : undefined;
            resourceInputs["editor"] = args ? args.editor : undefined;
            resourceInputs["generatePlainContent"] = args ? args.generatePlainContent : undefined;
            resourceInputs["htmlContent"] = args ? args.htmlContent : undefined;
            resourceInputs["name"] = args ? args.name : undefined;
            resourceInputs["plainContent"] = args ? args.plainContent : undefined;
            resourceInputs["subject"] = args ? args.subject : undefined;
            resourceInputs["templateId"] = args ? args.templateId : undefined;
            resourceInputs["testData"] = args ? args.testData : undefined;
            resourceInputs["thumbnailUrl"] = undefined /*out*/;
            resourceInputs["updatedAt"] = undefined /*out*/;
            resourceInputs["versionId"] = undefined /*out*/;
        } else {
            resourceInputs["active"] = undefined /*out*/;
            resourceInputs["editor"] = undefined /*out*/;
            resourceInputs["generatePlainContent"] = undefined /*out*/;
            resourceInputs["htmlContent"] = undefined /*out*/;
            resourceInputs["name"] = undefined /*out*/;
            resourceInputs["plainContent"] = undefined /*out*/;
            resourceInputs["subject"] = undefined /*out*/;
            resourceInputs["templateId"] = undefined /*out*/;
            resourceInputs["testData"] = undefined /*out*/;
            resourceInputs["thumbnailUrl"] = undefined /*out*/;
            resourceInputs["updatedAt"] = undefined /*out*/;
            resourceInputs["versionId"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(TemplateVersion.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a TemplateVersion resource.
 */
export interface TemplateVersionArgs {
    active?: pulumi.Input<number>;
    editor?: pulumi.Input<string>;
    generatePlainContent?: pulumi.Input<boolean>;
    htmlContent?: pulumi.Input<string>;
    name: pulumi.Input<string>;
    plainContent?: pulumi.Input<string>;
    subject?: pulumi.Input<string>;
    templateId: pulumi.Input<string>;
    testData?: pulumi.Input<string>;
}
