// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Manages a SendGrid Unsubscribe Group (Advanced Suppression Management).
 *
 * Unsubscribe groups allow recipients to opt out of specific types of emails while still receiving others. For example, you might have separate groups for marketing, newsletters, and product updates, allowing users to choose which types of emails they want to receive.
 *
 * When a recipient unsubscribes from a group, they will no longer receive emails that are associated with that group.
 */
export class UnsubscribeGroup extends pulumi.CustomResource {
    /**
     * Get an existing UnsubscribeGroup resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): UnsubscribeGroup {
        return new UnsubscribeGroup(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'sendgrid:index:UnsubscribeGroup';

    /**
     * Returns true if the given object is an instance of UnsubscribeGroup.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is UnsubscribeGroup {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === UnsubscribeGroup.__pulumiType;
    }

    public readonly description!: pulumi.Output<string | undefined>;
    public /*out*/ readonly groupId!: pulumi.Output<number>;
    public readonly isDefault!: pulumi.Output<boolean | undefined>;
    public readonly name!: pulumi.Output<string>;
    public /*out*/ readonly unsubscribes!: pulumi.Output<number>;

    /**
     * Create a UnsubscribeGroup resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: UnsubscribeGroupArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if ((!args || args.name === undefined) && !opts.urn) {
                throw new Error("Missing required property 'name'");
            }
            resourceInputs["description"] = args ? args.description : undefined;
            resourceInputs["isDefault"] = args ? args.isDefault : undefined;
            resourceInputs["name"] = args ? args.name : undefined;
            resourceInputs["groupId"] = undefined /*out*/;
            resourceInputs["unsubscribes"] = undefined /*out*/;
        } else {
            resourceInputs["description"] = undefined /*out*/;
            resourceInputs["groupId"] = undefined /*out*/;
            resourceInputs["isDefault"] = undefined /*out*/;
            resourceInputs["name"] = undefined /*out*/;
            resourceInputs["unsubscribes"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(UnsubscribeGroup.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a UnsubscribeGroup resource.
 */
export interface UnsubscribeGroupArgs {
    description?: pulumi.Input<string>;
    isDefault?: pulumi.Input<boolean>;
    name: pulumi.Input<string>;
}
