// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Manages a SendGrid Verified Sender.
 *
 * Verified Senders are sender identities that have been verified for sending email. After creation, SendGrid will send a verification email to the from_email address. The sender must click the verification link to complete the verification process.
 *
 * **Note:** The `verified` status will be `false` until the verification email is confirmed.
 */
export class VerifiedSender extends pulumi.CustomResource {
    /**
     * Get an existing VerifiedSender resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): VerifiedSender {
        return new VerifiedSender(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'sendgrid:index:VerifiedSender';

    /**
     * Returns true if the given object is an instance of VerifiedSender.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is VerifiedSender {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === VerifiedSender.__pulumiType;
    }

    declare public readonly address: pulumi.Output<string>;
    declare public readonly address2: pulumi.Output<string | undefined>;
    declare public readonly city: pulumi.Output<string>;
    declare public readonly country: pulumi.Output<string>;
    declare public readonly fromEmail: pulumi.Output<string>;
    declare public readonly fromName: pulumi.Output<string | undefined>;
    declare public /*out*/ readonly locked: pulumi.Output<boolean>;
    declare public readonly nickname: pulumi.Output<string>;
    declare public readonly replyTo: pulumi.Output<string>;
    declare public readonly replyToName: pulumi.Output<string | undefined>;
    declare public /*out*/ readonly senderId: pulumi.Output<number>;
    declare public readonly state: pulumi.Output<string | undefined>;
    declare public /*out*/ readonly verified: pulumi.Output<boolean>;
    declare public readonly zip: pulumi.Output<string | undefined>;

    /**
     * Create a VerifiedSender resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: VerifiedSenderArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if (args?.address === undefined && !opts.urn) {
                throw new Error("Missing required property 'address'");
            }
            if (args?.city === undefined && !opts.urn) {
                throw new Error("Missing required property 'city'");
            }
            if (args?.country === undefined && !opts.urn) {
                throw new Error("Missing required property 'country'");
            }
            if (args?.fromEmail === undefined && !opts.urn) {
                throw new Error("Missing required property 'fromEmail'");
            }
            if (args?.nickname === undefined && !opts.urn) {
                throw new Error("Missing required property 'nickname'");
            }
            if (args?.replyTo === undefined && !opts.urn) {
                throw new Error("Missing required property 'replyTo'");
            }
            resourceInputs["address"] = args?.address;
            resourceInputs["address2"] = args?.address2;
            resourceInputs["city"] = args?.city;
            resourceInputs["country"] = args?.country;
            resourceInputs["fromEmail"] = args?.fromEmail;
            resourceInputs["fromName"] = args?.fromName;
            resourceInputs["nickname"] = args?.nickname;
            resourceInputs["replyTo"] = args?.replyTo;
            resourceInputs["replyToName"] = args?.replyToName;
            resourceInputs["state"] = args?.state;
            resourceInputs["zip"] = args?.zip;
            resourceInputs["locked"] = undefined /*out*/;
            resourceInputs["senderId"] = undefined /*out*/;
            resourceInputs["verified"] = undefined /*out*/;
        } else {
            resourceInputs["address"] = undefined /*out*/;
            resourceInputs["address2"] = undefined /*out*/;
            resourceInputs["city"] = undefined /*out*/;
            resourceInputs["country"] = undefined /*out*/;
            resourceInputs["fromEmail"] = undefined /*out*/;
            resourceInputs["fromName"] = undefined /*out*/;
            resourceInputs["locked"] = undefined /*out*/;
            resourceInputs["nickname"] = undefined /*out*/;
            resourceInputs["replyTo"] = undefined /*out*/;
            resourceInputs["replyToName"] = undefined /*out*/;
            resourceInputs["senderId"] = undefined /*out*/;
            resourceInputs["state"] = undefined /*out*/;
            resourceInputs["verified"] = undefined /*out*/;
            resourceInputs["zip"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(VerifiedSender.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a VerifiedSender resource.
 */
export interface VerifiedSenderArgs {
    address: pulumi.Input<string>;
    address2?: pulumi.Input<string>;
    city: pulumi.Input<string>;
    country: pulumi.Input<string>;
    fromEmail: pulumi.Input<string>;
    fromName?: pulumi.Input<string>;
    nickname: pulumi.Input<string>;
    replyTo: pulumi.Input<string>;
    replyToName?: pulumi.Input<string>;
    state?: pulumi.Input<string>;
    zip?: pulumi.Input<string>;
}
