// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.github.jdetmar.pulumi.sendgrid.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Boolean;
import java.lang.String;
import java.util.Objects;

@CustomType
public final class LinkBrandingDNSRecord {
    private String data;
    private String host;
    private String type;
    private Boolean valid;

    private LinkBrandingDNSRecord() {}
    public String data() {
        return this.data;
    }
    public String host() {
        return this.host;
    }
    public String type() {
        return this.type;
    }
    public Boolean valid() {
        return this.valid;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(LinkBrandingDNSRecord defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String data;
        private String host;
        private String type;
        private Boolean valid;
        public Builder() {}
        public Builder(LinkBrandingDNSRecord defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.data = defaults.data;
    	      this.host = defaults.host;
    	      this.type = defaults.type;
    	      this.valid = defaults.valid;
        }

        @CustomType.Setter
        public Builder data(String data) {
            if (data == null) {
              throw new MissingRequiredPropertyException("LinkBrandingDNSRecord", "data");
            }
            this.data = data;
            return this;
        }
        @CustomType.Setter
        public Builder host(String host) {
            if (host == null) {
              throw new MissingRequiredPropertyException("LinkBrandingDNSRecord", "host");
            }
            this.host = host;
            return this;
        }
        @CustomType.Setter
        public Builder type(String type) {
            if (type == null) {
              throw new MissingRequiredPropertyException("LinkBrandingDNSRecord", "type");
            }
            this.type = type;
            return this;
        }
        @CustomType.Setter
        public Builder valid(Boolean valid) {
            if (valid == null) {
              throw new MissingRequiredPropertyException("LinkBrandingDNSRecord", "valid");
            }
            this.valid = valid;
            return this;
        }
        public LinkBrandingDNSRecord build() {
            final var _resultValue = new LinkBrandingDNSRecord();
            _resultValue.data = data;
            _resultValue.host = host;
            _resultValue.type = type;
            _resultValue.valid = valid;
            return _resultValue;
        }
    }
}
