// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.github.jdetmar.pulumi.sendgrid.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Boolean;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class TemplateVersionSummary {
    private Boolean active;
    private String id;
    private String name;
    private String templateId;
    private @Nullable String updatedAt;

    private TemplateVersionSummary() {}
    public Boolean active() {
        return this.active;
    }
    public String id() {
        return this.id;
    }
    public String name() {
        return this.name;
    }
    public String templateId() {
        return this.templateId;
    }
    public Optional<String> updatedAt() {
        return Optional.ofNullable(this.updatedAt);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(TemplateVersionSummary defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private Boolean active;
        private String id;
        private String name;
        private String templateId;
        private @Nullable String updatedAt;
        public Builder() {}
        public Builder(TemplateVersionSummary defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.active = defaults.active;
    	      this.id = defaults.id;
    	      this.name = defaults.name;
    	      this.templateId = defaults.templateId;
    	      this.updatedAt = defaults.updatedAt;
        }

        @CustomType.Setter
        public Builder active(Boolean active) {
            if (active == null) {
              throw new MissingRequiredPropertyException("TemplateVersionSummary", "active");
            }
            this.active = active;
            return this;
        }
        @CustomType.Setter
        public Builder id(String id) {
            if (id == null) {
              throw new MissingRequiredPropertyException("TemplateVersionSummary", "id");
            }
            this.id = id;
            return this;
        }
        @CustomType.Setter
        public Builder name(String name) {
            if (name == null) {
              throw new MissingRequiredPropertyException("TemplateVersionSummary", "name");
            }
            this.name = name;
            return this;
        }
        @CustomType.Setter
        public Builder templateId(String templateId) {
            if (templateId == null) {
              throw new MissingRequiredPropertyException("TemplateVersionSummary", "templateId");
            }
            this.templateId = templateId;
            return this;
        }
        @CustomType.Setter
        public Builder updatedAt(@Nullable String updatedAt) {

            this.updatedAt = updatedAt;
            return this;
        }
        public TemplateVersionSummary build() {
            final var _resultValue = new TemplateVersionSummary();
            _resultValue.active = active;
            _resultValue.id = id;
            _resultValue.name = name;
            _resultValue.templateId = templateId;
            _resultValue.updatedAt = updatedAt;
            return _resultValue;
        }
    }
}
